Intel SPMD Program Compiler: constant_scanner::constant_iterator Class Reference
constant_scanner::constant_iterator Class Reference
Public Member Functions
constant_iterator (const llvm::Function *F)
constant_iterator (const llvm::Function *F, bool)
bool operator== (const constant_iterator &x) const
bool operator!= (const constant_iterator &x) const
pointer operator* () const
constant_iterator & operator++ ()
Private Member Functions
bool isAtConstant () const
Private Attributes
llvm::const_inst_iterator InstI
unsigned OpIdx
Detailed Description
Definition at line 145 of file cbackend.cpp.
Constructor & Destructor Documentation
constant_iterator() [1/2]
constant_scanner::constant_iterator::constant_iterator (const llvm::Function * F) inline
Definition at line 155 of file cbackend.cpp.
References InstI, isAtConstant(), and operator++().
constant_iterator() [2/2]
constant_scanner::constant_iterator::constant_iterator (const llvm::Function * F, bool) inline
Definition at line 162 of file cbackend.cpp.
Member Function Documentation
isAtConstant()
bool constant_scanner::constant_iterator::isAtConstant () const inline private
Definition at line 149 of file cbackend.cpp.
References InstI, and OpIdx.
Referenced by constant_iterator(), operator*(), and operator++().
operator!=()
bool constant_scanner::constant_iterator::operator!= (const constant_iterator & x) const inline
Definition at line 166 of file cbackend.cpp.
operator*()
pointer constant_scanner::constant_iterator::operator* () const inline
Definition at line 168 of file cbackend.cpp.
References InstI, isAtConstant(), and OpIdx.
operator++()
constant_iterator& constant_scanner::constant_iterator::operator++ () inline
Definition at line 173 of file cbackend.cpp.
References InstI, isAtConstant(), and OpIdx.
Referenced by constant_iterator().
operator==()
bool constant_scanner::constant_iterator::operator== (const constant_iterator & x) const inline
Definition at line 165 of file cbackend.cpp.
References InstI, and OpIdx.
Member Data Documentation
InstI
llvm::const_inst_iterator constant_scanner::constant_iterator::InstI private
Definition at line 146 of file cbackend.cpp.
Referenced by constant_iterator(), isAtConstant(), operator*(), operator++(), and operator==().
OpIdx
unsigned constant_scanner::constant_iterator::OpIdx private
Definition at line 147 of file cbackend.cpp.
Referenced by isAtConstant(), operator*(), operator++(), and operator==().
The documentation for this class was generated from the following file:
cbackend.cpp