Intel SPMD Program Compiler: IntrinsicsOpt Class Reference
IntrinsicsOpt Class Reference
Classes
struct BlendInstruction
struct MaskInstruction
Public Member Functions
IntrinsicsOpt ()
const char * getPassName () const
bool runOnBasicBlock (llvm::BasicBlock &BB)
Static Public Attributes
static char ID = 0
Private Member Functions
bool matchesMaskInstruction (llvm::Function *function)
BlendInstruction * matchingBlendInstruction (llvm::Function *function)
Private Attributes
std::vector< MaskInstruction > maskInstructions
std::vector< BlendInstruction > blendInstructions
Detailed Description
This is a relatively simple optimization pass that does a few small optimizations that LLVM's x86 optimizer doesn't currently handle. (Specifically, MOVMSK of a constant can be replaced with the corresponding constant value, BLENDVPS and AVX masked load/store with either an 'all on' or 'all off' masks can be replaced with simpler operations.
Todo:
The better thing to do would be to submit a patch to LLVM to get these; they're presumably pretty simple patterns to match.
Definition at line 696 of file opt.cpp.
Constructor & Destructor Documentation
IntrinsicsOpt::IntrinsicsOpt ()
Definition at line 741 of file opt.cpp.
References Assert, blendInstructions, m, maskInstructions, and Module::module.
Member Function Documentation
const char* IntrinsicsOpt::getPassName () const inline
Definition at line 700 of file opt.cpp.
bool IntrinsicsOpt::matchesMaskInstruction (llvm::Function * function) private
Definition at line 970 of file opt.cpp.
References maskInstructions.
Referenced by runOnBasicBlock().
IntrinsicsOpt::BlendInstruction * IntrinsicsOpt::matchingBlendInstruction (llvm::Function * function) private
Definition at line 980 of file opt.cpp.
References blendInstructions.
Referenced by runOnBasicBlock().
bool IntrinsicsOpt::runOnBasicBlock (llvm::BasicBlock & BB)
Definition at line 792 of file opt.cpp.
References IntrinsicsOpt::BlendInstruction::allOnMask, Assert, DEBUG_END_PASS, DEBUG_START_PASS, Opt::forceAlignedMemory, g, Target::getNativeVectorAlignment(), LLVMTypes::Int32Type, lCopyMetadata(), lGetMask(), lIsUndef(), LLVMGetName(), LLVMInt32(), LLVMInt64(), m, matchesMaskInstruction(), matchingBlendInstruction(), Module::module, IntrinsicsOpt::BlendInstruction::op0, IntrinsicsOpt::BlendInstruction::op1, IntrinsicsOpt::BlendInstruction::opFactor, Globals::opt, and Globals::target.
Member Data Documentation
std::vector<BlendInstruction> IntrinsicsOpt::blendInstructions private
Definition at line 732 of file opt.cpp.
Referenced by IntrinsicsOpt(), and matchingBlendInstruction().
char IntrinsicsOpt::ID = 0 static
Definition at line 703 of file opt.cpp.
std::vector<MaskInstruction> IntrinsicsOpt::maskInstructions private
Definition at line 710 of file opt.cpp.
Referenced by IntrinsicsOpt(), and matchesMaskInstruction().
The documentation for this class was generated from the following file:
opt.cpp