Intel SPMD Program Compiler: LabeledStmt Class Reference
LabeledStmt Class Reference
#include <stmt.h>
Public Member Functions
LabeledStmt (const char *label, Stmt *stmt, SourcePos p)
void EmitCode (FunctionEmitContext *ctx) const
void Print (int indent) const
Stmt * Optimize ()
Stmt * TypeCheck ()
int EstimateCost () const
Public Member Functions inherited from Stmt
Stmt (SourcePos p)
Public Member Functions inherited from ASTNode
ASTNode (SourcePos p)
virtual ~ASTNode ()
Public Attributes
std::string name
Stmt * stmt
Detailed Description
Statement corresponding to a label (as would be used as a goto target) in the program.
Definition at line 392 of file stmt.h.
Constructor & Destructor Documentation
LabeledStmt::LabeledStmt (const char * label, Stmt * stmt, SourcePos p)
Definition at line 3145 of file stmt.cpp.
References name, s, and stmt.
Member Function Documentation
void LabeledStmt::EmitCode (FunctionEmitContext * ctx) const virtual
Emit LLVM IR for the statement, using the FunctionEmitContext to create the necessary instructions.
Implements Stmt.
Definition at line 3153 of file stmt.cpp.
References AssertPos, FunctionEmitContext::BranchInst(), Stmt::EmitCode(), FunctionEmitContext::GetCurrentBasicBlock(), FunctionEmitContext::GetLabeledBasicBlock(), name, ASTNode::pos, FunctionEmitContext::SetCurrentBasicBlock(), and stmt.
int LabeledStmt::EstimateCost () const virtual
Estimate the execution cost of the node (not including the cost of the children. The value returned should be based on the COST_* enumerant values defined in ispc.h.
Implements ASTNode.
Definition at line 3202 of file stmt.cpp.
Stmt * LabeledStmt::Optimize () virtual
The Optimize() method should perform any appropriate early-stage optimizations on the node (e.g. constant folding). This method will be called after the node's children have already been optimized, and the caller will store the returned ASTNode * in place of the original node. This method should return NULL if an error is encountered during optimization.
Reimplemented from Stmt.
Definition at line 3180 of file stmt.cpp.
void LabeledStmt::Print (int indent) const virtual
Print a representation of the statement (and any children AST nodes) to standard output. This method is used for debuggins.
Implements Stmt.
Definition at line 3172 of file stmt.cpp.
References name, Stmt::Print(), and stmt.
Stmt * LabeledStmt::TypeCheck () virtual
Type checking should be performed by the node when this method is called. In the event of an error, a NULL value may be returned. As with ASTNode::Optimize(), the caller should store the returned pointer in place of the original ASTNode *.
Implements Stmt.
Definition at line 3186 of file stmt.cpp.
References Error(), name, and ASTNode::pos.
Member Data Documentation
std::string LabeledStmt::name
Name of the label.
Definition at line 404 of file stmt.h.
Referenced by EmitCode(), FunctionEmitContext::initLabelBBlocks(), LabeledStmt(), Print(), and TypeCheck().
Stmt* LabeledStmt::stmt
Statements following the label.
Definition at line 406 of file stmt.h.
Referenced by EmitCode(), LabeledStmt(), Print(), and WalkAST().
The documentation for this class was generated from the following files:
stmt.h
stmt.cpp