Intel SPMD Program Compiler: VSelMovmskOpt Class Reference
VSelMovmskOpt Class Reference
Public Member Functions
VSelMovmskOpt ()
const char * getPassName () const
bool runOnBasicBlock (llvm::BasicBlock &BB)
Static Public Attributes
static char ID = 0
Detailed Description
This simple optimization pass looks for a vector select instruction with an all-on or all-off constant mask, simplifying it to the appropriate operand if so.
Todo:
The better thing to do would be to submit a patch to LLVM to get these; they're presumably pretty simple patterns to match.
Definition at line 923 of file opt.cpp.
Constructor & Destructor Documentation
VSelMovmskOpt::VSelMovmskOpt () inline
Definition at line 925 of file opt.cpp.
Member Function Documentation
const char* VSelMovmskOpt::getPassName () const inline
Definition at line 928 of file opt.cpp.
bool VSelMovmskOpt::runOnBasicBlock (llvm::BasicBlock & BB)
Definition at line 938 of file opt.cpp.
References ALL_OFF, ALL_ON, DEBUG_END_PASS, DEBUG_START_PASS, lGetMask(), lGetMaskStatus(), LLVMInt64(), m, and Module::module.
Member Data Documentation
char VSelMovmskOpt::ID = 0 static
Definition at line 931 of file opt.cpp.
The documentation for this class was generated from the following file:
opt.cpp