Intel® Implicit SPMD Program Compiler (Intel® ISPC): PeepholePass Class Reference
PeepholePass Class Reference
Public Member Functions
PeepholePass ()
llvm::StringRef getPassName () const
bool runOnBasicBlock (llvm::BasicBlock &BB)
bool runOnFunction (llvm::Function &F)
Static Public Attributes
static char ID = 0
Detailed Description
Definition at line 4470 of file opt.cpp.
Constructor & Destructor Documentation
PeepholePass()
PeepholePass::PeepholePass ()
Definition at line 4483 of file opt.cpp.
Referenced by CreatePeepholePass().
Member Function Documentation
getPassName()
llvm::StringRef PeepholePass::getPassName () const inline
Definition at line 4474 of file opt.cpp.
runOnBasicBlock()
bool PeepholePass::runOnBasicBlock (llvm::BasicBlock & BB)
Definition at line 4722 of file opt.cpp.
References DEBUG_END_PASS, DEBUG_START_PASS, lMatchAvgDownInt16(), lMatchAvgDownInt8(), lMatchAvgDownUInt16(), lMatchAvgDownUInt8(), lMatchAvgUpInt16(), lMatchAvgUpInt8(), lMatchAvgUpUInt16(), and lMatchAvgUpUInt8().
Referenced by ReplaceStdlibShiftPass::getPassName(), runOnFunction(), and ReplaceStdlibShiftPass::runOnFunction().
runOnFunction()
bool PeepholePass::runOnFunction (llvm::Function & F)
Definition at line 4757 of file opt.cpp.
References runOnBasicBlock().
Referenced by ReplaceStdlibShiftPass::getPassName(), and FixBooleanSelectPass::getPassName().
Member Data Documentation
ID
char PeepholePass::ID = 0 static
Definition at line 4478 of file opt.cpp.
The documentation for this class was generated from the following file:
opt.cpp