Intel SPMD Program Compiler: SmearCleanupPass Class Reference
SmearCleanupPass Class Reference
Public Member Functions
SmearCleanupPass (llvm::Module *m, int width)
const char * getPassName () const
bool runOnBasicBlock (llvm::BasicBlock &BB)
Public Attributes
llvm::Module * module
unsigned int vectorWidth
Static Public Attributes
static char ID = 0
Private Member Functions
unsigned int ChainLength (llvm::InsertElementInst *inst) const
llvm::Value * getInsertChainSmearValue (llvm::Instruction *inst) const
llvm::Value * getShuffleSmearValue (llvm::Instruction *inst) const
Detailed Description
Definition at line 4450 of file cbackend.cpp.
Constructor & Destructor Documentation
SmearCleanupPass::SmearCleanupPass (llvm::Module * m, int width) inline
Definition at line 4452 of file cbackend.cpp.
References m, module, and vectorWidth.
Member Function Documentation
unsigned int SmearCleanupPass::ChainLength (llvm::InsertElementInst * inst) const private
Definition at line 4473 of file cbackend.cpp.
Referenced by getInsertChainSmearValue().
llvm::Value * SmearCleanupPass::getInsertChainSmearValue (llvm::Instruction * inst) const private
Definition at line 4484 of file cbackend.cpp.
References ChainLength(), and vectorWidth.
Referenced by runOnBasicBlock().
const char* SmearCleanupPass::getPassName () const inline
Definition at line 4455 of file cbackend.cpp.
llvm::Value * SmearCleanupPass::getShuffleSmearValue (llvm::Instruction * inst) const private
Definition at line 4532 of file cbackend.cpp.
References vectorWidth.
Referenced by runOnBasicBlock().
bool SmearCleanupPass::runOnBasicBlock (llvm::BasicBlock & BB)
Definition at line 4568 of file cbackend.cpp.
References getInsertChainSmearValue(), getShuffleSmearValue(), lGetTypedFunc(), LLVMGetName(), module, and vectorWidth.
Member Data Documentation
char SmearCleanupPass::ID = 0 static
Definition at line 4458 of file cbackend.cpp.
llvm::Module* SmearCleanupPass::module
Definition at line 4459 of file cbackend.cpp.
Referenced by runOnBasicBlock(), and SmearCleanupPass().
unsigned int SmearCleanupPass::vectorWidth
Definition at line 4460 of file cbackend.cpp.
Referenced by getInsertChainSmearValue(), getShuffleSmearValue(), runOnBasicBlock(), and SmearCleanupPass().
The documentation for this class was generated from the following file:
cbackend.cpp