Intel SPMD Program Compiler: InstructionSimplifyPass Class Reference
InstructionSimplifyPass Class Reference
Public Member Functions
InstructionSimplifyPass ()
const char * getPassName () const
bool runOnBasicBlock (llvm::BasicBlock &BB)
Static Public Attributes
static char ID = 0
Static Private Member Functions
static bool simplifySelect (llvm::SelectInst *selectInst, llvm::BasicBlock::iterator iter)
static llvm::Value * simplifyBoolVec (llvm::Value *value)
static bool simplifyCall (llvm::CallInst *callInst, llvm::BasicBlock::iterator iter)
Detailed Description
This simple optimization pass looks for a vector select instruction with an all-on or all-off constant mask, simplifying it to the appropriate operand if so.
Todo:
The better thing to do would be to submit a patch to LLVM to get these; they're presumably pretty simple patterns to match.
Definition at line 1162 of file opt.cpp.
Constructor & Destructor Documentation
InstructionSimplifyPass::InstructionSimplifyPass () inline
Definition at line 1164 of file opt.cpp.
Member Function Documentation
const char* InstructionSimplifyPass::getPassName () const inline
Definition at line 1167 of file opt.cpp.
bool InstructionSimplifyPass::runOnBasicBlock (llvm::BasicBlock & BB)
Definition at line 1281 of file opt.cpp.
References DEBUG_END_PASS, DEBUG_START_PASS, simplifyCall(), and simplifySelect().
llvm::Value * InstructionSimplifyPass::simplifyBoolVec (llvm::Value * value) static private
Definition at line 1184 of file opt.cpp.
References LLVMTypes::Int1VectorType.
Referenced by simplifySelect().
bool InstructionSimplifyPass::simplifyCall (llvm::CallInst * callInst, llvm::BasicBlock::iterator iter) static private
Definition at line 1261 of file opt.cpp.
References lGetMask(), LLVMInt64(), m, and Module::module.
Referenced by runOnBasicBlock().
bool InstructionSimplifyPass::simplifySelect (llvm::SelectInst * selectInst, llvm::BasicBlock::iterator iter) static private
Definition at line 1220 of file opt.cpp.
References ALL_OFF, ALL_ON, lGetMaskStatus(), and simplifyBoolVec().
Referenced by runOnBasicBlock().
Member Data Documentation
char InstructionSimplifyPass::ID = 0 static
Definition at line 1170 of file opt.cpp.
The documentation for this class was generated from the following file:
opt.cpp