Intel SPMD Program Compiler: SwitchStmt Class Reference
SwitchStmt Class Reference
#include <stmt.h>
Public Member Functions
SwitchStmt (Expr *expr, Stmt *stmts, SourcePos pos)
void EmitCode (FunctionEmitContext *ctx) const
void Print (int indent) const
Stmt * TypeCheck ()
int EstimateCost () const
Public Member Functions inherited from Stmt
Stmt (SourcePos p)
virtual Stmt * Optimize ()
Public Member Functions inherited from ASTNode
ASTNode (SourcePos p)
virtual ~ASTNode ()
Public Attributes
Expr * expr
Stmt * stmts
Detailed Description
A "switch" statement in the program.
Definition at line 355 of file stmt.h.
Constructor & Destructor Documentation
SwitchStmt::SwitchStmt (Expr * expr, Stmt * stmts, SourcePos pos)
Definition at line 2434 of file stmt.cpp.
References expr, s, and stmts.
Member Function Documentation
void SwitchStmt::EmitCode (FunctionEmitContext * ctx) const virtual
Emit LLVM IR for the statement, using the FunctionEmitContext to create the necessary instructions.
Implements Stmt.
Definition at line 2530 of file stmt.cpp.
References AssertPos, FunctionEmitContext::BranchInst(), SwitchVisitInfo::caseBlocks, FunctionEmitContext::CreateBasicBlock(), SwitchVisitInfo::defaultBlock, Stmt::EmitCode(), FunctionEmitContext::EndSwitch(), Module::errorCount, expr, FunctionEmitContext::GetCurrentBasicBlock(), FunctionEmitContext::GetFullMask(), Expr::GetType(), Expr::GetValue(), Type::IsUniformType(), SwitchVisitInfo::lastBlock, lHasVaryingBreakOrContinue(), lSwitchASTPreVisit(), m, SwitchVisitInfo::nextBlock, ASTNode::pos, FunctionEmitContext::SetBlockEntryMask(), FunctionEmitContext::SetCurrentBasicBlock(), FunctionEmitContext::StartSwitch(), stmts, FunctionEmitContext::SwitchInst(), and WalkAST().
int SwitchStmt::EstimateCost () const virtual
Estimate the execution cost of the node (not including the cost of the children. The value returned should be based on the COST_* enumerant values defined in ispc.h.
Implements ASTNode.
Definition at line 2622 of file stmt.cpp.
References COST_UNIFORM_SWITCH, COST_VARYING_SWITCH, expr, Expr::GetType(), and Type::IsVaryingType().
void SwitchStmt::Print (int indent) const virtual
Print a representation of the statement (and any children AST nodes) to standard output. This method is used for debuggins.
Implements Stmt.
Definition at line 2577 of file stmt.cpp.
References expr, ASTNode::pos, Stmt::Print(), Expr::Print(), SourcePos::Print(), and stmts.
Stmt * SwitchStmt::TypeCheck () virtual
Type checking should be performed by the node when this method is called. In the event of an error, a NULL value may be returned. As with ASTNode::Optimize(), the caller should store the returned pointer in place of the original ASTNode *.
Implements Stmt.
Definition at line 2589 of file stmt.cpp.
References Assert, Type::EqualIgnoringConst(), Module::errorCount, expr, Type::GetAsConstType(), Type::GetAsUniformType(), Expr::GetType(), Type::IsUniformType(), m, TypeConvertExpr(), AtomicType::UniformInt32, AtomicType::UniformInt64, AtomicType::UniformUInt64, AtomicType::VaryingInt32, and AtomicType::VaryingInt64.
Member Data Documentation
Expr* SwitchStmt::expr
Expression that is used to determine which label to jump to.
Definition at line 366 of file stmt.h.
Referenced by EmitCode(), EstimateCost(), Print(), SwitchStmt(), TypeCheck(), and WalkAST().
Stmt* SwitchStmt::stmts
Statement block after the "switch" expression.
Definition at line 368 of file stmt.h.
Referenced by EmitCode(), Print(), SwitchStmt(), and WalkAST().
The documentation for this class was generated from the following files:
stmt.h
stmt.cpp