Intel SPMD Program Compiler: SOAArrayType Class Reference
SOAArrayType Class Reference
"Structure of arrays" array type.
#include <type.h>
Public Member Functions
SOAArrayType (const StructType *elementType, int numElements, int soaWidth)
const SOAArrayType * GetAsVaryingType () const
const SOAArrayType * GetAsUniformType () const
const Type * GetSOAType (int width) const
const SOAArrayType * GetAsConstType () const
const SOAArrayType * GetAsNonConstType () const
std::string GetString () const
std::string Mangle () const
std::string GetCDeclaration (const std::string &name) const
int TotalElementCount () const
const llvm::ArrayType * LLVMType (llvm::LLVMContext *ctx) const
llvm::DIType GetDIType (llvm::DIDescriptor scope) const
SOAArrayType * GetSizedArray (int size) const
Private Member Functions
const ArrayType * soaType () const
Private Attributes
const int soaWidth
Detailed Description
"Structure of arrays" array type.
This type represents an array with elements of a structure type, "SOA-ized" to some width w. This corresponds to replicating the struct element types w times and then having an array of size/w of these widened structs. This memory layout often makes it possible to access data with regular vector loads, rather than gathers that are needed with "AOS" (array of structures) layout.
Todo:
Native support for SOA stuff is still a work in progres...
Definition at line 359 of file type.h.
Constructor & Destructor Documentation
SOAArrayType::SOAArrayType (const StructType * elementType, int numElements, int soaWidth)
SOAType constructor.
Parameters:
elementType Type of the array elements. Must be a StructType.
numElements Total number of elements in the array. This parameter may be zero, in which case this is an "unsized" array type. (Arrays of specific size can be converted to unsized arrays to be passed to functions that take array parameters, for example).
soaWidth If non-zero, this gives the SOA width to use in laying out the array data in memory. (This value must be a power of two). For example, if the array's element type is: struct { uniform float x, y, z; }, the SOA width is four, and the number of elements is 12, then the array will be laid out in memory as xxxxyyyyzzzzxxxxyyyyzzzzxxxxyyyyzzzz.
Definition at line 640 of file type.cpp.
References assert, ArrayType::numElements, and soaWidth.
Referenced by GetAsConstType(), GetAsNonConstType(), GetAsUniformType(), GetAsVaryingType(), GetSizedArray(), and GetSOAType().
Member Function Documentation
const SOAArrayType * SOAArrayType::GetAsConstType () const [virtual]
Get a const version of this type. If it's already const, then the old Type pointer is returned.
Reimplemented from ArrayType.
Definition at line 672 of file type.cpp.
References ArrayType::child, Type::GetAsConstType(), ArrayType::numElements, SOAArrayType(), and soaWidth.
const SOAArrayType * SOAArrayType::GetAsNonConstType () const [virtual]
Get a non-const version of this type. If it's already not const, then the old Type pointer is returned.
Reimplemented from ArrayType.
Definition at line 679 of file type.cpp.
References ArrayType::child, Type::GetAsNonConstType(), ArrayType::numElements, SOAArrayType(), and soaWidth.
const SOAArrayType * SOAArrayType::GetAsUniformType () const [virtual]
Return a "uniform" instance of this type. If the type is already uniform, its "this" pointer will be returned.
Reimplemented from ArrayType.
Definition at line 658 of file type.cpp.
References ArrayType::child, Type::GetAsUniformType(), ArrayType::numElements, SOAArrayType(), and soaWidth.
const SOAArrayType * SOAArrayType::GetAsVaryingType () const [virtual]
Return a "varying" instance of this type. If the type is already uniform, its "this" pointer will be returned.
Reimplemented from ArrayType.
Definition at line 651 of file type.cpp.
References ArrayType::child, Type::GetAsVaryingType(), ArrayType::numElements, SOAArrayType(), and soaWidth.
std::string SOAArrayType::GetCDeclaration (const std::string & name) const [virtual]
Returns a string that is the declaration of the same type in C syntax.
Reimplemented from ArrayType.
Definition at line 716 of file type.cpp.
References Type::GetCDeclaration(), and soaType().
llvm::DIType SOAArrayType::GetDIType (llvm::DIDescriptor scope) const [virtual]
Returns the DIType (LLVM's debugging information structure), corresponding to this type.
Reimplemented from ArrayType.
Definition at line 746 of file type.cpp.
References ArrayType::child, FATAL, Type::GetDIType(), and soaType().
SOAArrayType * SOAArrayType::GetSizedArray (int length) const [virtual]
Returns a new array of the same child type, but with the given length.
Reimplemented from ArrayType.
Definition at line 761 of file type.cpp.
References ArrayType::child, NULL, SOAArrayType(), and soaWidth.
const Type * SOAArrayType::GetSOAType (int width) const [virtual]
Return a new type representing the current type laid out in width-wide SOA (structure of arrays) format.
Reimplemented from ArrayType.
Definition at line 665 of file type.cpp.
References ArrayType::child, Type::GetSOAType(), ArrayType::numElements, SOAArrayType(), and soaWidth.
std::string SOAArrayType::GetString () const [virtual]
Returns a text representation of the type (for example, for use in warning and error messages).
Reimplemented from ArrayType.
Definition at line 686 of file type.cpp.
References ArrayType::child, ArrayType::GetBaseType(), Type::GetString(), ArrayType::numElements, s, and soaWidth.
const llvm::ArrayType * SOAArrayType::LLVMType (llvm::LLVMContext * ctx) const [virtual]
Returns the LLVM type corresponding to this ispc type
Reimplemented from ArrayType.
Definition at line 734 of file type.cpp.
References ArrayType::child, ArrayType::LLVMType(), NULL, and soaType().
std::string SOAArrayType::Mangle () const [virtual]
Returns a string that represents the mangled type (for use in mangling function symbol names for function overloading). The various Types implementations of this method should collectively ensure that all of them use mangling schemes that are guaranteed not to clash.
Reimplemented from ArrayType.
Definition at line 709 of file type.cpp.
References Type::Mangle(), and soaType().
const ArrayType * SOAArrayType::soaType () const [private]
Returns a regular ArrayType with the struct type's elements widened out and with correspondingly fewer array elements.
Definition at line 769 of file type.cpp.
References ArrayType::ArrayType(), ArrayType::child, Type::GetSOAType(), ArrayType::numElements, and soaWidth.
Referenced by GetCDeclaration(), GetDIType(), LLVMType(), and Mangle().
int SOAArrayType::TotalElementCount () const
This method returns the total number of elements in the array, including all dimensions if this is a multidimensional array.
Reimplemented from ArrayType.
Definition at line 723 of file type.cpp.
References ArrayType::child, ArrayType::numElements, soaWidth, and ArrayType::TotalElementCount().
Member Data Documentation
const int SOAArrayType::soaWidth [private]
This member variable records the rate at which the structure elements are replicated.
Definition at line 403 of file type.h.
Referenced by GetAsConstType(), GetAsNonConstType(), GetAsUniformType(), GetAsVaryingType(), GetSizedArray(), GetSOAType(), GetString(), SOAArrayType(), soaType(), and TotalElementCount().
The documentation for this class was generated from the following files:
type.h
type.cpp