Intel SPMD Program Compiler: IndexExpr Class Reference
IndexExpr Class Reference
Expression representing indexing into something with an integer offset.
#include <expr.h>
Public Member Functions
IndexExpr (Expr *baseExpr, Expr *index, SourcePos p)
llvm::Value * GetValue (FunctionEmitContext *ctx) const
llvm::Value * GetLValue (FunctionEmitContext *ctx) const
const Type * GetType () const
const Type * GetLValueType () const
Symbol * GetBaseSymbol () const
void Print () const
Expr * Optimize ()
Expr * TypeCheck ()
int EstimateCost () const
Public Member Functions inherited from Expr
Expr (SourcePos p, unsigned scid)
virtual llvm::Constant * GetConstant (const Type *type) const
Public Member Functions inherited from ASTNode
ASTNode (SourcePos p, unsigned scid)
virtual ~ASTNode ()
unsigned getValueID () const
Static Public Member Functions
static bool classof (IndexExpr const *)
static bool classof (ASTNode const *N)
Static Public Member Functions inherited from Expr
static bool classof (Expr const *)
static bool classof (ASTNode const *N)
Static Public Member Functions inherited from ASTNode
static bool classof (ASTNode const *)
Public Attributes
Expr * baseExpr
Expr * index
Public Attributes inherited from ASTNode
SourcePos pos
Private Attributes
const Type * type
const PointerType * lvalueType
Additional Inherited Members
Public Types inherited from ASTNode
enum ASTNodeTy {
AddressOfExprID, AssignExprID, BinaryExprID, ConstExprID,
DerefExprID, PtrDerefExprID, RefDerefExprID, ExprListID,
FunctionCallExprID, FunctionSymbolExprID, IndexExprID, StructMemberExprID,
VectorMemberExprID, NewExprID, NullPointerExprID, ReferenceExprID,
SelectExprID, SizeOfExprID, SymbolExprID, SyncExprID,
TypeCastExprID, UnaryExprID, MaxExprID, AssertStmtID,
BreakStmtID, CaseStmtID, ContinueStmtID, DeclStmtID,
DefaultStmtID, DeleteStmtID, DoStmtID, ExprStmtID,
ForeachActiveStmtID, ForeachStmtID, ForeachUniqueStmtID, ForStmtID,
GotoStmtID, IfStmtID, LabeledStmtID, PrintStmtID,
ReturnStmtID, StmtListID, SwitchStmtID, UnmaskedStmtID
}
Detailed Description
Expression representing indexing into something with an integer offset.
This is used for both array indexing and indexing into VectorTypes.
Definition at line 287 of file expr.h.
Constructor & Destructor Documentation
IndexExpr()
IndexExpr::IndexExpr (Expr * baseExpr, Expr * index, SourcePos p)
Definition at line 3835 of file expr.cpp.
References baseExpr, index, lvalueType, and type.
Member Function Documentation
classof() [1/2]
static bool IndexExpr::classof (IndexExpr const *) inline static
Definition at line 291 of file expr.h.
classof() [2/2]
static bool IndexExpr::classof (ASTNode const * N) inline static
Definition at line 292 of file expr.h.
References ASTNode::EstimateCost(), Expr::GetBaseSymbol(), Expr::GetLValue(), Expr::GetLValueType(), Expr::GetType(), Expr::GetValue(), ASTNode::getValueID(), ASTNode::IndexExprID, Expr::Optimize(), Expr::Print(), and Expr::TypeCheck().
EstimateCost()
int IndexExpr::EstimateCost () const virtual
Estimate the execution cost of the node (not including the cost of the children. The value returned should be based on the COST_* enumerant values defined in ispc.h.
Implements ASTNode.
Definition at line 4309 of file expr.cpp.
References baseExpr, COST_GATHER, COST_LOAD, Expr::GetType(), index, and Type::IsVaryingType().
GetBaseSymbol()
Symbol * IndexExpr::GetBaseSymbol () const virtual
For expressions that have values based on a symbol (e.g. regular symbol references, array indexing, etc.), this returns a pointer to that symbol.
Reimplemented from Expr.
Definition at line 4048 of file expr.cpp.
References baseExpr, and Expr::GetBaseSymbol().
Referenced by GetValue().
GetLValue()
llvm::Value * IndexExpr::GetLValue (FunctionEmitContext * ctx) const virtual
For expressions that can provide an lvalue (e.g. array indexing), this function should emit IR that computes the expression's lvalue and returns the corresponding llvm::Value. Expressions that can't provide an lvalue should leave this unimplemented; the default implementation returns NULL.
Reimplemented from Expr.
Definition at line 4116 of file expr.cpp.
References AssertPos, baseExpr, Module::errorCount, FunctionEmitContext::GetElementPtrInst(), Expr::GetLValue(), Expr::GetLValueType(), GetLValueType(), Type::GetReferenceTarget(), Expr::GetType(), PointerType::GetUniform(), Expr::GetValue(), index, lAddVaryingOffsetsIfNeeded(), lCheckIndicesVersusBounds(), lConvertPtrToSliceIfNeeded(), LLVMGetName(), LLVMInt32(), m, and FunctionEmitContext::SetDebugPos().
Referenced by GetValue().
GetLValueType()
const Type * IndexExpr::GetLValueType () const virtual
Returns the type of the value returned by GetLValueType(); this should be a pointer type of some sort (uniform or varying).
Reimplemented from Expr.
Definition at line 4180 of file expr.cpp.
References AssertPos, baseExpr, PointerType::GetAsSlice(), Type::GetBaseType(), PointerType::GetBaseType(), SequentialType::GetElementType(), Expr::GetLValueType(), Type::GetReferenceTarget(), Expr::GetType(), PointerType::GetUniform(), PointerType::GetVarying(), index, Type::IsSOAType(), Type::IsUniformType(), Type::IsVaryingType(), and lvalueType.
Referenced by StructMemberExpr::classof(), GetLValue(), and GetValue().
GetType()
const Type * IndexExpr::GetType () const virtual
Returns the Type of the expression.
Implements Expr.
Definition at line 4005 of file expr.cpp.
References AssertPos, baseExpr, Type::GetAsUniformType(), Type::GetAsVaryingType(), PointerType::GetBaseType(), SequentialType::GetElementType(), Type::GetReferenceTarget(), Expr::GetType(), index, Type::IsSOAType(), Type::IsUniformType(), and type.
Referenced by StructMemberExpr::classof(), GetValue(), and Print().
GetValue()
llvm::Value * IndexExpr::GetValue (FunctionEmitContext * ctx) const virtual
This is the main method for Expr implementations to implement. It should call methods in the FunctionEmitContext to emit LLVM IR instructions to the current basic block in order to generate an llvm::Value that represents the expression's value.
Implements Expr.
Definition at line 3946 of file expr.cpp.
References FunctionEmitContext::AllocaInst(), Assert, AssertPos, baseExpr, Globals::ctx, Module::errorCount, g, GetBaseSymbol(), FunctionEmitContext::GetElementPtrInst(), SequentialType::GetElementType(), GetLValue(), GetLValueType(), Expr::GetType(), GetType(), PointerType::GetUniform(), Expr::GetValue(), index, Type::IsVaryingType(), lAddVaryingOffsetsIfNeeded(), LLVMInt32(), LLVMMaskAllOn, Type::LLVMType(), lMaskForSymbol(), FunctionEmitContext::LoadInst(), lVaryingStructHasUniformMember(), m, FunctionEmitContext::SetDebugPos(), and FunctionEmitContext::StoreInst().
Optimize()
Expr * IndexExpr::Optimize () virtual
This method should perform early optimizations of the expression (constant folding, etc.) and return a pointer to the resulting expression. If an error is encountered during optimization, NULL should be returned.
Implements Expr.
Definition at line 4238 of file expr.cpp.
References baseExpr, and index.
Print()
void IndexExpr::Print () const virtual
Prints the expression to standard output (used for debugging).
Implements Expr.
Definition at line 4325 of file expr.cpp.
References baseExpr, GetType(), index, Expr::Print(), and SourcePos::Print().
TypeCheck()
Expr * IndexExpr::TypeCheck () virtual
This method should perform type checking of the expression and return a pointer to the resulting expression. If an error is encountered, NULL should be returned.
Implements Expr.
Definition at line 4244 of file expr.cpp.
References AssertPos, baseExpr, Opt::disableUniformMemoryOptimizations, Type::EqualIgnoringConst(), Error(), Module::errorCount, Opt::force32BitAddressing, g, Type::GetAsUniformType(), Type::GetReferenceTarget(), Type::GetString(), Expr::GetType(), index, Target::is32Bit(), Type::IsUniformType(), m, Globals::opt, Globals::target, TypeConvertExpr(), AtomicType::UniformInt32, AtomicType::UniformInt64, AtomicType::UniformUInt64, and AtomicType::VaryingInt32.
Member Data Documentation
baseExpr
Expr* IndexExpr::baseExpr
Definition at line 305 of file expr.h.
Referenced by EstimateCost(), GetBaseSymbol(), GetLValue(), GetLValueType(), GetType(), GetValue(), IndexExpr(), lCheckAllOffSafety(), Optimize(), Print(), TypeCheck(), and WalkAST().
index
Expr * IndexExpr::index
Definition at line 305 of file expr.h.
Referenced by EstimateCost(), GetLValue(), GetLValueType(), GetType(), GetValue(), IndexExpr(), lCheckAllOffSafety(), lCheckIndicesVersusBounds(), Optimize(), Print(), TypeCheck(), and WalkAST().
lvalueType
const PointerType* IndexExpr::lvalueType mutable private
Definition at line 309 of file expr.h.
Referenced by GetLValueType(), and IndexExpr().
type
const Type* IndexExpr::type mutable private
Definition at line 308 of file expr.h.
Referenced by GetType(), IndexExpr(), and lVaryingStructHasUniformMember().
The documentation for this class was generated from the following files:
expr.h
expr.cpp