Intel SPMD Program Compiler: DereferenceExpr Class Reference
DereferenceExpr Class Reference
Expression that represents dereferencing a reference to get its value.
#include <expr.h>
Public Member Functions
DereferenceExpr (Expr *e, SourcePos p)
llvm::Value * GetValue (FunctionEmitContext *ctx) const
llvm::Value * GetLValue (FunctionEmitContext *ctx) const
const Type * GetType () const
const Type * GetLValueType () const
Symbol * GetBaseSymbol () const
void Print () const
Expr * TypeCheck ()
Expr * Optimize ()
int EstimateCost () const
Public Attributes
Expr * expr
Detailed Description
Expression that represents dereferencing a reference to get its value.
Definition at line 535 of file expr.h.
Constructor & Destructor Documentation
DereferenceExpr::DereferenceExpr (Expr * e, SourcePos p)
Definition at line 5779 of file expr.cpp.
References expr.
Member Function Documentation
int DereferenceExpr::EstimateCost () const
Definition at line 5867 of file expr.cpp.
References COST_DEREF, COST_GATHER, expr, Expr::GetType(), Type::IsVaryingType(), and NULL.
Symbol * DereferenceExpr::GetBaseSymbol () const [virtual]
For expressions that have values based on a symbol (e.g. regular symbol references, array indexing, etc.), this returns a pointer to that symbol.
Reimplemented from Expr.
Definition at line 5822 of file expr.cpp.
References expr, Expr::GetBaseSymbol(), and NULL.
llvm::Value * DereferenceExpr::GetLValue (FunctionEmitContext * ctx) const [virtual]
For expressions that can provide an lvalue (e.g. array indexing), this function should emit IR that computes the expression's lvalue and returns the corresponding llvm::Value. Expressions that can't provide an lvalue should leave this unimplemented; the default implementation returns NULL.
Reimplemented from Expr.
Definition at line 5806 of file expr.cpp.
References expr, Expr::GetValue(), and NULL.
const Type * DereferenceExpr::GetLValueType () const [virtual]
Returns the type of the value returned by GetLValueType(); this should be a pointer type of some sort (uniform or varying).
Reimplemented from Expr.
Definition at line 5814 of file expr.cpp.
References expr, Expr::GetType(), and NULL.
const Type * DereferenceExpr::GetType () const [virtual]
Returns the Type of the expression.
Implements Expr.
Definition at line 5828 of file expr.cpp.
References Assert, expr, Type::GetAsVaryingType(), Type::GetBaseType(), Type::GetReferenceTarget(), Expr::GetType(), Type::IsUniformType(), and NULL.
Referenced by Print().
llvm::Value * DereferenceExpr::GetValue (FunctionEmitContext * ctx) const [virtual]
This is the main method for Expr implementations to implement. It should call methods in the FunctionEmitContext to emit LLVM IR instructions to the current basic block in order to generate an llvm::Value that represents the expression's value.
Implements Expr.
Definition at line 5786 of file expr.cpp.
References expr, Expr::GetBaseSymbol(), FunctionEmitContext::GetFullMask(), Expr::GetType(), Expr::GetValue(), lMaskForSymbol(), FunctionEmitContext::LoadInst(), NULL, and FunctionEmitContext::SetDebugPos().
Expr * DereferenceExpr::Optimize () [virtual]
This method should perform early optimizations of the expression (constant folding, etc.) and return a pointer to the resulting expression. If an error is encountered during optimization, NULL should be returned.
Implements Expr.
Definition at line 5857 of file expr.cpp.
References expr, NULL, and Expr::Optimize().
void DereferenceExpr::Print () const [virtual]
Prints the expression to standard output (used for debugging).
Implements Expr.
Definition at line 5883 of file expr.cpp.
References expr, GetType(), NULL, Expr::Print(), and SourcePos::Print().
Expr * DereferenceExpr::TypeCheck () [virtual]
This method should perform type checking of the expression and return a pointer to the resulting expression. If an error is encountered, NULL should be returned.
Implements Expr.
Definition at line 5847 of file expr.cpp.
References expr, NULL, and Expr::TypeCheck().
Member Data Documentation
Expr* DereferenceExpr::expr
Definition at line 549 of file expr.h.
Referenced by DereferenceExpr(), EstimateCost(), GetBaseSymbol(), GetLValue(), GetLValueType(), GetType(), GetValue(), lSafeToRunWithAllLanesOff(), Optimize(), Print(), and TypeCheck().
The documentation for this class was generated from the following files:
expr.h
expr.cpp