Intel® Implicit SPMD Program Compiler (Intel® ISPC): ArgErrors Class Reference
ArgErrors Class Reference
Public Member Functions
ArgErrors ()
void AddError (const char *format,...) PRINTF_FUNC
void AddWarning (const char *format,...) PRINTF_FUNC
void Emit ()
Private Types
enum MsgType { MsgType::warning, MsgType::error }
Private Member Functions
void AddMessage (MsgType msg_type, const char *format, va_list args)
Private Attributes
std::vector< std::pair< MsgType, std::string > > m_messages
Detailed Description
Definition at line 370 of file main.cpp.
Member Enumeration Documentation
MsgType
enum ArgErrors::MsgType strong private
Enumerator
warning
error
Definition at line 371 of file main.cpp.
Constructor & Destructor Documentation
ArgErrors()
ArgErrors::ArgErrors () inline
Definition at line 386 of file main.cpp.
Member Function Documentation
AddError()
void ArgErrors::AddError (const char * format, ...) inline
Definition at line 387 of file main.cpp.
Referenced by main(), ParsingPhaseName(), and ParsingPhases().
AddMessage()
void ArgErrors::AddMessage (MsgType msg_type, const char * format, va_list args) inline private
Definition at line 373 of file main.cpp.
AddWarning()
void ArgErrors::AddWarning (const char * format, ...) inline
Definition at line 393 of file main.cpp.
Referenced by main().
Emit()
void ArgErrors::Emit () inline
Definition at line 399 of file main.cpp.
References Error(), g, Warning(), and Globals::warningsAsErrors.
Member Data Documentation
m_messages
std::vector<std::pair<MsgType, std::string> > ArgErrors::m_messages private
Definition at line 372 of file main.cpp.
The documentation for this class was generated from the following file:
main.cpp