Intel® Implicit SPMD Program Compiler (Intel® ISPC): GatherCoalescePass Class Reference
GatherCoalescePass Class Reference
Public Member Functions
GatherCoalescePass ()
llvm::StringRef getPassName () const
bool runOnBasicBlock (llvm::BasicBlock &BB)
bool runOnFunction (llvm::Function &F)
Static Public Attributes
static char ID = 0
Detailed Description
Definition at line 2830 of file opt.cpp.
Constructor & Destructor Documentation
GatherCoalescePass()
GatherCoalescePass::GatherCoalescePass () inline
Definition at line 2833 of file opt.cpp.
Member Function Documentation
getPassName()
llvm::StringRef GatherCoalescePass::getPassName () const inline
Definition at line 2835 of file opt.cpp.
References ID.
runOnBasicBlock()
bool GatherCoalescePass::runOnBasicBlock (llvm::BasicBlock & BB)
Definition at line 3654 of file opt.cpp.
References ALL_ON, Debug(), DEBUG_END_PASS, DEBUG_START_PASS, Globals::debugPrint, g, lCoalesceGathers(), lGetMaskStatus(), lGetSourcePosFromMetadata(), lInstructionMayWriteToMemory(), LLVMDumpValue(), LLVMVectorValuesAllEqual(), m, and Module::module.
runOnFunction()
bool GatherCoalescePass::runOnFunction (llvm::Function & F)
Definition at line 3796 of file opt.cpp.
Member Data Documentation
ID
char GatherCoalescePass::ID = 0 static
Definition at line 2832 of file opt.cpp.
Referenced by getPassName().
The documentation for this class was generated from the following file:
opt.cpp