Intel SPMD Program Compiler: MemberExpr Class Reference
MemberExpr Class Reference
Expression representing member selection ("foo.bar").
#include <expr.h>
Public Member Functions
llvm::Value * GetValue (FunctionEmitContext *ctx) const
llvm::Value * GetLValue (FunctionEmitContext *ctx) const
const Type * GetType () const
Symbol * GetBaseSymbol () const
void Print () const
Expr * Optimize ()
Expr * TypeCheck ()
int EstimateCost () const
virtual int getElementNumber () const =0
virtual const Type * getElementType () const =0
std::string getCandidateNearMatches () const
MemberExpr (Expr *expr, const char *identifier, SourcePos pos, SourcePos identifierPos, bool derefLValue)
Public Member Functions inherited from Expr
Expr (SourcePos p)
virtual const Type * GetLValueType () const
virtual llvm::Constant * GetConstant (const Type *type) const
Public Member Functions inherited from ASTNode
ASTNode (SourcePos p)
virtual ~ASTNode ()
Static Public Member Functions
static MemberExpr * create (Expr *expr, const char *identifier, SourcePos pos, SourcePos identifierPos, bool derefLvalue)
Public Attributes
Expr * expr
std::string identifier
const SourcePos identifierPos
bool dereferenceExpr
Protected Attributes
const Type * type
const Type * lvalueType
Detailed Description
Expression representing member selection ("foo.bar").
This will also be overloaded to deal with swizzles.
Definition at line 302 of file expr.h.
Constructor & Destructor Documentation
MemberExpr::MemberExpr (Expr * expr, const char * identifier, SourcePos pos, SourcePos identifierPos, bool derefLValue)
Definition at line 5167 of file expr.cpp.
References dereferenceExpr, expr, identifier, lvalueType, and type.
Member Function Documentation
MemberExpr * MemberExpr::create (Expr * expr, const char * identifier, SourcePos pos, SourcePos identifierPos, bool derefLvalue) static
Definition at line 5097 of file expr.cpp.
References Assert, Error(), PointerType::GetBaseType(), Type::GetReferenceTarget(), Type::GetString(), Expr::GetType(), StructType::IsDefined(), ASTNode::pos, and TypeCheck().
int MemberExpr::EstimateCost () const virtual
Estimate the execution cost of the node (not including the cost of the children. The value returned should be based on the COST_* enumerant values defined in ispc.h.
Implements ASTNode.
Definition at line 5290 of file expr.cpp.
References COST_GATHER, COST_SIMPLE_ARITH_LOGIC_OP, Expr::GetLValueType(), Type::IsVaryingType(), and lvalueType.
Symbol * MemberExpr::GetBaseSymbol () const virtual
For expressions that have values based on a symbol (e.g. regular symbol references, array indexing, etc.), this returns a pointer to that symbol.
Reimplemented from Expr.
Definition at line 5233 of file expr.cpp.
References expr, and Expr::GetBaseSymbol().
Referenced by GetValue().
std::string MemberExpr::getCandidateNearMatches () const
There is no structure member with the name we've got in "identifier". Use the approximate string matching routine to see if the identifier is a minor misspelling of one of the ones that is there.
Definition at line 5316 of file expr.cpp.
References expr, StructType::GetElementCount(), StructType::GetElementName(), Expr::GetType(), identifier, and MatchStrings().
Referenced by StructMemberExpr::getElementNumber(), and StructMemberExpr::GetType().
int MemberExpr::getElementNumber () const pure virtual
Implemented in VectorMemberExpr, and StructMemberExpr.
Definition at line 5239 of file expr.cpp.
Referenced by GetLValue(), and GetValue().
virtual const Type* MemberExpr::getElementType () const pure virtual
Implemented in VectorMemberExpr, and StructMemberExpr.
llvm::Value * MemberExpr::GetLValue (FunctionEmitContext * ctx) const virtual
For expressions that can provide an lvalue (e.g. array indexing), this function should emit IR that computes the expression's lvalue and returns the corresponding llvm::Value. Expressions that can't provide an lvalue should leave this unimplemented; the default implementation returns NULL.
Reimplemented from Expr.
Reimplemented in VectorMemberExpr.
Definition at line 5245 of file expr.cpp.
References FunctionEmitContext::AddElementOffset(), AssertPos, dereferenceExpr, Module::errorCount, expr, getElementNumber(), Expr::GetLValue(), Expr::GetLValueType(), Expr::GetType(), Expr::GetValue(), lAddVaryingOffsetsIfNeeded(), m, and FunctionEmitContext::SetDebugPos().
Referenced by GetValue().
const Type * MemberExpr::GetType () const virtual
Returns the Type of the expression.
Implements Expr.
Reimplemented in VectorMemberExpr, and StructMemberExpr.
Definition at line 5227 of file expr.cpp.
Referenced by GetValue(), and Print().
llvm::Value * MemberExpr::GetValue (FunctionEmitContext * ctx) const virtual
This is the main method for Expr implementations to implement. It should call methods in the FunctionEmitContext to emit LLVM IR instructions to the current basic block in order to generate an llvm::Value that represents the expression's value.
Implements Expr.
Reimplemented in VectorMemberExpr.
Definition at line 5178 of file expr.cpp.
References FunctionEmitContext::AddElementOffset(), FunctionEmitContext::AllocaInst(), AssertPos, Globals::ctx, Module::errorCount, expr, g, GetBaseSymbol(), getElementNumber(), GetLValue(), Expr::GetLValueType(), Expr::GetType(), GetType(), PointerType::GetUniform(), Expr::GetValue(), identifier, LLVMGetName(), LLVMMaskAllOn, Type::LLVMType(), lMaskForSymbol(), FunctionEmitContext::LoadInst(), lvalueType, m, FunctionEmitContext::SetDebugPos(), and FunctionEmitContext::StoreInst().
Expr * MemberExpr::Optimize () virtual
This method should perform early optimizations of the expression (constant folding, etc.) and return a pointer to the resulting expression. If an error is encountered during optimization, NULL should be returned.
Implements Expr.
Definition at line 5284 of file expr.cpp.
References expr.
void MemberExpr::Print () const virtual
Prints the expression to standard output (used for debugging).
Implements Expr.
Definition at line 5300 of file expr.cpp.
References expr, GetType(), identifier, Expr::Print(), and SourcePos::Print().
Expr * MemberExpr::TypeCheck () virtual
This method should perform type checking of the expression and return a pointer to the resulting expression. If an error is encountered, NULL should be returned.
Implements Expr.
Definition at line 5278 of file expr.cpp.
References expr.
Referenced by create().
Member Data Documentation
bool MemberExpr::dereferenceExpr
Indicates whether the expression should be dereferenced before the member is found. (i.e. this is true if the MemberExpr was a '->' operator, and is false if it was a '.' operator.
Definition at line 330 of file expr.h.
Referenced by GetLValue(), StructMemberExpr::GetLValueType(), VectorMemberExpr::GetLValueType(), StructMemberExpr::getStructType(), VectorMemberExpr::GetValue(), lCheckAllOffSafety(), and MemberExpr().
Expr* MemberExpr::expr
Definition at line 320 of file expr.h.
Referenced by GetBaseSymbol(), getCandidateNearMatches(), GetLValue(), StructMemberExpr::GetLValueType(), VectorMemberExpr::GetLValueType(), StructMemberExpr::getStructType(), StructMemberExpr::GetType(), GetValue(), VectorMemberExpr::GetValue(), MemberExpr(), Optimize(), Print(), TypeCheck(), and WalkAST().
std::string MemberExpr::identifier
Definition at line 321 of file expr.h.
Referenced by getCandidateNearMatches(), StructMemberExpr::getElementNumber(), VectorMemberExpr::getElementNumber(), StructMemberExpr::getElementType(), VectorMemberExpr::GetLValue(), VectorMemberExpr::GetLValueType(), StructMemberExpr::GetType(), VectorMemberExpr::GetType(), GetValue(), VectorMemberExpr::GetValue(), MemberExpr(), Print(), and VectorMemberExpr::VectorMemberExpr().
const SourcePos MemberExpr::identifierPos
Definition at line 322 of file expr.h.
Referenced by StructMemberExpr::getElementNumber(), and StructMemberExpr::GetType().
const Type * MemberExpr::lvalueType mutable protected
Definition at line 333 of file expr.h.
Referenced by EstimateCost(), StructMemberExpr::GetLValueType(), VectorMemberExpr::GetLValueType(), StructMemberExpr::GetType(), GetValue(), and MemberExpr().
const Type* MemberExpr::type mutable protected
Definition at line 333 of file expr.h.
Referenced by StructMemberExpr::getStructType(), StructMemberExpr::GetType(), VectorMemberExpr::GetType(), and MemberExpr().
The documentation for this class was generated from the following files:
expr.h
expr.cpp