Intel SPMD Program Compiler: EnumType Class Reference
EnumType Class Reference
Type implementation for enumerated types.
#include <type.h>
Public Member Functions
EnumType (SourcePos pos)
EnumType (const char *name, SourcePos pos)
Variability GetVariability () const
bool IsBoolType () const
bool IsFloatType () const
bool IsIntType () const
bool IsUnsignedType () const
bool IsConstType () const
const EnumType * GetBaseType () const
const EnumType * GetAsVaryingType () const
const EnumType * GetAsUniformType () const
const EnumType * GetAsUnboundVariabilityType () const
const EnumType * GetAsSOAType (int width) const
const EnumType * ResolveUnboundVariability (Variability v) const
const EnumType * GetAsConstType () const
const EnumType * GetAsNonConstType () const
std::string GetString () const
std::string Mangle () const
std::string GetCDeclaration (const std::string &name) const
const std::string & GetEnumName () const
llvm::Type * LLVMType (llvm::LLVMContext *ctx) const
llvm::DIType GetDIType (llvm::DIDescriptor scope) const
void SetEnumerators (const std::vector< Symbol *> &enumerators)
int GetEnumeratorCount () const
const Symbol * GetEnumerator (int i) const
Public Member Functions inherited from Type
bool IsPointerType () const
bool IsArrayType () const
bool IsReferenceType () const
bool IsVoidType () const
bool IsNumericType () const
bool IsUniformType () const
bool IsVaryingType () const
bool IsSOAType () const
int GetSOAWidth () const
bool HasUnboundVariability () const
virtual const Type * GetAsUnsignedType () const
virtual const Type * GetReferenceTarget () const
Public Attributes
const SourcePos pos
Public Attributes inherited from Type
const TypeId typeId
Private Attributes
const std::string name
Variability variability
bool isConst
std::vector< Symbol * > enumerators
Additional Inherited Members
Static Public Member Functions inherited from Type
static bool Equal (const Type *a, const Type *b)
static bool EqualIgnoringConst (const Type *a, const Type *b)
static const Type * MoreGeneralType (const Type *type0, const Type *type1, SourcePos pos, const char *reason, bool forceVarying=false, int vecSize=0)
static bool IsBasicType (const Type *type)
Protected Member Functions inherited from Type
Type (TypeId id)
Detailed Description
Type implementation for enumerated types.
Definition at line 355 of file type.h.
Constructor & Destructor Documentation
EnumType() [1/2]
EnumType::EnumType (SourcePos pos)
Constructor for anonymous enumerated types
Definition at line 644 of file type.cpp.
References isConst, Variability::Unbound, and variability.
Referenced by GetAsConstType(), GetAsNonConstType(), GetAsSOAType(), GetAsUnboundVariabilityType(), GetAsUniformType(), GetAsVaryingType(), and ResolveUnboundVariability().
EnumType() [2/2]
EnumType::EnumType (const char * name, SourcePos pos)
Constructor for named enumerated types
Definition at line 650 of file type.cpp.
References isConst, Variability::Unbound, and variability.
Member Function Documentation
GetAsConstType()
const EnumType * EnumType::GetAsConstType () const virtual
Get a const version of this type. If it's already const, then the old Type pointer is returned.
Implements Type.
Definition at line 719 of file type.cpp.
References EnumType(), and isConst.
GetAsNonConstType()
const EnumType * EnumType::GetAsNonConstType () const virtual
Get a non-const version of this type. If it's already not const, then the old Type pointer is returned.
Implements Type.
Definition at line 729 of file type.cpp.
References EnumType(), and isConst.
GetAsSOAType()
const EnumType * EnumType::GetAsSOAType (int width) const virtual
Implements Type.
Definition at line 709 of file type.cpp.
References EnumType(), Type::GetSOAWidth(), Variability::SOA, and variability.
GetAsUnboundVariabilityType()
const EnumType * EnumType::GetAsUnboundVariabilityType () const virtual
Get an instance of the type with unbound variability.
Implements Type.
Definition at line 699 of file type.cpp.
References EnumType(), Type::HasUnboundVariability(), Variability::Unbound, and variability.
GetAsUniformType()
const EnumType * EnumType::GetAsUniformType () const virtual
Return a "uniform" instance of this type. If the type is already uniform, its "this" pointer will be returned.
Implements Type.
Definition at line 669 of file type.cpp.
References EnumType(), Type::IsUniformType(), Variability::Uniform, and variability.
GetAsVaryingType()
const EnumType * EnumType::GetAsVaryingType () const virtual
Return a "varying" instance of this type. If the type is already varying, its "this" pointer will be returned.
Implements Type.
Definition at line 689 of file type.cpp.
References EnumType(), Type::IsVaryingType(), variability, and Variability::Varying.
GetBaseType()
const EnumType * EnumType::GetBaseType () const virtual
Returns the basic root type of the given type. For example, for an array or short-vector, this returns the element type. For a struct or atomic type, it returns itself.
Implements Type.
Definition at line 667 of file type.cpp.
GetCDeclaration()
std::string EnumType::GetCDeclaration (const std::string & name) const virtual
Returns a string that is the declaration of the same type in C syntax.
Implements Type.
Definition at line 763 of file type.cpp.
References Assert, Module::errorCount, g, Target::getVectorWidth(), isConst, lShouldPrintName(), m, name, Variability::SOA, Variability::soaWidth, Globals::target, Variability::Unbound, variability, and Variability::Varying.
GetDIType()
llvm::DIType EnumType::GetDIType (llvm::DIDescriptor scope) const virtual
Returns the DIType (LLVM's debugging information structure), corresponding to this type.
Implements Type.
Definition at line 810 of file type.cpp.
References Assert, Module::diBuilder, enumerators, FATAL, SourcePos::first_line, g, SourcePos::GetDIFile(), AtomicType::GetDIType(), Target::getVectorWidth(), lCreateDIArray(), m, name, pos, Variability::SOA, Variability::soaWidth, Globals::target, Variability::type, Variability::Uniform, AtomicType::UniformInt32, variability, and Variability::Varying.
GetEnumerator()
const Symbol * EnumType::GetEnumerator (int i) const
Returns the symbol for the given enumerator number.
Definition at line 887 of file type.cpp.
References enumerators.
GetEnumeratorCount()
int EnumType::GetEnumeratorCount () const
Returns the total number of enuemrators in this enum type.
Definition at line 885 of file type.cpp.
References enumerators.
GetEnumName()
const std::string& EnumType::GetEnumName () const inline
Returns the name of the enum type. (e.g. struct Foo -> "Foo".)
Definition at line 385 of file type.h.
References name.
GetString()
std::string EnumType::GetString () const virtual
Returns a text representation of the type (for example, for use in warning and error messages).
Implements Type.
Definition at line 739 of file type.cpp.
References Variability::GetString(), isConst, name, and variability.
GetVariability()
Variability EnumType::GetVariability () const virtual
Returns the variability of the type.
Implements Type.
Definition at line 655 of file type.cpp.
References variability.
Referenced by lCheckTypeEquality().
IsBoolType()
bool EnumType::IsBoolType () const virtual
Returns true if the underlying type is boolean. In other words, this is true for individual bools and for short-vectors with underlying bool type, but not for arrays of bools.
Implements Type.
Definition at line 657 of file type.cpp.
IsConstType()
bool EnumType::IsConstType () const virtual
Returns true if this type is 'const'-qualified.
Implements Type.
Definition at line 665 of file type.cpp.
References isConst.
IsFloatType()
bool EnumType::IsFloatType () const virtual
Returns true if the underlying type is float or double. In other words, this is true for individual floats/doubles and for short-vectors of them, but not for arrays of them.
Implements Type.
Definition at line 659 of file type.cpp.
IsIntType()
bool EnumType::IsIntType () const virtual
Returns true if the underlying type is an integer type. In other words, this is true for individual integers and for short-vectors of integer types, but not for arrays of integer types.
Implements Type.
Definition at line 661 of file type.cpp.
IsUnsignedType()
bool EnumType::IsUnsignedType () const virtual
Returns true if the underlying type is unsigned. In other words, this is true for unsigned integers and short vectors of unsigned integer types.
Implements Type.
Definition at line 663 of file type.cpp.
LLVMType()
llvm::Type * EnumType::LLVMType (llvm::LLVMContext * ctx) const virtual
Returns the LLVM type corresponding to this ispc type
Implements Type.
Definition at line 791 of file type.cpp.
References Assert, FATAL, LLVMTypes::Int32Type, LLVMTypes::Int32VectorType, ArrayType::LLVMType(), Variability::SOA, Variability::soaWidth, Variability::type, Variability::Unbound, Variability::Uniform, AtomicType::UniformInt32, variability, and Variability::Varying.
Mangle()
std::string EnumType::Mangle () const virtual
Returns a string that represents the mangled type (for use in mangling function symbol names for function overloading). The various Types implementations of this method should collectively ensure that all of them use mangling schemes that are guaranteed not to clash.
Implements Type.
Definition at line 751 of file type.cpp.
References Assert, isConst, Variability::MangleString(), name, Variability::Unbound, and variability.
ResolveUnboundVariability()
const EnumType * EnumType::ResolveUnboundVariability (Variability v) const virtual
Implements Type.
Definition at line 679 of file type.cpp.
References EnumType(), Variability::Unbound, and variability.
SetEnumerators()
void EnumType::SetEnumerators (const std::vector< Symbol *> & enumerators)
Provides the enumerators defined in the enum definition.
Definition at line 883 of file type.cpp.
References enumerators.
Member Data Documentation
enumerators
std::vector<Symbol *> EnumType::enumerators private
Definition at line 407 of file type.h.
Referenced by GetDIType(), GetEnumerator(), GetEnumeratorCount(), and SetEnumerators().
isConst
bool EnumType::isConst private
Definition at line 406 of file type.h.
Referenced by EnumType(), GetAsConstType(), GetAsNonConstType(), GetCDeclaration(), GetString(), IsConstType(), and Mangle().
name
const std::string EnumType::name private
Definition at line 404 of file type.h.
Referenced by GetCDeclaration(), GetDIType(), GetEnumName(), GetString(), and Mangle().
pos
const SourcePos EnumType::pos
Definition at line 401 of file type.h.
Referenced by GetDIType(), and lCheckTypeEquality().
variability
Variability EnumType::variability private
Definition at line 405 of file type.h.
Referenced by EnumType(), GetAsSOAType(), GetAsUnboundVariabilityType(), GetAsUniformType(), GetAsVaryingType(), GetCDeclaration(), GetDIType(), GetString(), GetVariability(), LLVMType(), Mangle(), and ResolveUnboundVariability().
The documentation for this class was generated from the following files:
type.h
type.cpp