Intel SPMD Program Compiler: StmtList Class Reference
StmtList Class Reference
Representation of a list of statements in the program.
#include <stmt.h>
Public Member Functions
StmtList (SourcePos p)
void EmitCode (FunctionEmitContext *ctx) const
void Print (int indent) const
Stmt * Optimize ()
Stmt * TypeCheck ()
void Add (Stmt *s)
const std::vector< Stmt * > & GetStatements ()
Private Attributes
std::vector< Stmt * > stmts
Detailed Description
Representation of a list of statements in the program.
Definition at line 256 of file stmt.h.
Constructor & Destructor Documentation
StmtList::StmtList (SourcePos p) [inline]
Definition at line 258 of file stmt.h.
Member Function Documentation
void StmtList::Add (Stmt * s) [inline]
Definition at line 266 of file stmt.h.
References stmts.
void StmtList::EmitCode (FunctionEmitContext * ctx) const [virtual]
Emit LLVM IR for the statement, using the FunctionEmitContext to create the necessary instructions.
Implements Stmt.
Definition at line 1306 of file stmt.cpp.
References FunctionEmitContext::EndScope(), FunctionEmitContext::GetCurrentBasicBlock(), ASTNode::pos, FunctionEmitContext::SetDebugPos(), FunctionEmitContext::StartScope(), and stmts.
const std::vector<Stmt *>& StmtList::GetStatements () [inline]
Definition at line 267 of file stmt.h.
References stmts.
Referenced by Module::AddFunction(), and lHasVaryingBreakOrContinue().
Stmt * StmtList::Optimize () [virtual]
The Optimize() method should perform any appropriate early-stage optimizations on the node (e.g. constant folding). The caller should use the returned ASTNode * in place of the original node. This method may return NULL if an error is encountered during optimization.
Implements Stmt.
Definition at line 1320 of file stmt.cpp.
References stmts.
void StmtList::Print (int indent) const [virtual]
Print a representation of the statement (and any children AST nodes) to standard output. This method is used for debuggins.
Implements Stmt.
Definition at line 1338 of file stmt.cpp.
References ASTNode::pos, SourcePos::Print(), and stmts.
Stmt * StmtList::TypeCheck () [virtual]
Type checking should be performed by the node when this method is called. In the event of an error, a NULL value may be returned. As with ASTNode::Optimize(), the caller should store the returned pointer in place of the original ASTNode *.
Implements Stmt.
Definition at line 1329 of file stmt.cpp.
References stmts.
Member Data Documentation
std::vector<Stmt *> StmtList::stmts [private]
Definition at line 270 of file stmt.h.
Referenced by Add(), EmitCode(), GetStatements(), Optimize(), Print(), and TypeCheck().
The documentation for this class was generated from the following files:
stmt.h
stmt.cpp