Intel® Implicit SPMD Program Compiler (Intel® ISPC): DebugPassFile Class Reference
DebugPassFile Class Reference
Public Member Functions
DebugPassFile (int number, llvm::StringRef name)
llvm::StringRef getPassName () const
bool runOnModule (llvm::Module &m)
bool doInitialization (llvm::Module &m)
Static Public Attributes
static char ID = 0
Private Member Functions
void run (llvm::Module &m, bool init)
Private Attributes
int pnum
llvm::StringRef pname
Detailed Description
This pass is added in list of passes after optimizations which we want to debug and print dump of LLVM IR to file.
Definition at line 4244 of file opt.cpp.
Constructor & Destructor Documentation
DebugPassFile()
DebugPassFile::DebugPassFile (int number, llvm::StringRef name) inline
Definition at line 4247 of file opt.cpp.
Member Function Documentation
doInitialization()
bool DebugPassFile::doInitialization (llvm::Module & m)
Definition at line 4285 of file opt.cpp.
References DebugPassManager::run().
getPassName()
llvm::StringRef DebugPassFile::getPassName () const inline
Definition at line 4249 of file opt.cpp.
References m, and DebugPassManager::run().
run()
void DebugPassFile::run (llvm::Module & m, bool init) private
Definition at line 4271 of file opt.cpp.
References Assert, and sanitize().
runOnModule()
bool DebugPassFile::runOnModule (llvm::Module & m)
Definition at line 4280 of file opt.cpp.
References DebugPassManager::run().
Member Data Documentation
ID
char DebugPassFile::ID = 0 static
Definition at line 4246 of file opt.cpp.
pname
llvm::StringRef DebugPassFile::pname private
Definition at line 4256 of file opt.cpp.
pnum
int DebugPassFile::pnum private
Definition at line 4255 of file opt.cpp.
The documentation for this class was generated from the following file:
opt.cpp