Intel SPMD Program Compiler: PseudoMaskedStorePass Class Reference
PseudoMaskedStorePass Class Reference
Public Member Functions
PseudoMaskedStorePass ()
const char * getPassName () const
bool runOnBasicBlock (llvm::BasicBlock &BB)
Static Public Attributes
static char ID = 0
Detailed Description
When the front-end needs to do a masked store, it emits a __pseudo_masked_store* call as a placeholder. This pass lowers these calls to either __masked_store* or __masked_store_blend* calls.
Definition at line 2124 of file opt.cpp.
Constructor & Destructor Documentation
PseudoMaskedStorePass::PseudoMaskedStorePass () [inline]
Definition at line 2127 of file opt.cpp.
Member Function Documentation
const char* PseudoMaskedStorePass::getPassName () const [inline]
Definition at line 2129 of file opt.cpp.
bool PseudoMaskedStorePass::runOnBasicBlock (llvm::BasicBlock & BB)
Definition at line 2193 of file opt.cpp.
References LMSInfo::blendFunc, Opt::disableBlendedMaskedStores, g, lCallInst(), lCopyMetadata(), lIsSafeToBlend(), LMSInfo::maskedStoreFunc, NULL, Globals::opt, and LMSInfo::pseudoFunc.
Member Data Documentation
char PseudoMaskedStorePass::ID = 0 [static]
Definition at line 2126 of file opt.cpp.
The documentation for this class was generated from the following file:
opt.cpp