Intel SPMD Program Compiler: SizeOfExpr Class Reference
SizeOfExpr Class Reference
#include <expr.h>
Public Member Functions
SizeOfExpr (Expr *e, SourcePos p)
SizeOfExpr (const Type *t, SourcePos p)
llvm::Value * GetValue (FunctionEmitContext *ctx) const
const Type * GetType () const
void Print () const
Expr * TypeCheck ()
Expr * Optimize ()
int EstimateCost () const
Public Member Functions inherited from Expr
Expr (SourcePos p)
virtual llvm::Value * GetLValue (FunctionEmitContext *ctx) const
virtual const Type * GetLValueType () const
virtual Symbol * GetBaseSymbol () const
virtual llvm::Constant * GetConstant (const Type *type) const
Public Member Functions inherited from ASTNode
ASTNode (SourcePos p)
virtual ~ASTNode ()
Public Attributes
Expr * expr
const Type * type
Detailed Description
Expression that returns the size of the given expression or type in bytes.
Definition at line 560 of file expr.h.
Constructor & Destructor Documentation
SizeOfExpr::SizeOfExpr (Expr * e, SourcePos p)
Definition at line 7833 of file expr.cpp.
SizeOfExpr::SizeOfExpr (const Type * t, SourcePos p)
Definition at line 7838 of file expr.cpp.
References Type::ResolveUnboundVariability(), type, and Variability::Varying.
Member Function Documentation
int SizeOfExpr::EstimateCost () const virtual
Estimate the execution cost of the node (not including the cost of the children. The value returned should be based on the COST_* enumerant values defined in ispc.h.
Implements ASTNode.
Definition at line 7908 of file expr.cpp.
const Type * SizeOfExpr::GetType () const virtual
Returns the Type of the expression.
Implements Expr.
Definition at line 7860 of file expr.cpp.
References Opt::force32BitAddressing, g, Target::is32Bit(), Globals::opt, Globals::target, AtomicType::UniformUInt32, and AtomicType::UniformUInt64.
llvm::Value * SizeOfExpr::GetValue (FunctionEmitContext * ctx) const virtual
This is the main method for Expr implementations to implement. It should call methods in the FunctionEmitContext to emit LLVM IR instructions to the current basic block in order to generate an llvm::Value that represents the expression's value.
Implements Expr.
Definition at line 7845 of file expr.cpp.
References Globals::ctx, expr, g, FunctionEmitContext::GetCurrentBasicBlock(), Expr::GetType(), Type::LLVMType(), FunctionEmitContext::SetDebugPos(), Target::SizeOf(), Globals::target, and type.
Expr * SizeOfExpr::Optimize () virtual
This method should perform early optimizations of the expression (constant folding, etc.) and return a pointer to the resulting expression. If an error is encountered during optimization, NULL should be returned.
Implements Expr.
Definition at line 7902 of file expr.cpp.
void SizeOfExpr::Print () const virtual
Prints the expression to standard output (used for debugging).
Implements Expr.
Definition at line 7867 of file expr.cpp.
References expr, Type::GetString(), Expr::GetType(), Expr::Print(), SourcePos::Print(), and type.
Expr * SizeOfExpr::TypeCheck () virtual
This method should perform type checking of the expression and return a pointer to the resulting expression. If an error is encountered, NULL should be returned.
Implements Expr.
Definition at line 7880 of file expr.cpp.
References Error(), g, Target::getISA(), Type::GetString(), Type::IsVaryingType(), Globals::target, and type.
Member Data Documentation
Expr* SizeOfExpr::expr
Definition at line 574 of file expr.h.
Referenced by GetValue(), Print(), and WalkAST().
const Type* SizeOfExpr::type
Definition at line 575 of file expr.h.
Referenced by GetValue(), Print(), SizeOfExpr(), and TypeCheck().
The documentation for this class was generated from the following files:
expr.h
expr.cpp