Intel SPMD Program Compiler: ContinueStmt Class Reference
ContinueStmt Class Reference
Statement implementation for a continue statement in the program.
#include <stmt.h>
Public Member Functions
ContinueStmt (SourcePos pos)
void EmitCode (FunctionEmitContext *ctx) const
void Print (int indent) const
Stmt * TypeCheck ()
int EstimateCost () const
Public Member Functions inherited from Stmt
Stmt (SourcePos p)
virtual Stmt * Optimize ()
Public Member Functions inherited from ASTNode
ASTNode (SourcePos p)
virtual ~ASTNode ()
Additional Inherited Members
Public Attributes inherited from ASTNode
SourcePos pos
Detailed Description
Statement implementation for a continue statement in the program.
Definition at line 214 of file stmt.h.
Constructor & Destructor Documentation
ContinueStmt::ContinueStmt (SourcePos pos)
Definition at line 1221 of file stmt.cpp.
Member Function Documentation
void ContinueStmt::EmitCode (FunctionEmitContext * ctx) const virtual
Emit LLVM IR for the statement, using the FunctionEmitContext to create the necessary instructions.
Implements Stmt.
Definition at line 1227 of file stmt.cpp.
References FunctionEmitContext::Continue(), FunctionEmitContext::GetCurrentBasicBlock(), ASTNode::pos, and FunctionEmitContext::SetDebugPos().
int ContinueStmt::EstimateCost () const virtual
Estimate the execution cost of the node (not including the cost of the children. The value returned should be based on the COST_* enumerant values defined in ispc.h.
Implements ASTNode.
Definition at line 1243 of file stmt.cpp.
References COST_BREAK_CONTINUE.
void ContinueStmt::Print (int indent) const virtual
Print a representation of the statement (and any children AST nodes) to standard output. This method is used for debuggins.
Implements Stmt.
Definition at line 1249 of file stmt.cpp.
References ASTNode::pos, and SourcePos::Print().
Stmt * ContinueStmt::TypeCheck () virtual
Type checking should be performed by the node when this method is called. In the event of an error, a NULL value may be returned. As with ASTNode::Optimize(), the caller should store the returned pointer in place of the original ASTNode *.
Implements Stmt.
Definition at line 1237 of file stmt.cpp.
The documentation for this class was generated from the following files:
stmt.h
stmt.cpp