Intel SPMD Program Compiler: BreakStmt Class Reference
BreakStmt Class Reference
Statement implementation for a break or 'coherent' break statement in the program.
#include <stmt.h>
Public Member Functions
BreakStmt (bool doCoherenceCheck, SourcePos pos)
void EmitCode (FunctionEmitContext *ctx) const
void Print (int indent) const
Stmt * Optimize ()
Stmt * TypeCheck ()
Private Attributes
const bool doCoherenceCheck
Detailed Description
Statement implementation for a break or 'coherent' break statement in the program.
Definition at line 192 of file stmt.h.
Constructor & Destructor Documentation
BreakStmt::BreakStmt (bool doCoherenceCheck, SourcePos pos)
Definition at line 1190 of file stmt.cpp.
Member Function Documentation
void BreakStmt::EmitCode (FunctionEmitContext * ctx) const [virtual]
Emit LLVM IR for the statement, using the FunctionEmitContext to create the necessary instructions.
Implements Stmt.
Definition at line 1196 of file stmt.cpp.
References FunctionEmitContext::Break(), doCoherenceCheck, FunctionEmitContext::GetCurrentBasicBlock(), ASTNode::pos, and FunctionEmitContext::SetDebugPos().
Stmt * BreakStmt::Optimize () [virtual]
The Optimize() method should perform any appropriate early-stage optimizations on the node (e.g. constant folding). The caller should use the returned ASTNode * in place of the original node. This method may return NULL if an error is encountered during optimization.
Implements Stmt.
Definition at line 1206 of file stmt.cpp.
void BreakStmt::Print (int indent) const [virtual]
Print a representation of the statement (and any children AST nodes) to standard output. This method is used for debuggins.
Implements Stmt.
Definition at line 1218 of file stmt.cpp.
References doCoherenceCheck, ASTNode::pos, and SourcePos::Print().
Stmt * BreakStmt::TypeCheck () [virtual]
Type checking should be performed by the node when this method is called. In the event of an error, a NULL value may be returned. As with ASTNode::Optimize(), the caller should store the returned pointer in place of the original ASTNode *.
Implements Stmt.
Definition at line 1212 of file stmt.cpp.
Member Data Documentation
const bool BreakStmt::doCoherenceCheck [private]
This indicates whether the generated code will check to see if no more program instances are currently running after the break, in which case the code can have a jump to the end of the current loop.
Definition at line 207 of file stmt.h.
Referenced by EmitCode(), and Print().
The documentation for this class was generated from the following files:
stmt.h
stmt.cpp