Intel SPMD Program Compiler: Function Class Reference
Function Class Reference
#include <func.h>
Public Member Functions
Function (Symbol *sym, Stmt *code)
const Type * GetReturnType () const
const FunctionType * GetType () const
void GenerateIR ()
Private Member Functions
void emitCode (FunctionEmitContext *ctx, llvm::Function *function, SourcePos firstStmtPos)
Private Attributes
Symbol * sym
std::vector< Symbol * > args
Stmt * code
Symbol * maskSymbol
Symbol * threadIndexSym
Symbol * threadCountSym
Symbol * taskIndexSym
Symbol * taskCountSym
Symbol * taskIndexSym0
Symbol * taskCountSym0
Symbol * taskIndexSym1
Symbol * taskCountSym1
Symbol * taskIndexSym2
Symbol * taskCountSym2
Detailed Description
Definition at line 44 of file func.h.
Constructor & Destructor Documentation
Function()
Function::Function (Symbol * sym, Stmt * code)
Definition at line 92 of file func.cpp.
References args, Assert, code, Globals::debugPrint, g, Target::getISA(), FunctionType::GetNumParameters(), FunctionType::GetParameterName(), FunctionType::GetParameterType(), FunctionType::isTask, SymbolTable::LookupVariable(), m, maskSymbol, Symbol::name, Optimize(), Symbol::parentFunction, Stmt::Print(), sym, Module::symbolTable, Globals::target, taskCountSym, taskCountSym0, taskCountSym1, taskCountSym2, taskIndexSym, taskIndexSym0, taskIndexSym1, taskIndexSym2, threadCountSym, threadIndexSym, Symbol::type, and TypeCheck().
Member Function Documentation
emitCode()
void Function::emitCode (FunctionEmitContext * ctx, llvm::Function * function, SourcePos firstStmtPos) private
Given the statements implementing a function, emit the code that implements the function. Most of the work do be done here just involves wiring up the function parameter values to be available in the function body code.
Definition at line 226 of file func.cpp.
References FunctionEmitContext::AddElementOffset(), FunctionEmitContext::AddInstrumentationPoint(), FunctionEmitContext::All(), FunctionEmitContext::AllocaInst(), args, Assert, FunctionEmitContext::BranchInst(), CHECK_MASK_AT_FUNCTION_START_COST, code, FunctionEmitContext::CreateBasicBlock(), Globals::ctx, Debug(), Opt::disableCoherentControlFlow, Opt::disableMaskAllOnOptimizations, Stmt::EmitCode(), FunctionEmitContext::EmitFunctionParameterDebugInfo(), FunctionEmitContext::EmitVariableDebugInfo(), EstimateCost(), g, FunctionEmitContext::GetCurrentBasicBlock(), FunctionEmitContext::GetFullMaskPointer(), FunctionEmitContext::GetFunctionMask(), Target::getISA(), Target::getMaskingIsFree(), FunctionType::GetReturnType(), FunctionType::GetString(), FunctionEmitContext::InitializeLabelMap(), LLVMTypes::Int32Type, FunctionType::isExported, FunctionType::isTask, FunctionType::isUnmasked, Type::IsVoidType(), lCopyInTaskParameter(), LLVMInt32(), LLVMMaskAllOn, FunctionEmitContext::LoadInst(), m, Target::markFuncWithTargetAttr(), maskSymbol, LLVMTypes::MaskType, Module::module, Symbol::name, Globals::NoOmitFramePointer, Globals::opt, Symbol::pos, ASTNode::pos, FunctionEmitContext::ReturnInst(), FunctionEmitContext::SetCurrentBasicBlock(), FunctionEmitContext::SetDebugPos(), FunctionEmitContext::SetFunctionMask(), Symbol::storagePtr, FunctionEmitContext::StoreInst(), sym, Globals::target, taskCountSym, taskCountSym0, taskCountSym1, taskCountSym2, taskIndexSym, taskIndexSym0, taskIndexSym1, taskIndexSym2, threadCountSym, threadIndexSym, Symbol::type, and Warning().
Referenced by GenerateIR().
GenerateIR()
void Function::GenerateIR ()
Generate LLVM IR for the function into the current module.
Definition at line 486 of file func.cpp.
References Assert, code, Globals::ctx, emitCode(), Error(), Module::errorCount, Symbol::exportedFunction, Symbol::function, g, Target::GENERIC, Target::getISA(), Target::GetISAString(), Target::getTreatGenericAsSmth(), FunctionType::isExported, FunctionType::isTask, FunctionType::LLVMFunctionType(), m, Globals::mangleFunctionsWithTarget, Target::markFuncWithTargetAttr(), Module::module, Symbol::name, Symbol::pos, ASTNode::pos, StmtList::stmts, sym, Globals::target, and Symbol::type.
GetReturnType()
const Type * Function::GetReturnType () const
Definition at line 173 of file func.cpp.
References Assert, FunctionType::GetReturnType(), sym, and Symbol::type.
Referenced by ReturnStmt::EmitCode(), and FunctionEmitContext::ReturnInst().
GetType()
const FunctionType * Function::GetType () const
Definition at line 179 of file func.cpp.
References Assert, sym, and Symbol::type.
Member Data Documentation
args
std::vector<Symbol *> Function::args private
Definition at line 58 of file func.h.
Referenced by emitCode(), and Function().
code
Stmt* Function::code private
Definition at line 59 of file func.h.
Referenced by emitCode(), Function(), and GenerateIR().
maskSymbol
Symbol* Function::maskSymbol private
Definition at line 60 of file func.h.
Referenced by emitCode(), and Function().
sym
Symbol* Function::sym private
Definition at line 57 of file func.h.
Referenced by emitCode(), Function(), GenerateIR(), GetReturnType(), and GetType().
taskCountSym
Symbol * Function::taskCountSym private
Definition at line 62 of file func.h.
Referenced by emitCode(), and Function().
taskCountSym0
Symbol * Function::taskCountSym0 private
Definition at line 63 of file func.h.
Referenced by emitCode(), and Function().
taskCountSym1
Symbol * Function::taskCountSym1 private
Definition at line 64 of file func.h.
Referenced by emitCode(), and Function().
taskCountSym2
Symbol * Function::taskCountSym2 private
Definition at line 65 of file func.h.
Referenced by emitCode(), and Function().
taskIndexSym
Symbol* Function::taskIndexSym private
Definition at line 62 of file func.h.
Referenced by emitCode(), and Function().
taskIndexSym0
Symbol* Function::taskIndexSym0 private
Definition at line 63 of file func.h.
Referenced by emitCode(), and Function().
taskIndexSym1
Symbol* Function::taskIndexSym1 private
Definition at line 64 of file func.h.
Referenced by emitCode(), and Function().
taskIndexSym2
Symbol* Function::taskIndexSym2 private
Definition at line 65 of file func.h.
Referenced by emitCode(), and Function().
threadCountSym
Symbol * Function::threadCountSym private
Definition at line 61 of file func.h.
Referenced by emitCode(), and Function().
threadIndexSym
Symbol* Function::threadIndexSym private
Definition at line 61 of file func.h.
Referenced by emitCode(), and Function().
The documentation for this class was generated from the following files:
func.h
func.cpp