Intel® Implicit SPMD Program Compiler (Intel® ISPC): DebugPassManager Class Reference
DebugPassManager Class Reference
Public Member Functions
DebugPassManager ()
void add (llvm::Pass *P, int stage)
bool run (llvm::Module &M)
llvm::legacy::PassManager & getPM ()
Private Attributes
llvm::legacy::PassManager PM
int number
Detailed Description
Definition at line 402 of file opt.cpp.
Constructor & Destructor Documentation
DebugPassManager()
DebugPassManager::DebugPassManager () inline
Definition at line 404 of file opt.cpp.
References add().
Member Function Documentation
add()
void DebugPassManager::add (llvm::Pass * P, int stage = -1)
Definition at line 414 of file opt.cpp.
References CreateDebugPass(), CreateDebugPassFile(), Globals::debug_stages, Globals::dumpFile, g, number, Globals::off_stages, and PM.
Referenced by DebugPassManager(), and Optimize().
getPM()
llvm::legacy::PassManager& DebugPassManager::getPM () inline
Definition at line 407 of file opt.cpp.
References PM.
Referenced by Optimize().
run()
bool DebugPassManager::run (llvm::Module & M) inline
Definition at line 406 of file opt.cpp.
References PM.
Referenced by DebugPassFile::doInitialization(), DebugPassFile::getPassName(), Optimize(), and DebugPassFile::runOnModule().
Member Data Documentation
number
int DebugPassManager::number private
Definition at line 411 of file opt.cpp.
Referenced by add().
PM
llvm::legacy::PassManager DebugPassManager::PM private
Definition at line 410 of file opt.cpp.
Referenced by add(), getPM(), and run().
The documentation for this class was generated from the following file:
opt.cpp