Intel SPMD Program Compiler: NullPointerExpr Class Reference
NullPointerExpr Class Reference
An expression that represents a NULL pointer.
#include <expr.h>
Public Member Functions
NullPointerExpr (SourcePos p)
llvm::Value * GetValue (FunctionEmitContext *ctx) const
const Type * GetType () const
Expr * TypeCheck ()
Expr * Optimize ()
llvm::Constant * GetConstant (const Type *type) const
void Print () const
int EstimateCost () const
Public Member Functions inherited from Expr
Expr (SourcePos p, unsigned scid)
virtual llvm::Value * GetLValue (FunctionEmitContext *ctx) const
virtual const Type * GetLValueType () const
virtual Symbol * GetBaseSymbol () const
Public Member Functions inherited from ASTNode
ASTNode (SourcePos p, unsigned scid)
virtual ~ASTNode ()
unsigned getValueID () const
Static Public Member Functions
static bool classof (NullPointerExpr const *)
static bool classof (ASTNode const *N)
Static Public Member Functions inherited from Expr
static bool classof (Expr const *)
static bool classof (ASTNode const *N)
Static Public Member Functions inherited from ASTNode
static bool classof (ASTNode const *)
Additional Inherited Members
Public Types inherited from ASTNode
enum ASTNodeTy {
AddressOfExprID, AssignExprID, BinaryExprID, ConstExprID,
DerefExprID, PtrDerefExprID, RefDerefExprID, ExprListID,
FunctionCallExprID, FunctionSymbolExprID, IndexExprID, StructMemberExprID,
VectorMemberExprID, NewExprID, NullPointerExprID, ReferenceExprID,
SelectExprID, SizeOfExprID, SymbolExprID, SyncExprID,
TypeCastExprID, UnaryExprID, MaxExprID, AssertStmtID,
BreakStmtID, CaseStmtID, ContinueStmtID, DeclStmtID,
DefaultStmtID, DeleteStmtID, DoStmtID, ExprStmtID,
ForeachActiveStmtID, ForeachStmtID, ForeachUniqueStmtID, ForStmtID,
GotoStmtID, IfStmtID, LabeledStmtID, PrintStmtID,
ReturnStmtID, StmtListID, SwitchStmtID, UnmaskedStmtID
}
Public Attributes inherited from ASTNode
SourcePos pos
Detailed Description
An expression that represents a NULL pointer.
Definition at line 712 of file expr.h.
Constructor & Destructor Documentation
NullPointerExpr()
NullPointerExpr::NullPointerExpr (SourcePos p) inline
Definition at line 714 of file expr.h.
Member Function Documentation
classof() [1/2]
static bool NullPointerExpr::classof (NullPointerExpr const *) inline static
Definition at line 716 of file expr.h.
classof() [2/2]
static bool NullPointerExpr::classof (ASTNode const * N) inline static
Definition at line 717 of file expr.h.
References ASTNode::getValueID(), and ASTNode::NullPointerExprID.
EstimateCost()
int NullPointerExpr::EstimateCost () const virtual
Estimate the execution cost of the node (not including the cost of the children. The value returned should be based on the COST_* enumerant values defined in ispc.h.
Implements ASTNode.
Definition at line 7825 of file expr.cpp.
GetConstant()
llvm::Constant * NullPointerExpr::GetConstant (const Type * type) const virtual
If this is a constant expression that can be converted to a constant of the given type, this method should return the corresponding llvm::Constant value. Otherwise it should return NULL.
Reimplemented from Expr.
Definition at line 7806 of file expr.cpp.
References AssertPos, Globals::ctx, Module::errorCount, g, Type::LLVMType(), m, and ASTNode::pos.
GetType()
const Type * NullPointerExpr::GetType () const virtual
Returns the Type of the expression.
Implements Expr.
Definition at line 7800 of file expr.cpp.
References PointerType::Void.
GetValue()
llvm::Value * NullPointerExpr::GetValue (FunctionEmitContext * ctx) const virtual
This is the main method for Expr implementations to implement. It should call methods in the FunctionEmitContext to emit LLVM IR instructions to the current basic block in order to generate an llvm::Value that represents the expression's value.
Implements Expr.
Definition at line 7796 of file expr.cpp.
References LLVMTypes::VoidPointerType.
Optimize()
Expr * NullPointerExpr::Optimize () virtual
This method should perform early optimizations of the expression (constant folding, etc.) and return a pointer to the resulting expression. If an error is encountered during optimization, NULL should be returned.
Implements Expr.
Definition at line 7804 of file expr.cpp.
Print()
void NullPointerExpr::Print () const virtual
Prints the expression to standard output (used for debugging).
Implements Expr.
Definition at line 7820 of file expr.cpp.
References ASTNode::pos, and SourcePos::Print().
TypeCheck()
Expr * NullPointerExpr::TypeCheck () virtual
This method should perform type checking of the expression and return a pointer to the resulting expression. If an error is encountered, NULL should be returned.
Implements Expr.
Definition at line 7802 of file expr.cpp.
The documentation for this class was generated from the following files:
expr.h
expr.cpp