Intel SPMD Program Compiler: AndCmpCleanupPass Class Reference
AndCmpCleanupPass Class Reference
Public Member Functions
AndCmpCleanupPass ()
const char * getPassName () const
bool runOnBasicBlock (llvm::BasicBlock &BB)
Static Public Attributes
static char ID = 0
Detailed Description
Definition at line 4666 of file cbackend.cpp.
Constructor & Destructor Documentation
AndCmpCleanupPass::AndCmpCleanupPass () inline
Definition at line 4668 of file cbackend.cpp.
Member Function Documentation
const char* AndCmpCleanupPass::getPassName () const inline
Definition at line 4671 of file cbackend.cpp.
bool AndCmpCleanupPass::runOnBasicBlock (llvm::BasicBlock & BB)
Definition at line 4684 of file cbackend.cpp.
References Assert, LLVMGetName(), lPredicateToString(), lTypeToSuffix(), m, LLVMTypes::MaskType, and Module::module.
Member Data Documentation
char AndCmpCleanupPass::ID = 0 static
Definition at line 4674 of file cbackend.cpp.
The documentation for this class was generated from the following file:
cbackend.cpp