Intel SPMD Program Compiler: GSImprovementsPass Class Reference
GSImprovementsPass Class Reference
Public Member Functions
GSImprovementsPass ()
const char * getPassName () const
bool runOnBasicBlock (llvm::BasicBlock &BB)
Static Public Attributes
static char ID = 0
Detailed Description
After earlier optimization passes have run, we are sometimes able to determine that gathers/scatters are actually accessing memory in a more regular fashion and then change the operation to something simpler and more efficient. For example, if all of the lanes in a gather are reading from the same location, we can instead do a scalar load and broadcast. This pass examines gathers and scatters and tries to simplify them if at all possible.
Todo:
Currently, this only looks for all program instances going to the same location and all going to a linear sequence of locations in memory. There are a number of other cases that might make sense to look for, including things that could be handled with a vector load + shuffle or things that could be handled with hybrids of e.g. 2 4-wide vector loads with AVX, etc.
Definition at line 1495 of file opt.cpp.
Constructor & Destructor Documentation
GSImprovementsPass::GSImprovementsPass () [inline]
Definition at line 1498 of file opt.cpp.
Member Function Documentation
const char* GSImprovementsPass::getPassName () const [inline]
Definition at line 1500 of file opt.cpp.
bool GSImprovementsPass::runOnBasicBlock (llvm::BasicBlock & BB)
Definition at line 2119 of file opt.cpp.
References GatherImpInfo::align, ScatterImpInfo::align, assert, Debug(), g, LLVMTypes::Int16VectorPointerType, LLVMTypes::Int32VectorPointerType, LLVMTypes::Int64VectorPointerType, LLVMTypes::Int8VectorPointerType, ISPC_MAX_NVEC, lCopyMetadata(), lGetSourcePosFromMetadata(), LLVM_TYPE_CONST, LLVMInt32(), GatherImpInfo::loadBroadcastFunc, GatherImpInfo::loadMaskedFunc, lScalarizeVector(), lVectorIsLinear(), lVectorValuesAllEqual(), ScatterImpInfo::maskedStoreFunc, NULL, Globals::target, ScatterImpInfo::vecPtrType, Target::vectorWidth, LLVMTypes::VoidPointerType, and Warning().
Member Data Documentation
char GSImprovementsPass::ID = 0 [static]
Definition at line 1497 of file opt.cpp.
The documentation for this class was generated from the following file:
opt.cpp