Intel® Implicit SPMD Program Compiler (Intel® ISPC): BitcodeLib Class Reference
BitcodeLib Class Reference
#include <bitcode_lib.h>
Public Types
enum BitcodeLibType { BitcodeLibType::Dispatch, BitcodeLibType::Builtins_c, BitcodeLibType::ISPC_target }
Public Member Functions
BitcodeLib (const unsigned char lib[], int size, TargetOS os)
BitcodeLib (const unsigned char lib[], int size, TargetOS os, Arch arch)
BitcodeLib (const unsigned char lib[], int size, ISPCTarget target, TargetOS os, Arch arch)
void print () const
BitcodeLibType getType () const
const unsigned char * getLib () const
const size_t getSize () const
const TargetOS getOS () const
const Arch getArch () const
const ISPCTarget getISPCTarget () const
Private Attributes
BitcodeLibType m_type
const unsigned char * m_lib
const size_t m_size
const TargetOS m_os
const Arch m_arch
const ISPCTarget m_target
Detailed Description
Definition at line 42 of file bitcode_lib.h.
Member Enumeration Documentation
BitcodeLibType
enum BitcodeLib::BitcodeLibType strong
Enumerator
Dispatch
Builtins_c
ISPC_target
Definition at line 44 of file bitcode_lib.h.
Constructor & Destructor Documentation
BitcodeLib() [1/3]
BitcodeLib::BitcodeLib (const unsigned char lib[], int size, TargetOS os)
Definition at line 43 of file bitcode_lib.cpp.
References none, and TargetLibRegistry::RegisterTarget().
BitcodeLib() [2/3]
BitcodeLib::BitcodeLib (const unsigned char lib[], int size, TargetOS os, Arch arch)
Definition at line 49 of file bitcode_lib.cpp.
References TargetLibRegistry::RegisterTarget().
BitcodeLib() [3/3]
BitcodeLib::BitcodeLib (const unsigned char lib[], int size, ISPCTarget target, TargetOS os, Arch arch)
Definition at line 54 of file bitcode_lib.cpp.
References TargetLibRegistry::RegisterTarget().
Member Function Documentation
getArch()
const Arch BitcodeLib::getArch () const
Definition at line 90 of file bitcode_lib.cpp.
References m_arch.
getISPCTarget()
const ISPCTarget BitcodeLib::getISPCTarget () const
Definition at line 91 of file bitcode_lib.cpp.
References m_target.
getLib()
const unsigned char * BitcodeLib::getLib () const
Definition at line 87 of file bitcode_lib.cpp.
References m_lib.
Referenced by AddBitcodeToModule().
getOS()
const TargetOS BitcodeLib::getOS () const
Definition at line 89 of file bitcode_lib.cpp.
References m_os.
getSize()
const size_t BitcodeLib::getSize () const
Definition at line 88 of file bitcode_lib.cpp.
References m_size.
Referenced by AddBitcodeToModule().
getType()
BitcodeLib::BitcodeLibType BitcodeLib::getType () const
Definition at line 86 of file bitcode_lib.cpp.
References m_type.
print()
void BitcodeLib::print () const
Definition at line 60 of file bitcode_lib.cpp.
References ArchToString(), Builtins_c, Dispatch, ISPC_target, ISPCTargetToString(), m_arch, m_os, m_size, m_target, m_type, and OSToString().
Member Data Documentation
m_arch
const Arch BitcodeLib::m_arch private
Definition at line 56 of file bitcode_lib.h.
Referenced by getArch(), and print().
m_lib
const unsigned char* BitcodeLib::m_lib private
Definition at line 51 of file bitcode_lib.h.
Referenced by getLib().
m_os
const TargetOS BitcodeLib::m_os private
Definition at line 55 of file bitcode_lib.h.
Referenced by getOS(), and print().
m_size
const size_t BitcodeLib::m_size private
Definition at line 52 of file bitcode_lib.h.
Referenced by getSize(), and print().
m_target
const ISPCTarget BitcodeLib::m_target private
Definition at line 57 of file bitcode_lib.h.
Referenced by getISPCTarget(), and print().
m_type
BitcodeLibType BitcodeLib::m_type private
Definition at line 48 of file bitcode_lib.h.
Referenced by getType(), and print().
The documentation for this class was generated from the following files:
bitcode_lib.h
bitcode_lib.cpp