Intel SPMD Program Compiler: ReferenceMemberExpr Class Reference
ReferenceMemberExpr Class Reference
Public Member Functions
ReferenceMemberExpr (Expr *e, const char *id, SourcePos p, SourcePos idpos, const ReferenceType *referenceType)
const Type * GetType () const
int getElementNumber () const
llvm::Value * GetLValue (FunctionEmitContext *ctx) const
Private Attributes
const ReferenceType * exprReferenceType
MemberExpr * dereferencedExpr
Detailed Description
Definition at line 3018 of file expr.cpp.
Constructor & Destructor Documentation
ReferenceMemberExpr::ReferenceMemberExpr (Expr * e, const char * id, SourcePos p, SourcePos idpos, const ReferenceType * referenceType)
Definition at line 3035 of file expr.cpp.
References dereferencedExpr, exprReferenceType, ReferenceType::GetReferenceTarget(), and NULL.
Member Function Documentation
int ReferenceMemberExpr::getElementNumber () const [virtual]
Reimplemented from MemberExpr.
Definition at line 3066 of file expr.cpp.
References dereferencedExpr, MemberExpr::getElementNumber(), and NULL.
Referenced by GetLValue().
llvm::Value * ReferenceMemberExpr::GetLValue (FunctionEmitContext * ctx) const [virtual]
For expressions that can provide an lvalue (e.g. array indexing), this function should emit IR that computes the expression's lvalue and returns the corresponding llvm::Value. Expressions that can't provide an lvalue should leave this unimplemented; the default implementation returns NULL.
Reimplemented from MemberExpr.
Definition at line 3077 of file expr.cpp.
References dereferencedExpr, Error(), MemberExpr::expr, exprReferenceType, getElementNumber(), FunctionEmitContext::GetElementPtrInst(), ReferenceType::GetString(), Expr::GetValue(), NULL, ASTNode::pos, and FunctionEmitContext::SetDebugPos().
const Type * ReferenceMemberExpr::GetType () const [virtual]
Returns the Type of the expression.
Reimplemented from MemberExpr.
Definition at line 3055 of file expr.cpp.
References dereferencedExpr, Error(), exprReferenceType, ReferenceType::GetString(), MemberExpr::GetType(), NULL, and ASTNode::pos.
Member Data Documentation
MemberExpr* ReferenceMemberExpr::dereferencedExpr [private]
Definition at line 3032 of file expr.cpp.
Referenced by getElementNumber(), GetLValue(), GetType(), and ReferenceMemberExpr().
const ReferenceType* ReferenceMemberExpr::exprReferenceType [private]
Definition at line 3031 of file expr.cpp.
Referenced by GetLValue(), GetType(), and ReferenceMemberExpr().
The documentation for this class was generated from the following file:
expr.cpp