Intel® Implicit SPMD Program Compiler (Intel® ISPC): ForeachActiveStmt Class Reference
ForeachActiveStmt Class Reference
#include <stmt.h>
Public Member Functions
ForeachActiveStmt (Symbol *iterSym, Stmt *stmts, SourcePos pos)
void EmitCode (FunctionEmitContext *ctx) const
void Print (int indent) const
Stmt * TypeCheck ()
int EstimateCost () const
Public Member Functions inherited from Stmt
Stmt (SourcePos p, unsigned scid)
virtual Stmt * Optimize ()
Public Member Functions inherited from ASTNode
ASTNode (SourcePos p, unsigned scid)
virtual ~ASTNode ()
unsigned getValueID () const
Static Public Member Functions
static bool classof (ForeachActiveStmt const *)
static bool classof (ASTNode const *N)
Static Public Member Functions inherited from Stmt
static bool classof (Stmt const *)
static bool classof (ASTNode const *N)
Static Public Member Functions inherited from ASTNode
static bool classof (ASTNode const *)
Public Attributes
Symbol * sym
Stmt * stmts
Public Attributes inherited from ASTNode
SourcePos pos
Additional Inherited Members
Public Types inherited from ASTNode
enum ASTNodeTy {
AddressOfExprID, AssignExprID, BinaryExprID, ConstExprID,
DerefExprID, PtrDerefExprID, RefDerefExprID, ExprListID,
FunctionCallExprID, FunctionSymbolExprID, IndexExprID, StructMemberExprID,
VectorMemberExprID, NewExprID, NullPointerExprID, ReferenceExprID,
SelectExprID, SizeOfExprID, SymbolExprID, SyncExprID,
TypeCastExprID, UnaryExprID, MaxExprID, AssertStmtID,
BreakStmtID, CaseStmtID, ContinueStmtID, DeclStmtID,
DefaultStmtID, DeleteStmtID, DoStmtID, ExprStmtID,
ForeachActiveStmtID, ForeachStmtID, ForeachUniqueStmtID, ForStmtID,
GotoStmtID, IfStmtID, LabeledStmtID, PrintStmtID,
ReturnStmtID, StmtListID, SwitchStmtID, UnmaskedStmtID
}
Detailed Description
Iteration over each executing program instance.
Definition at line 263 of file stmt.h.
Constructor & Destructor Documentation
ForeachActiveStmt()
ForeachActiveStmt::ForeachActiveStmt (Symbol * iterSym, Stmt * stmts, SourcePos pos)
Definition at line 1752 of file stmt.cpp.
References stmts, and sym.
Member Function Documentation
classof() [1/2]
static bool ForeachActiveStmt::classof (ForeachActiveStmt const *) inline static
Definition at line 267 of file stmt.h.
classof() [2/2]
static bool ForeachActiveStmt::classof (ASTNode const * N) inline static
Definition at line 268 of file stmt.h.
References Stmt::EmitCode(), ASTNode::EstimateCost(), ASTNode::ForeachActiveStmtID, ASTNode::getValueID(), Stmt::Print(), and Stmt::TypeCheck().
EmitCode()
void ForeachActiveStmt::EmitCode (FunctionEmitContext * ctx) const virtual
Emit LLVM IR for the statement, using the FunctionEmitContext to create the necessary instructions.
Implements Stmt.
Definition at line 1757 of file stmt.cpp.
References FunctionEmitContext::AllocaInst(), Assert, FunctionEmitContext::BinaryOperator(), FunctionEmitContext::BranchInst(), FunctionEmitContext::CallInst(), FunctionEmitContext::CmpInst(), FunctionEmitContext::CreateBasicBlock(), Stmt::EmitCode(), FunctionEmitContext::EmitVariableDebugInfo(), FunctionEmitContext::EndForeach(), FunctionEmitContext::EndScope(), Type::Equal(), Module::errorCount, FunctionEmitContext::FOREACH_ACTIVE, AtomicType::GetAsConstType(), FunctionEmitContext::GetCurrentBasicBlock(), FunctionEmitContext::GetFullMask(), FunctionEmitContext::GetInternalMask(), FunctionEmitContext::I1VecToBoolVec(), LLVMTypes::Int32Type, LLVMTypes::Int64Type, FunctionEmitContext::LaneMask(), LLVMInt64(), FunctionEmitContext::LoadInst(), m, Module::module, Symbol::name, FunctionEmitContext::NotOperator(), ASTNode::pos, FunctionEmitContext::ProgramIndexVector(), FunctionEmitContext::RestoreContinuedLanes(), FunctionEmitContext::SetBlockEntryMask(), FunctionEmitContext::SetContinueTarget(), FunctionEmitContext::SetCurrentBasicBlock(), FunctionEmitContext::SetDebugPos(), FunctionEmitContext::SetInternalMask(), FunctionEmitContext::SmearUniform(), FunctionEmitContext::StartForeach(), FunctionEmitContext::StartScope(), stmts, Symbol::storagePtr, FunctionEmitContext::StoreInst(), sym, FunctionEmitContext::TruncInst(), Symbol::type, and AtomicType::UniformInt64.
EstimateCost()
int ForeachActiveStmt::EstimateCost () const virtual
Estimate the execution cost of the node (not including the cost of the children. The value returned should be based on the COST_* enumerant values defined in ispc.h.
Implements ASTNode.
Definition at line 1906 of file stmt.cpp.
References COST_VARYING_LOOP.
Print()
void ForeachActiveStmt::Print (int indent) const virtual
Print a representation of the statement (and any children AST nodes) to standard output. This method is used for debuggins.
Implements Stmt.
Definition at line 1877 of file stmt.cpp.
References Type::GetString(), Symbol::name, ASTNode::pos, Stmt::Print(), SourcePos::Print(), stmts, sym, and Symbol::type.
TypeCheck()
Stmt * ForeachActiveStmt::TypeCheck () virtual
Type checking should be performed by the node when this method is called. In the event of an error, a NULL value may be returned. As with ASTNode::Optimize(), the caller should store the returned pointer in place of the original ASTNode *.
Implements Stmt.
Definition at line 1899 of file stmt.cpp.
References sym.
Member Data Documentation
stmts
Stmt* ForeachActiveStmt::stmts
Definition at line 277 of file stmt.h.
Referenced by EmitCode(), ForeachActiveStmt(), Print(), and WalkAST().
sym
Symbol* ForeachActiveStmt::sym
Definition at line 276 of file stmt.h.
Referenced by EmitCode(), ForeachActiveStmt(), Print(), and TypeCheck().
The documentation for this class was generated from the following files:
stmt.h
stmt.cpp