Intel SPMD Program Compiler: CaseStmt Class Reference
CaseStmt Class Reference
#include <stmt.h>
Public Member Functions
CaseStmt (int value, Stmt *stmt, SourcePos pos)
void EmitCode (FunctionEmitContext *ctx) const
void Print (int indent) const
Stmt * TypeCheck ()
int EstimateCost () const
Public Attributes
const int value
Stmt * stmts
Detailed Description
Statement corresponding to a "case" label in the program. In addition to the value associated with the "case", this statement also stores the statements following it.
Definition at line 288 of file stmt.h.
Constructor & Destructor Documentation
CaseStmt::CaseStmt (int value, Stmt * stmt, SourcePos pos)
Definition at line 1890 of file stmt.cpp.
References s, and stmts.
Member Function Documentation
void CaseStmt::EmitCode (FunctionEmitContext * ctx) const [virtual]
Emit LLVM IR for the statement, using the FunctionEmitContext to create the necessary instructions.
Implements Stmt.
Definition at line 1897 of file stmt.cpp.
References FunctionEmitContext::EmitCaseLabel(), Stmt::EmitCode(), lCheckMask(), stmts, and value.
int CaseStmt::EstimateCost () const
Definition at line 1920 of file stmt.cpp.
void CaseStmt::Print (int indent) const [virtual]
Print a representation of the statement (and any children AST nodes) to standard output. This method is used for debuggins.
Implements Stmt.
Definition at line 1905 of file stmt.cpp.
References Stmt::Print(), stmts, and value.
Stmt * CaseStmt::TypeCheck () [virtual]
Implements Stmt.
Definition at line 1914 of file stmt.cpp.
Member Data Documentation
Stmt* CaseStmt::stmts
Definition at line 300 of file stmt.h.
Referenced by CaseStmt(), EmitCode(), and Print().
const int CaseStmt::value
Integer value after the "case" statement
Definition at line 299 of file stmt.h.
Referenced by EmitCode(), lSwitchASTPreVisit(), and Print().
The documentation for this class was generated from the following files:
stmt.h
stmt.cpp