Intel SPMD Program Compiler: ReturnStmt Class Reference
ReturnStmt Class Reference
Statement implementation for a 'return' or 'coherent' return statement in the program.
#include <stmt.h>
Public Member Functions
ReturnStmt (Expr *v, bool cc, SourcePos p)
void EmitCode (FunctionEmitContext *ctx) const
void Print (int indent) const
Stmt * Optimize ()
Stmt * TypeCheck ()
Private Attributes
Expr * val
const bool doCoherenceCheck
Detailed Description
Statement implementation for a 'return' or 'coherent' return statement in the program.
Definition at line 234 of file stmt.h.
Constructor & Destructor Documentation
ReturnStmt::ReturnStmt (Expr * v, bool cc, SourcePos p)
Definition at line 1266 of file stmt.cpp.
Member Function Documentation
void ReturnStmt::EmitCode (FunctionEmitContext * ctx) const [virtual]
Emit LLVM IR for the statement, using the FunctionEmitContext to create the necessary instructions.
Implements Stmt.
Definition at line 1273 of file stmt.cpp.
References FunctionEmitContext::CurrentLanesReturned(), doCoherenceCheck, FunctionEmitContext::GetCurrentBasicBlock(), ASTNode::pos, FunctionEmitContext::SetDebugPos(), and val.
Stmt * ReturnStmt::Optimize () [virtual]
The Optimize() method should perform any appropriate early-stage optimizations on the node (e.g. constant folding). The caller should use the returned ASTNode * in place of the original node. This method may return NULL if an error is encountered during optimization.
Implements Stmt.
Definition at line 1283 of file stmt.cpp.
References Expr::Optimize(), and val.
void ReturnStmt::Print (int indent) const [virtual]
Print a representation of the statement (and any children AST nodes) to standard output. This method is used for debuggins.
Implements Stmt.
Definition at line 1302 of file stmt.cpp.
References doCoherenceCheck, ASTNode::pos, Expr::Print(), SourcePos::Print(), and val.
Stmt * ReturnStmt::TypeCheck () [virtual]
Type checking should be performed by the node when this method is called. In the event of an error, a NULL value may be returned. As with ASTNode::Optimize(), the caller should store the returned pointer in place of the original ASTNode *.
Implements Stmt.
Definition at line 1291 of file stmt.cpp.
References Expr::TypeCheck(), and val.
Member Data Documentation
const bool ReturnStmt::doCoherenceCheck [private]
This indicates whether the generated code will check to see if no more program instances are currently running after the return, in which case the code can possibly jump to the end of the current function.
Definition at line 250 of file stmt.h.
Referenced by EmitCode(), and Print().
Expr* ReturnStmt::val [private]
Definition at line 245 of file stmt.h.
Referenced by EmitCode(), Optimize(), Print(), and TypeCheck().
The documentation for this class was generated from the following files:
stmt.h
stmt.cpp