Intel SPMD Program Compiler: AllCPUs Class Reference
AllCPUs Class Reference
Public Member Functions
AllCPUs ()
std::string HumanReadableListOfNames ()
std::string & GetDefaultNameFromType (CPUtype type)
CPUtype GetTypeFromName (std::string name)
bool BackwardCompatible (CPUtype what, CPUtype with)
Private Member Functions
std::set< CPUtype > Set (CPUtype type,...)
Private Attributes
std::vector< std::vector
< std::string > > names
std::vector< std::set< CPUtype > > compat
Detailed Description
Definition at line 271 of file ispc.cpp.
Constructor & Destructor Documentation
AllCPUs::AllCPUs () inline
Definition at line 290 of file ispc.cpp.
References compat, CPU_Bonnell, CPU_Broadwell, CPU_Core2, CPU_Generic, CPU_Haswell, CPU_IvyBridge, CPU_KNL, CPU_Nehalem, CPU_None, CPU_Penryn, CPU_SandyBridge, CPU_Silvermont, names, Set(), and sizeofCPUtype.
Member Function Documentation
bool AllCPUs::BackwardCompatible (CPUtype what, CPUtype with) inline
Definition at line 430 of file ispc.cpp.
References Assert, compat, CPU_None, and sizeofCPUtype.
Referenced by Target::Target().
std::string& AllCPUs::GetDefaultNameFromType (CPUtype type) inline
Definition at line 414 of file ispc.cpp.
References Assert, CPU_None, names, and sizeofCPUtype.
Referenced by Target::Target().
CPUtype AllCPUs::GetTypeFromName (std::string name) inline
Definition at line 419 of file ispc.cpp.
References CPU_None, names, and sizeofCPUtype.
Referenced by Target::Target().
std::string AllCPUs::HumanReadableListOfNames () inline
Definition at line 398 of file ispc.cpp.
References CPU_Generic, names, and sizeofCPUtype.
Referenced by Target::SupportedCPUs(), and Target::Target().
std::set<CPUtype> AllCPUs::Set (CPUtype type, ...) inline private
Definition at line 276 of file ispc.cpp.
References CPU_None.
Referenced by AllCPUs().
Member Data Documentation
std::vector<std::set<CPUtype> > AllCPUs::compat private
Definition at line 274 of file ispc.cpp.
Referenced by AllCPUs(), and BackwardCompatible().
std::vector<std::vector<std::string> > AllCPUs::names private
Definition at line 273 of file ispc.cpp.
Referenced by AllCPUs(), GetDefaultNameFromType(), GetTypeFromName(), and HumanReadableListOfNames().
The documentation for this class was generated from the following file:
ispc.cpp