Intel® Implicit SPMD Program Compiler (Intel® ISPC): Triple Class Reference
Triple Class Reference
Public Member Functions
Triple (uint32_t encoding)
Triple (ISPCTarget target, TargetOS os, Arch arch)
uint32_t encode () const
Public Attributes
ISPCTarget m_target
TargetOS m_os
Arch m_arch
Static Private Attributes
static constexpr uint32_t target_width = bits_required((uint32_t)ISPCTarget::error)
static constexpr uint32_t os_width = bits_required((uint32_t)TargetOS::error)
static constexpr uint32_t arch_width = bits_required((uint32_t)Arch::error)
static constexpr uint32_t target_mask = (1 << target_width) - 1
static constexpr uint32_t os_mask = ((1 << os_width) - 1) << target_width
static constexpr uint32_t arch_mask = ((1 << arch_width) - 1) << (target_width + os_width)
Detailed Description
Definition at line 55 of file target_registry.cpp.
Constructor & Destructor Documentation
Triple() [1/2]
Triple::Triple (uint32_t encoding) inline
Definition at line 70 of file target_registry.cpp.
References os_width, and target_width.
Referenced by TargetLibRegistry::getBuiltinsCLib(), TargetLibRegistry::getISPCTargetLib(), and TargetLibRegistry::TargetLibRegistry().
Triple() [2/2]
Triple::Triple (ISPCTarget target, TargetOS os, Arch arch) inline
Definition at line 76 of file target_registry.cpp.
Member Function Documentation
encode()
uint32_t Triple::encode () const inline
Definition at line 78 of file target_registry.cpp.
References TargetLibRegistry::libs, m_os, m_target, os_width, and target_width.
Referenced by TargetLibRegistry::getBuiltinsCLib(), TargetLibRegistry::getISPCTargetLib(), and TargetLibRegistry::TargetLibRegistry().
Member Data Documentation
arch_mask
constexpr uint32_t Triple::arch_mask = ((1 << arch_width) - 1) << (target_width + os_width) static private
Definition at line 63 of file target_registry.cpp.
arch_width
constexpr uint32_t Triple::arch_width = bits_required((uint32_t)Arch::error) static private
Definition at line 59 of file target_registry.cpp.
m_arch
Arch Triple::m_arch
Definition at line 68 of file target_registry.cpp.
m_os
TargetOS Triple::m_os
Definition at line 67 of file target_registry.cpp.
Referenced by encode().
m_target
ISPCTarget Triple::m_target
Definition at line 66 of file target_registry.cpp.
Referenced by encode().
os_mask
constexpr uint32_t Triple::os_mask = ((1 << os_width) - 1) << target_width static private
Definition at line 62 of file target_registry.cpp.
os_width
constexpr uint32_t Triple::os_width = bits_required((uint32_t)TargetOS::error) static private
Definition at line 58 of file target_registry.cpp.
Referenced by encode(), and Triple().
target_mask
constexpr uint32_t Triple::target_mask = (1 << target_width) - 1 static private
Definition at line 61 of file target_registry.cpp.
target_width
constexpr uint32_t Triple::target_width = bits_required((uint32_t)ISPCTarget::error) static private
Definition at line 57 of file target_registry.cpp.
Referenced by encode(), and Triple().
The documentation for this class was generated from the following file:
target_registry.cpp