Intel SPMD Program Compiler: AtomicType Class Reference
AtomicType Class Reference
AtomicType represents basic types like floats, ints, etc.
#include <type.h>
Public Types
enum BasicType {
TYPE_VOID, TYPE_BOOL, TYPE_INT8, TYPE_UINT8,
TYPE_INT16, TYPE_UINT16, TYPE_INT32, TYPE_UINT32,
TYPE_FLOAT, TYPE_INT64, TYPE_UINT64, TYPE_DOUBLE
}
Public Member Functions
bool IsUniformType () const
bool IsBoolType () const
bool IsFloatType () const
bool IsIntType () const
bool IsUnsignedType () const
bool IsConstType () const
const AtomicType * GetBaseType () const
const AtomicType * GetAsVaryingType () const
const AtomicType * GetAsUniformType () const
const AtomicType * GetAsUnsignedType () const
const Type * GetSOAType (int width) const
const AtomicType * GetAsConstType () const
const AtomicType * GetAsNonConstType () const
std::string GetString () const
std::string Mangle () const
std::string GetCDeclaration (const std::string &name) const
LLVM_TYPE_CONST llvm::Type * LLVMType (llvm::LLVMContext *ctx) const
llvm::DIType GetDIType (llvm::DIDescriptor scope) const
Public Attributes
const BasicType basicType
static const AtomicType * VaryingBool = new AtomicType(TYPE_BOOL, false, false)
static const AtomicType * VaryingInt8 = new AtomicType(TYPE_INT8, false, false)
static const AtomicType * VaryingInt16 = new AtomicType(TYPE_INT16, false, false)
static const AtomicType * VaryingInt32 = new AtomicType(TYPE_INT32, false, false)
static const AtomicType * VaryingUInt8 = new AtomicType(TYPE_UINT8, false, false)
static const AtomicType * VaryingUInt16 = new AtomicType(TYPE_UINT16, false, false)
static const AtomicType * VaryingUInt32 = new AtomicType(TYPE_UINT32, false, false)
static const AtomicType * VaryingFloat = new AtomicType(TYPE_FLOAT, false, false)
static const AtomicType * VaryingInt64 = new AtomicType(TYPE_INT64, false, false)
static const AtomicType * VaryingUInt64 = new AtomicType(TYPE_UINT64, false, false)
static const AtomicType * VaryingDouble = new AtomicType(TYPE_DOUBLE, false, false)
static const AtomicType * VaryingConstBool = new AtomicType(TYPE_BOOL, false, true)
static const AtomicType * VaryingConstInt8 = new AtomicType(TYPE_INT8, false, true)
static const AtomicType * VaryingConstInt16 = new AtomicType(TYPE_INT16, false, true)
static const AtomicType * VaryingConstInt32 = new AtomicType(TYPE_INT32, false, true)
static const AtomicType * VaryingConstUInt8 = new AtomicType(TYPE_UINT8, false, true)
static const AtomicType * VaryingConstUInt16 = new AtomicType(TYPE_UINT16, false, true)
static const AtomicType * VaryingConstUInt32 = new AtomicType(TYPE_UINT32, false, true)
static const AtomicType * VaryingConstFloat = new AtomicType(TYPE_FLOAT, false, true)
static const AtomicType * VaryingConstInt64 = new AtomicType(TYPE_INT64, false, true)
static const AtomicType * VaryingConstUInt64 = new AtomicType(TYPE_UINT64, false, true)
static const AtomicType * VaryingConstDouble = new AtomicType(TYPE_DOUBLE, false, true)
Static Public Attributes
static const AtomicType * UniformBool = new AtomicType(TYPE_BOOL, true, false)
static const AtomicType * UniformInt8 = new AtomicType(TYPE_INT8, true, false)
static const AtomicType * UniformInt16 = new AtomicType(TYPE_INT16, true, false)
static const AtomicType * UniformInt32 = new AtomicType(TYPE_INT32, true, false)
static const AtomicType * UniformUInt8 = new AtomicType(TYPE_UINT8, true, false)
static const AtomicType * UniformUInt16 = new AtomicType(TYPE_UINT16, true, false)
static const AtomicType * UniformUInt32 = new AtomicType(TYPE_UINT32, true, false)
static const AtomicType * UniformFloat = new AtomicType(TYPE_FLOAT, true, false)
static const AtomicType * UniformInt64 = new AtomicType(TYPE_INT64, true, false)
static const AtomicType * UniformUInt64 = new AtomicType(TYPE_UINT64, true, false)
static const AtomicType * UniformDouble = new AtomicType(TYPE_DOUBLE, true, false)
static const AtomicType * UniformConstBool = new AtomicType(TYPE_BOOL, true, true)
static const AtomicType * UniformConstInt8 = new AtomicType(TYPE_INT8, true, true)
static const AtomicType * UniformConstInt16 = new AtomicType(TYPE_INT16, true, true)
static const AtomicType * UniformConstInt32 = new AtomicType(TYPE_INT32, true, true)
static const AtomicType * UniformConstUInt8 = new AtomicType(TYPE_UINT8, true, true)
static const AtomicType * UniformConstUInt16 = new AtomicType(TYPE_UINT16, true, true)
static const AtomicType * UniformConstUInt32 = new AtomicType(TYPE_UINT32, true, true)
static const AtomicType * UniformConstFloat = new AtomicType(TYPE_FLOAT, true, true)
static const AtomicType * UniformConstInt64 = new AtomicType(TYPE_INT64, true, true)
static const AtomicType * UniformConstUInt64 = new AtomicType(TYPE_UINT64, true, true)
static const AtomicType * UniformConstDouble = new AtomicType(TYPE_DOUBLE, true, true)
static const AtomicType * Void = new AtomicType(TYPE_VOID, true, false)
Private Member Functions
AtomicType (BasicType basicType, bool isUniform, bool isConst)
Private Attributes
const bool isUniform
const bool isConst
Detailed Description
AtomicType represents basic types like floats, ints, etc.
AtomicTypes can be either uniform or varying. Unique instances of all of the possible AtomicTypes are available in the static members like AtomicType::UniformInt32. It is thus possible to compare AtomicTypes for equality with simple pointer equality tests; this is not true for the other Type implementations.
Definition at line 186 of file type.h.
Member Enumeration Documentation
enum AtomicType::BasicType
This enumerator records the basic types that AtomicTypes can be built from.
Enumerator:
TYPE_VOID
TYPE_BOOL
TYPE_INT8
TYPE_UINT8
TYPE_INT16
TYPE_UINT16
TYPE_INT32
TYPE_UINT32
TYPE_FLOAT
TYPE_INT64
TYPE_UINT64
TYPE_DOUBLE
Definition at line 214 of file type.h.
Constructor & Destructor Documentation
AtomicType::AtomicType (BasicType basicType, bool isUniform, bool isConst) [private]
Definition at line 122 of file type.cpp.
Member Function Documentation
const AtomicType * AtomicType::GetAsConstType () const [virtual]
Get a const version of this type. If it's already const, then the old Type pointer is returned.
Implements Type.
Definition at line 193 of file type.cpp.
References basicType, FATAL, isUniform, NULL, TYPE_BOOL, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT16, TYPE_INT32, TYPE_INT64, TYPE_INT8, TYPE_UINT16, TYPE_UINT32, TYPE_UINT64, TYPE_UINT8, UniformConstBool, UniformConstDouble, UniformConstFloat, UniformConstInt16, UniformConstInt32, UniformConstInt64, UniformConstInt8, UniformConstUInt16, UniformConstUInt32, UniformConstUInt64, UniformConstUInt8, VaryingConstBool, VaryingConstDouble, VaryingConstFloat, VaryingConstInt16, VaryingConstInt32, VaryingConstInt64, VaryingConstInt8, VaryingConstUInt16, VaryingConstUInt32, VaryingConstUInt64, and VaryingConstUInt8.
Referenced by VectorType::GetAsConstType().
const AtomicType * AtomicType::GetAsNonConstType () const [virtual]
Get a non-const version of this type. If it's already not const, then the old Type pointer is returned.
Implements Type.
Definition at line 217 of file type.cpp.
References basicType, FATAL, isUniform, NULL, TYPE_BOOL, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT16, TYPE_INT32, TYPE_INT64, TYPE_INT8, TYPE_UINT16, TYPE_UINT32, TYPE_UINT64, TYPE_UINT8, UniformBool, UniformDouble, UniformFloat, UniformInt16, UniformInt32, UniformInt64, UniformInt8, UniformUInt16, UniformUInt32, UniformUInt64, UniformUInt8, VaryingBool, VaryingDouble, VaryingFloat, VaryingInt16, VaryingInt32, VaryingInt64, VaryingInt8, VaryingUInt16, VaryingUInt32, VaryingUInt64, and VaryingUInt8.
Referenced by VectorType::GetAsNonConstType().
const AtomicType * AtomicType::GetAsUniformType () const [virtual]
Return a "uniform" instance of this type. If the type is already uniform, its "this" pointer will be returned.
Implements Type.
Definition at line 271 of file type.cpp.
References basicType, FATAL, isConst, IsUniformType(), NULL, TYPE_BOOL, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT16, TYPE_INT32, TYPE_INT64, TYPE_INT8, TYPE_UINT16, TYPE_UINT32, TYPE_UINT64, TYPE_UINT8, TYPE_VOID, UniformBool, UniformConstBool, UniformConstDouble, UniformConstFloat, UniformConstInt16, UniformConstInt32, UniformConstInt64, UniformConstInt8, UniformConstUInt16, UniformConstUInt32, UniformConstUInt64, UniformConstUInt8, UniformDouble, UniformFloat, UniformInt16, UniformInt32, UniformInt64, UniformInt8, UniformUInt16, UniformUInt32, UniformUInt64, and UniformUInt8.
Referenced by VectorType::GetAsUniformType(), GetDIType(), and VectorType::getVectorMemoryCount().
const AtomicType * AtomicType::GetAsUnsignedType () const [virtual]
If this is a signed integer type, return the unsigned version of the type. Otherwise, return the original type.
Reimplemented from Type.
Definition at line 168 of file type.cpp.
References IsUnsignedType(), NULL, UniformConstUInt16, UniformConstUInt32, UniformConstUInt64, UniformConstUInt8, UniformUInt16, UniformUInt32, UniformUInt64, UniformUInt8, VaryingConstUInt16, VaryingConstUInt32, VaryingConstUInt64, VaryingConstUInt8, VaryingUInt16, VaryingUInt32, VaryingUInt64, and VaryingUInt8.
const AtomicType * AtomicType::GetAsVaryingType () const [virtual]
Return a "varying" instance of this type. If the type is already uniform, its "this" pointer will be returned.
Implements Type.
Definition at line 247 of file type.cpp.
References basicType, FATAL, isConst, Type::IsVaryingType(), NULL, TYPE_BOOL, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT16, TYPE_INT32, TYPE_INT64, TYPE_INT8, TYPE_UINT16, TYPE_UINT32, TYPE_UINT64, TYPE_UINT8, TYPE_VOID, VaryingBool, VaryingConstBool, VaryingConstDouble, VaryingConstFloat, VaryingConstInt16, VaryingConstInt32, VaryingConstInt64, VaryingConstInt8, VaryingConstUInt16, VaryingConstUInt32, VaryingConstUInt64, VaryingConstUInt8, VaryingDouble, VaryingFloat, VaryingInt16, VaryingInt32, VaryingInt64, VaryingInt8, VaryingUInt16, VaryingUInt32, VaryingUInt64, and VaryingUInt8.
Referenced by VectorType::GetAsVaryingType().
const AtomicType * AtomicType::GetBaseType () const [virtual]
For AtomicTypes, the base type is just the same as the AtomicType itself.
Implements Type.
Definition at line 241 of file type.cpp.
std::string AtomicType::GetCDeclaration (const std::string & name) const [virtual]
Returns a string that is the declaration of the same type in C syntax.
Implements Type.
Definition at line 354 of file type.cpp.
References Assert, basicType, Module::errorCount, FATAL, isConst, isUniform, lShouldPrintName(), m, TYPE_BOOL, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT16, TYPE_INT32, TYPE_INT64, TYPE_INT8, TYPE_UINT16, TYPE_UINT32, TYPE_UINT64, TYPE_UINT8, and TYPE_VOID.
Referenced by VectorType::GetCDeclaration().
llvm::DIType AtomicType::GetDIType (llvm::DIDescriptor scope) const [virtual]
Returns the DIType (LLVM's debugging information structure), corresponding to this type.
Implements Type.
Definition at line 417 of file type.cpp.
References basicType, Module::diBuilder, FATAL, g, GetAsUniformType(), GetDIType(), isUniform, m, Globals::target, TYPE_BOOL, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT16, TYPE_INT32, TYPE_INT64, TYPE_INT8, TYPE_UINT16, TYPE_UINT32, TYPE_UINT64, TYPE_UINT8, TYPE_VOID, and Target::vectorWidth.
Referenced by GetDIType(), and VectorType::GetDIType().
const Type * AtomicType::GetSOAType (int width) const [virtual]
Return a new type representing the current type laid out in width-wide SOA (structure of arrays) format.
Implements Type.
Definition at line 295 of file type.cpp.
References Assert.
std::string AtomicType::GetString () const [virtual]
Returns a text representation of the type (for example, for use in warning and error messages).
Implements Type.
Definition at line 302 of file type.cpp.
References basicType, FATAL, isConst, isUniform, TYPE_BOOL, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT16, TYPE_INT32, TYPE_INT64, TYPE_INT8, TYPE_UINT16, TYPE_UINT32, TYPE_UINT64, TYPE_UINT8, and TYPE_VOID.
Referenced by VectorType::GetString().
bool AtomicType::IsBoolType () const [virtual]
Returns true if the underlying type is boolean. In other words, this is true for individual bools and for short-vectors with underlying bool type, but not for arrays of bools.
Implements Type.
Definition at line 156 of file type.cpp.
References basicType, and TYPE_BOOL.
Referenced by VectorType::IsBoolType().
bool AtomicType::IsConstType () const [virtual]
Returns true if this type is 'const'-qualified.
Implements Type.
Definition at line 162 of file type.cpp.
References isConst.
Referenced by VectorType::IsConstType().
bool AtomicType::IsFloatType () const [virtual]
Returns true if the underlying type is float or double. In other words, this is true for individual floats/doubles and for short-vectors of them, but not for arrays of them.
Implements Type.
Definition at line 134 of file type.cpp.
References basicType, TYPE_DOUBLE, and TYPE_FLOAT.
Referenced by VectorType::IsFloatType().
bool AtomicType::IsIntType () const [virtual]
Returns true if the underlying type is an integer type. In other words, this is true for individual integers and for short-vectors of integer types, but not for arrays of integer types.
Implements Type.
Definition at line 140 of file type.cpp.
References basicType, TYPE_INT16, TYPE_INT32, TYPE_INT64, TYPE_INT8, TYPE_UINT16, TYPE_UINT32, TYPE_UINT64, and TYPE_UINT8.
Referenced by VectorType::IsIntType(), lDoTypeConv(), and TypeCastExpr::TypeCheck().
bool AtomicType::IsUniformType () const [virtual]
Returns true if the underlying type is uniform
Implements Type.
Definition at line 128 of file type.cpp.
References isUniform.
Referenced by GetAsUniformType(), VectorType::IsUniformType(), VectorType::LLVMType(), lMatchWithTypeWidening(), and lTypeConvAtomic().
bool AtomicType::IsUnsignedType () const [virtual]
Returns true if the underlying type is unsigned. In other words, this is true for unsigned integers and short vectors of unsigned integer types.
Implements Type.
Definition at line 149 of file type.cpp.
References basicType, TYPE_UINT16, TYPE_UINT32, TYPE_UINT64, and TYPE_UINT8.
Referenced by GetAsUnsignedType(), and VectorType::IsUnsignedType().
LLVM_TYPE_CONST llvm::Type * AtomicType::LLVMType (llvm::LLVMContext * ctx) const [virtual]
Returns the LLVM type corresponding to this ispc type
Implements Type.
Definition at line 387 of file type.cpp.
References basicType, LLVMTypes::BoolType, LLVMTypes::BoolVectorType, LLVMTypes::DoubleType, LLVMTypes::DoubleVectorType, FATAL, LLVMTypes::FloatType, LLVMTypes::FloatVectorType, LLVMTypes::Int16Type, LLVMTypes::Int16VectorType, LLVMTypes::Int32Type, LLVMTypes::Int32VectorType, LLVMTypes::Int64Type, LLVMTypes::Int64VectorType, LLVMTypes::Int8Type, LLVMTypes::Int8VectorType, isUniform, NULL, TYPE_BOOL, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT16, TYPE_INT32, TYPE_INT64, TYPE_INT8, TYPE_UINT16, TYPE_UINT32, TYPE_UINT64, TYPE_UINT8, and TYPE_VOID.
Referenced by VectorType::LLVMType().
std::string AtomicType::Mangle () const [virtual]
Returns a string that represents the mangled type (for use in mangling function symbol names for function overloading). The various Types implementations of this method should collectively ensure that all of them use mangling schemes that are guaranteed not to clash.
Implements Type.
Definition at line 329 of file type.cpp.
References basicType, FATAL, isConst, isUniform, TYPE_BOOL, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INT16, TYPE_INT32, TYPE_INT64, TYPE_INT8, TYPE_UINT16, TYPE_UINT32, TYPE_UINT64, TYPE_UINT8, and TYPE_VOID.
Referenced by VectorType::Mangle().
Member Data Documentation
const BasicType AtomicType::basicType
Definition at line 229 of file type.h.
Referenced by GetAsConstType(), GetAsNonConstType(), GetAsUniformType(), GetAsVaryingType(), ConstExpr::getBasicType(), GetCDeclaration(), GetDIType(), GetString(), IsBoolType(), IsFloatType(), IsIntType(), IsUnsignedType(), lLLVMConstantValue(), LLVMType(), lMatchWithTypeWidening(), lTypeConvAtomic(), Mangle(), Type::MoreGeneralType(), TypeCastExpr::Optimize(), and TypeCastExpr::TypeCheck().
const bool AtomicType::isConst [private]
Definition at line 257 of file type.h.
Referenced by GetAsUniformType(), GetAsVaryingType(), GetCDeclaration(), GetString(), IsConstType(), and Mangle().
const bool AtomicType::isUniform [private]
Definition at line 256 of file type.h.
Referenced by GetAsConstType(), GetAsNonConstType(), GetCDeclaration(), GetDIType(), GetString(), IsUniformType(), LLVMType(), and Mangle().
const AtomicType * AtomicType::UniformBool = new AtomicType(TYPE_BOOL, true, false) [static]
Definition at line 231 of file type.h.
Referenced by GetAsNonConstType(), GetAsUniformType(), ConstExpr::GetConstant(), SelectExpr::GetValue(), lConstFoldBinLogicalOp(), lEncodeType(), lLLVMTypeToISPCType(), lMatchingBoolType(), UnaryExpr::Optimize(), BinaryExpr::Optimize(), IfStmt::TypeCheck(), BinaryExpr::TypeCheck(), DoStmt::TypeCheck(), ForStmt::TypeCheck(), and AssertStmt::TypeCheck().
const AtomicType * AtomicType::UniformConstBool = new AtomicType(TYPE_BOOL, true, true) [static]
Definition at line 242 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), GetAsUniformType(), and UnaryExpr::Optimize().
const AtomicType * AtomicType::UniformConstDouble = new AtomicType(TYPE_DOUBLE, true, true) [static]
Definition at line 252 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), and GetAsUniformType().
const AtomicType * AtomicType::UniformConstFloat = new AtomicType(TYPE_FLOAT, true, true) [static]
Definition at line 249 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), GetAsUniformType(), and BinaryExpr::Optimize().
const AtomicType * AtomicType::UniformConstInt16 = new AtomicType(TYPE_INT16, true, true) [static]
Definition at line 244 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), and GetAsUniformType().
const AtomicType * AtomicType::UniformConstInt32 = new AtomicType(TYPE_INT32, true, true) [static]
Definition at line 245 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), GetAsUniformType(), lDefineConstantInt(), and UnaryExpr::Optimize().
const AtomicType * AtomicType::UniformConstInt64 = new AtomicType(TYPE_INT64, true, true) [static]
Definition at line 250 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), and GetAsUniformType().
const AtomicType * AtomicType::UniformConstInt8 = new AtomicType(TYPE_INT8, true, true) [static]
Definition at line 243 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), and GetAsUniformType().
const AtomicType * AtomicType::UniformConstUInt16 = new AtomicType(TYPE_UINT16, true, true) [static]
Definition at line 247 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), GetAsUniformType(), and GetAsUnsignedType().
const AtomicType * AtomicType::UniformConstUInt32 = new AtomicType(TYPE_UINT32, true, true) [static]
Definition at line 248 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), GetAsUniformType(), GetAsUnsignedType(), and UnaryExpr::Optimize().
const AtomicType * AtomicType::UniformConstUInt64 = new AtomicType(TYPE_UINT64, true, true) [static]
Definition at line 251 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), GetAsUniformType(), and GetAsUnsignedType().
const AtomicType * AtomicType::UniformConstUInt8 = new AtomicType(TYPE_UINT8, true, true) [static]
Definition at line 246 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), GetAsUniformType(), and GetAsUnsignedType().
const AtomicType * AtomicType::UniformDouble = new AtomicType(TYPE_DOUBLE, true, false) [static]
Definition at line 241 of file type.h.
Referenced by GetAsNonConstType(), GetAsUniformType(), ConstExpr::GetConstant(), lEncodeType(), lLLVMTypeToISPCType(), and BinaryExpr::Optimize().
const AtomicType * AtomicType::UniformFloat = new AtomicType(TYPE_FLOAT, true, false) [static]
Definition at line 238 of file type.h.
Referenced by GetAsNonConstType(), GetAsUniformType(), ConstExpr::GetConstant(), lEncodeType(), lLLVMTypeToISPCType(), and BinaryExpr::Optimize().
const AtomicType * AtomicType::UniformInt16 = new AtomicType(TYPE_INT16, true, false) [static]
Definition at line 233 of file type.h.
Referenced by GetAsNonConstType(), GetAsUniformType(), ConstExpr::GetConstant(), lLLVMTypeToISPCType(), lProcessPrintArg(), and UnaryExpr::Optimize().
const AtomicType * AtomicType::UniformInt32 = new AtomicType(TYPE_INT32, true, false) [static]
Definition at line 234 of file type.h.
Referenced by GetAsNonConstType(), GetAsUniformType(), ConstExpr::GetConstant(), BinaryExpr::GetType(), lArrayToPointer(), lDefineConstantIntFunc(), lEmitPrePostIncDec(), lEncodeType(), lLLVMTypeToISPCType(), lProcessPrintArg(), UnaryExpr::Optimize(), BinaryExpr::Optimize(), BinaryExpr::TypeCheck(), AssignExpr::TypeCheck(), FunctionCallExpr::TypeCheck(), ForeachStmt::TypeCheck(), and IndexExpr::TypeCheck().
const AtomicType * AtomicType::UniformInt64 = new AtomicType(TYPE_INT64, true, false) [static]
Definition at line 239 of file type.h.
Referenced by GetAsNonConstType(), GetAsUniformType(), ConstExpr::GetConstant(), BinaryExpr::GetType(), lEncodeType(), lLLVMTypeToISPCType(), UnaryExpr::Optimize(), BinaryExpr::TypeCheck(), and AssignExpr::TypeCheck().
const AtomicType * AtomicType::UniformInt8 = new AtomicType(TYPE_INT8, true, false) [static]
Definition at line 232 of file type.h.
Referenced by GetAsNonConstType(), GetAsUniformType(), ConstExpr::GetConstant(), lLLVMTypeToISPCType(), lProcessPrintArg(), and UnaryExpr::Optimize().
const AtomicType * AtomicType::UniformUInt16 = new AtomicType(TYPE_UINT16, true, false) [static]
Definition at line 236 of file type.h.
Referenced by GetAsNonConstType(), GetAsUniformType(), GetAsUnsignedType(), ConstExpr::GetConstant(), lLLVMTypeToISPCType(), lProcessPrintArg(), and UnaryExpr::Optimize().
const AtomicType * AtomicType::UniformUInt32 = new AtomicType(TYPE_UINT32, true, false) [static]
Definition at line 237 of file type.h.
Referenced by GetAsNonConstType(), GetAsUniformType(), GetAsUnsignedType(), ConstExpr::GetConstant(), SizeOfExpr::GetType(), TypeCastExpr::GetValue(), lEncodeType(), lLLVMTypeToISPCType(), UnaryExpr::Optimize(), and BinaryExpr::Optimize().
const AtomicType * AtomicType::UniformUInt64 = new AtomicType(TYPE_UINT64, true, false) [static]
Definition at line 240 of file type.h.
Referenced by GetAsNonConstType(), GetAsUniformType(), GetAsUnsignedType(), ConstExpr::GetConstant(), SizeOfExpr::GetType(), lEncodeType(), lLLVMTypeToISPCType(), and UnaryExpr::Optimize().
const AtomicType * AtomicType::UniformUInt8 = new AtomicType(TYPE_UINT8, true, false) [static]
Definition at line 235 of file type.h.
Referenced by GetAsNonConstType(), GetAsUniformType(), GetAsUnsignedType(), ConstExpr::GetConstant(), lLLVMTypeToISPCType(), lProcessPrintArg(), and UnaryExpr::Optimize().
const AtomicType * AtomicType::VaryingBool = new AtomicType(TYPE_BOOL, false, false)
Definition at line 231 of file type.h.
Referenced by GetAsNonConstType(), GetAsVaryingType(), ConstExpr::GetConstant(), SelectExpr::GetValue(), lConstFoldBinLogicalOp(), lCreateISPCSymbol(), lEncodeType(), lMatchingBoolType(), FunctionEmitContext::maskedStore(), UnaryExpr::Optimize(), BinaryExpr::Optimize(), IfStmt::TypeCheck(), BinaryExpr::TypeCheck(), DoStmt::TypeCheck(), ForStmt::TypeCheck(), and AssertStmt::TypeCheck().
const AtomicType * AtomicType::VaryingConstBool = new AtomicType(TYPE_BOOL, false, true)
Definition at line 242 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), GetAsVaryingType(), and UnaryExpr::Optimize().
const AtomicType * AtomicType::VaryingConstDouble = new AtomicType(TYPE_DOUBLE, false, true)
Definition at line 252 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), and GetAsVaryingType().
const AtomicType * AtomicType::VaryingConstFloat = new AtomicType(TYPE_FLOAT, false, true)
Definition at line 249 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), GetAsVaryingType(), and BinaryExpr::Optimize().
const AtomicType * AtomicType::VaryingConstInt16 = new AtomicType(TYPE_INT16, false, true)
Definition at line 244 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), and GetAsVaryingType().
const AtomicType * AtomicType::VaryingConstInt32 = new AtomicType(TYPE_INT32, false, true)
Definition at line 245 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), GetAsVaryingType(), lDefineProgramIndex(), and UnaryExpr::Optimize().
const AtomicType * AtomicType::VaryingConstInt64 = new AtomicType(TYPE_INT64, false, true)
Definition at line 250 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), and GetAsVaryingType().
const AtomicType * AtomicType::VaryingConstInt8 = new AtomicType(TYPE_INT8, false, true)
Definition at line 243 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), and GetAsVaryingType().
const AtomicType * AtomicType::VaryingConstUInt16 = new AtomicType(TYPE_UINT16, false, true)
Definition at line 247 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), GetAsUnsignedType(), and GetAsVaryingType().
const AtomicType * AtomicType::VaryingConstUInt32 = new AtomicType(TYPE_UINT32, false, true)
Definition at line 248 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), GetAsUnsignedType(), GetAsVaryingType(), and UnaryExpr::Optimize().
const AtomicType * AtomicType::VaryingConstUInt64 = new AtomicType(TYPE_UINT64, false, true)
Definition at line 251 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), GetAsUnsignedType(), and GetAsVaryingType().
const AtomicType * AtomicType::VaryingConstUInt8 = new AtomicType(TYPE_UINT8, false, true)
Definition at line 246 of file type.h.
Referenced by ConstExpr::ConstExpr(), GetAsConstType(), GetAsUnsignedType(), and GetAsVaryingType().
const AtomicType * AtomicType::VaryingDouble = new AtomicType(TYPE_DOUBLE, false, false)
Definition at line 241 of file type.h.
Referenced by GetAsNonConstType(), GetAsVaryingType(), ConstExpr::GetConstant(), lEncodeType(), lLLVMTypeToISPCType(), FunctionEmitContext::maskedStore(), and BinaryExpr::Optimize().
const AtomicType * AtomicType::VaryingFloat = new AtomicType(TYPE_FLOAT, false, false)
Definition at line 238 of file type.h.
Referenced by GetAsNonConstType(), GetAsVaryingType(), ConstExpr::GetConstant(), lEncodeType(), lLLVMTypeToISPCType(), FunctionEmitContext::maskedStore(), and BinaryExpr::Optimize().
const AtomicType * AtomicType::VaryingInt16 = new AtomicType(TYPE_INT16, false, false)
Definition at line 233 of file type.h.
Referenced by GetAsNonConstType(), GetAsVaryingType(), ConstExpr::GetConstant(), lLLVMTypeToISPCType(), and FunctionEmitContext::maskedStore().
const AtomicType * AtomicType::VaryingInt32 = new AtomicType(TYPE_INT32, false, false)
Definition at line 234 of file type.h.
Referenced by GetAsNonConstType(), GetAsVaryingType(), ConstExpr::GetConstant(), lCreateISPCSymbol(), lEmitPrePostIncDec(), lEncodeType(), lLLVMTypeToISPCType(), lProcessPrintArg(), FunctionEmitContext::maskedStore(), UnaryExpr::Optimize(), BinaryExpr::Optimize(), and IndexExpr::TypeCheck().
const AtomicType * AtomicType::VaryingInt64 = new AtomicType(TYPE_INT64, false, false)
Definition at line 239 of file type.h.
Referenced by GetAsNonConstType(), GetAsVaryingType(), ConstExpr::GetConstant(), lEncodeType(), lLLVMTypeToISPCType(), and FunctionEmitContext::maskedStore().
const AtomicType * AtomicType::VaryingInt8 = new AtomicType(TYPE_INT8, false, false)
Definition at line 232 of file type.h.
Referenced by GetAsNonConstType(), GetAsVaryingType(), ConstExpr::GetConstant(), lLLVMTypeToISPCType(), and FunctionEmitContext::maskedStore().
const AtomicType * AtomicType::VaryingUInt16 = new AtomicType(TYPE_UINT16, false, false)
Definition at line 236 of file type.h.
Referenced by GetAsNonConstType(), GetAsUnsignedType(), GetAsVaryingType(), ConstExpr::GetConstant(), lLLVMTypeToISPCType(), and FunctionEmitContext::maskedStore().
const AtomicType * AtomicType::VaryingUInt32 = new AtomicType(TYPE_UINT32, false, false)
Definition at line 237 of file type.h.
Referenced by GetAsNonConstType(), GetAsUnsignedType(), GetAsVaryingType(), ConstExpr::GetConstant(), TypeCastExpr::GetValue(), lEncodeType(), lLLVMTypeToISPCType(), FunctionEmitContext::maskedStore(), UnaryExpr::Optimize(), and BinaryExpr::Optimize().
const AtomicType * AtomicType::VaryingUInt64 = new AtomicType(TYPE_UINT64, false, false)
Definition at line 240 of file type.h.
Referenced by GetAsNonConstType(), GetAsUnsignedType(), GetAsVaryingType(), ConstExpr::GetConstant(), lEncodeType(), lLLVMTypeToISPCType(), and FunctionEmitContext::maskedStore().
const AtomicType * AtomicType::VaryingUInt8 = new AtomicType(TYPE_UINT8, false, false)
Definition at line 235 of file type.h.
Referenced by GetAsNonConstType(), GetAsUnsignedType(), GetAsVaryingType(), ConstExpr::GetConstant(), lLLVMTypeToISPCType(), and FunctionEmitContext::maskedStore().
const AtomicType * AtomicType::Void = new AtomicType(TYPE_VOID, true, false) [static]
Definition at line 253 of file type.h.
Referenced by Module::AddFunctionDeclaration(), FunctionEmitContext::CurrentLanesReturned(), FunctionEmitContext::FunctionEmitContext(), SyncExpr::GetType(), FunctionCallExpr::GetValue(), TypeCastExpr::GetValue(), lDoTypeConv(), lLLVMTypeToISPCType(), and FunctionEmitContext::ReturnInst().
The documentation for this class was generated from the following files:
type.h
type.cpp