Intel SPMD Program Compiler: PrintStmt Class Reference
PrintStmt Class Reference
Representation of a print() statement in the program.
#include <stmt.h>
Public Member Functions
PrintStmt (const std::string &f, Expr *v, SourcePos p)
void EmitCode (FunctionEmitContext *ctx) const
void Print (int indent) const
Stmt * TypeCheck ()
int EstimateCost () const
Public Member Functions inherited from Stmt
Stmt (SourcePos p)
virtual Stmt * Optimize ()
Public Member Functions inherited from ASTNode
ASTNode (SourcePos p)
virtual ~ASTNode ()
Public Attributes
const std::string format
Expr * values
Detailed Description
Representation of a print() statement in the program.
It's currently necessary to have a special statement type for print() since strings aren't supported as first-class types in the language, but we need to be able to pass a formatting string as the first argument to print(). We also need this to be a variable argument function, which also isn't supported. Representing print() as a statement lets us work around both of those ugly little issues...
Definition at line 437 of file stmt.h.
Constructor & Destructor Documentation
PrintStmt::PrintStmt (const std::string & f, Expr * v, SourcePos p)
Definition at line 2933 of file stmt.cpp.
Member Function Documentation
void PrintStmt::EmitCode (FunctionEmitContext * ctx) const virtual
Emit LLVM IR for the statement, using the FunctionEmitContext to create the necessary instructions.
Implements Stmt.
Definition at line 3028 of file stmt.cpp.
References FunctionEmitContext::AddElementOffset(), FunctionEmitContext::AllocaInst(), AssertPos, FunctionEmitContext::BitCastInst(), FunctionEmitContext::CallInst(), ExprList::exprs, format, g, FunctionEmitContext::GetCurrentBasicBlock(), FunctionEmitContext::GetFullMask(), FunctionEmitContext::GetStringPtr(), Target::getVectorWidth(), FunctionEmitContext::LaneMask(), LLVMInt32(), lProcessPrintArg(), m, Module::module, ASTNode::pos, FunctionEmitContext::SetDebugPos(), FunctionEmitContext::StoreInst(), Globals::target, values, and LLVMTypes::VoidPointerType.
int PrintStmt::EstimateCost () const virtual
Estimate the execution cost of the node (not including the cost of the children. The value returned should be based on the COST_* enumerant values defined in ispc.h.
Implements ASTNode.
Definition at line 3122 of file stmt.cpp.
References COST_FUNCALL.
void PrintStmt::Print (int indent) const virtual
Print a representation of the statement (and any children AST nodes) to standard output. This method is used for debuggins.
Implements Stmt.
Definition at line 3110 of file stmt.cpp.
References format.
Stmt * PrintStmt::TypeCheck () virtual
Type checking should be performed by the node when this method is called. In the event of an error, a NULL value may be returned. As with ASTNode::Optimize(), the caller should store the returned pointer in place of the original ASTNode *.
Implements Stmt.
Definition at line 3116 of file stmt.cpp.
Member Data Documentation
const std::string PrintStmt::format
Format string for the print() statement.
Definition at line 448 of file stmt.h.
Referenced by EmitCode(), and Print().
Expr* PrintStmt::values
This holds the arguments passed to the print() statement. If more than one was provided, this will be an ExprList.
Definition at line 451 of file stmt.h.
Referenced by EmitCode(), and WalkAST().
The documentation for this class was generated from the following files:
stmt.h
stmt.cpp