Intel SPMD Program Compiler: GatherScatterFlattenOpt Class Reference
GatherScatterFlattenOpt Class Reference
Public Member Functions
GatherScatterFlattenOpt ()
const char * getPassName () const
bool runOnBasicBlock (llvm::BasicBlock &BB)
Static Public Attributes
static char ID = 0
Detailed Description
When the front-end emits gathers and scatters, it generates an array of vector-width pointers to represent the set of addresses to read from or write to. This optimization detects cases when the base pointer is a uniform pointer or when the indexing is into an array that can be converted into scatters/gathers from a single base pointer and an array of offsets.
See for example the comments discussing the __pseudo_gather functions in builtins.cpp for more information about this.
Definition at line 910 of file opt.cpp.
Constructor & Destructor Documentation
GatherScatterFlattenOpt::GatherScatterFlattenOpt () [inline]
Definition at line 913 of file opt.cpp.
Member Function Documentation
const char* GatherScatterFlattenOpt::getPassName () const [inline]
Definition at line 915 of file opt.cpp.
bool GatherScatterFlattenOpt::runOnBasicBlock (llvm::BasicBlock & BB)
Definition at line 1265 of file opt.cpp.
References Assert, GSInfo::baseOffsets32Func, GSInfo::baseOffsetsFunc, Opt::force32BitAddressing, GSInfo::func, g, LLVMTypes::Int32VectorType, GSInfo::isGather, lCopyMetadata(), lExtractOffsetVector248Scale(), lGetBasePtrAndOffsets(), NULL, Globals::opt, and LLVMTypes::VoidPointerType.
Member Data Documentation
char GatherScatterFlattenOpt::ID = 0 [static]
Definition at line 912 of file opt.cpp.
The documentation for this class was generated from the following file:
opt.cpp