Intel SPMD Program Compiler: ExprStmt Class Reference
ExprStmt Class Reference
Statement representing a single expression.
#include <stmt.h>
Public Member Functions
ExprStmt (Expr *expr, SourcePos pos)
void EmitCode (FunctionEmitContext *ctx) const
void Print (int indent) const
Stmt * Optimize ()
Stmt * TypeCheck ()
Private Attributes
Expr * expr
Detailed Description
Statement representing a single expression.
Definition at line 69 of file stmt.h.
Constructor & Destructor Documentation
ExprStmt::ExprStmt (Expr * expr, SourcePos pos)
Definition at line 65 of file stmt.cpp.
References expr.
Member Function Documentation
void ExprStmt::EmitCode (FunctionEmitContext * ctx) const [virtual]
Emit LLVM IR for the statement, using the FunctionEmitContext to create the necessary instructions.
Implements Stmt.
Definition at line 71 of file stmt.cpp.
References expr, FunctionEmitContext::GetCurrentBasicBlock(), Expr::GetValue(), ASTNode::pos, and FunctionEmitContext::SetDebugPos().
Referenced by FunctionEmitContext::ReturnInst().
Stmt * ExprStmt::Optimize () [virtual]
The Optimize() method should perform any appropriate early-stage optimizations on the node (e.g. constant folding). The caller should use the returned ASTNode * in place of the original node. This method may return NULL if an error is encountered during optimization.
Implements Stmt.
Definition at line 82 of file stmt.cpp.
References expr, and Expr::Optimize().
void ExprStmt::Print (int indent) const [virtual]
Print a representation of the statement (and any children AST nodes) to standard output. This method is used for debuggins.
Implements Stmt.
Definition at line 98 of file stmt.cpp.
References expr, ASTNode::pos, Expr::Print(), and SourcePos::Print().
Stmt * ExprStmt::TypeCheck () [virtual]
Type checking should be performed by the node when this method is called. In the event of an error, a NULL value may be returned. As with ASTNode::Optimize(), the caller should store the returned pointer in place of the original ASTNode *.
Implements Stmt.
Definition at line 90 of file stmt.cpp.
References expr, and Expr::TypeCheck().
Member Data Documentation
Expr* ExprStmt::expr [private]
Definition at line 80 of file stmt.h.
Referenced by EmitCode(), ExprStmt(), Optimize(), Print(), and TypeCheck().
The documentation for this class was generated from the following files:
stmt.h
stmt.cpp