Intel SPMD Program Compiler: MaskOpsCleanupPass Class Reference
MaskOpsCleanupPass Class Reference
Public Member Functions
MaskOpsCleanupPass (llvm::Module *m)
const char * getPassName () const
bool runOnBasicBlock (llvm::BasicBlock &BB)
Private Member Functions
llvm::Value * lGetNotOperand (llvm::Value *v) const
Private Attributes
llvm::Function * notFunc
llvm::Function * andNotFuncs [2]
Static Private Attributes
static char ID = 0
Detailed Description
This pass does various peephole improvements to mask modification operations. In particular, it converts mask XORs with "all true" to calls to __not() and replaces operations like and(not(a), b) to __and_not1(a, b) (and similarly if the second operand has not applied to it...)
Definition at line 4745 of file cbackend.cpp.
Constructor & Destructor Documentation
MaskOpsCleanupPass::MaskOpsCleanupPass (llvm::Module * m) inline
Definition at line 4747 of file cbackend.cpp.
References andNotFuncs, LLVMTypes::MaskType, and notFunc.
Member Function Documentation
const char* MaskOpsCleanupPass::getPassName () const inline
Definition at line 4788 of file cbackend.cpp.
llvm::Value * MaskOpsCleanupPass::lGetNotOperand (llvm::Value * v) const private
Checks to see if the given value is the NOT of some other value. If so, it returns the operand of the NOT; otherwise returns NULL.
Definition at line 4829 of file cbackend.cpp.
References lIsAllTrue(), and notFunc.
Referenced by runOnBasicBlock().
bool MaskOpsCleanupPass::runOnBasicBlock (llvm::BasicBlock & BB)
Definition at line 4846 of file cbackend.cpp.
References andNotFuncs, lGetNotOperand(), lIsAllTrue(), LLVMTypes::MaskType, and notFunc.
Member Data Documentation
llvm::Function * MaskOpsCleanupPass::andNotFuncs[2] private
Definition at line 4794 of file cbackend.cpp.
Referenced by MaskOpsCleanupPass(), and runOnBasicBlock().
char MaskOpsCleanupPass::ID = 0 static private
Definition at line 4796 of file cbackend.cpp.
llvm::Function* MaskOpsCleanupPass::notFunc private
Definition at line 4794 of file cbackend.cpp.
Referenced by lGetNotOperand(), MaskOpsCleanupPass(), and runOnBasicBlock().
The documentation for this class was generated from the following file:
cbackend.cpp