Intel SPMD Program Compiler: ArgFactory Class Reference
ArgFactory Class Reference abstract
Public Member Functions
ArgFactory ()
char * GetNextArg ()
Private Member Functions
char * AllocateString (std::string string)
virtual char GetNextChar ()=0
Detailed Description
Define an abstract base-class that implements the parsing of an character source and the breaking of it into the individual arguments
Definition at line 209 of file main.cpp.
Constructor & Destructor Documentation
ArgFactory()
ArgFactory::ArgFactory () inline
Definition at line 224 of file main.cpp.
Member Function Documentation
AllocateString()
char* ArgFactory::AllocateString (std::string string) inline private
Definition at line 211 of file main.cpp.
Referenced by GetNextArg().
GetNextArg()
char* ArgFactory::GetNextArg () inline
Definition at line 226 of file main.cpp.
References AllocateString(), and GetNextChar().
Referenced by lAddArgsFromFactory().
GetNextChar()
virtual char ArgFactory::GetNextChar () private pure virtual
Method provided by the derived classes to retrieve the next character from the stream.
Implemented in StringArgFactory, and FileArgFactory.
Referenced by GetNextArg().
The documentation for this class was generated from the following file:
main.cpp