Intel SPMD Program Compiler: LowerMaskedStorePass Class Reference
LowerMaskedStorePass Class Reference
Public Member Functions
LowerMaskedStorePass ()
const char * getPassName () const
bool runOnBasicBlock (llvm::BasicBlock &BB)
Static Public Attributes
static char ID = 0
Detailed Description
When the front-end needs to do a masked store, it emits a __pseudo_masked_store_{32,64} call as a placeholder. This pass lowers these calls to either __masked_store_{32,64} or __masked_store_blend_{32,64} calls.
Definition at line 1170 of file opt.cpp.
Constructor & Destructor Documentation
LowerMaskedStorePass::LowerMaskedStorePass () [inline]
Definition at line 1173 of file opt.cpp.
Member Function Documentation
const char* LowerMaskedStorePass::getPassName () const [inline]
Definition at line 1175 of file opt.cpp.
bool LowerMaskedStorePass::runOnBasicBlock (llvm::BasicBlock & BB)
Definition at line 1235 of file opt.cpp.
References assert, Opt::disableBlendedMaskedStores, g, Target::isa, lCopyMetadata(), lIsStackVariablePointer(), lMaskedStoreName(), m, Module::module, Globals::opt, Target::SSE2, Target::SSE4, and Globals::target.
Member Data Documentation
char LowerMaskedStorePass::ID = 0 [static]
Definition at line 1172 of file opt.cpp.
The documentation for this class was generated from the following file:
opt.cpp