Intel SPMD Program Compiler: StructMemberExpr Class Reference
StructMemberExpr Class Reference
Public Member Functions
StructMemberExpr (Expr *e, const char *id, SourcePos p, SourcePos idpos, bool derefLValue)
const Type * GetType () const
const Type * GetLValueType () const
int getElementNumber () const
const Type * getElementType () const
Public Member Functions inherited from MemberExpr
llvm::Value * GetValue (FunctionEmitContext *ctx) const
llvm::Value * GetLValue (FunctionEmitContext *ctx) const
Symbol * GetBaseSymbol () const
void Print () const
Expr * Optimize ()
Expr * TypeCheck ()
int EstimateCost () const
std::string getCandidateNearMatches () const
MemberExpr (Expr *expr, const char *identifier, SourcePos pos, SourcePos identifierPos, bool derefLValue, unsigned scid)
Public Member Functions inherited from Expr
Expr (SourcePos p, unsigned scid)
virtual llvm::Constant * GetConstant (const Type *type) const
Public Member Functions inherited from ASTNode
ASTNode (SourcePos p, unsigned scid)
virtual ~ASTNode ()
unsigned getValueID () const
Static Public Member Functions
static bool classof (StructMemberExpr const *)
static bool classof (ASTNode const *N)
Static Public Member Functions inherited from MemberExpr
static MemberExpr * create (Expr *expr, const char *identifier, SourcePos pos, SourcePos identifierPos, bool derefLvalue)
static bool classof (MemberExpr const *)
static bool classof (ASTNode const *N)
Static Public Member Functions inherited from Expr
static bool classof (Expr const *)
static bool classof (ASTNode const *N)
Static Public Member Functions inherited from ASTNode
static bool classof (ASTNode const *)
Private Member Functions
const StructType * getStructType () const
Additional Inherited Members
Public Types inherited from ASTNode
enum ASTNodeTy {
AddressOfExprID, AssignExprID, BinaryExprID, ConstExprID,
DerefExprID, PtrDerefExprID, RefDerefExprID, ExprListID,
FunctionCallExprID, FunctionSymbolExprID, IndexExprID, StructMemberExprID,
VectorMemberExprID, NewExprID, NullPointerExprID, ReferenceExprID,
SelectExprID, SizeOfExprID, SymbolExprID, SyncExprID,
TypeCastExprID, UnaryExprID, MaxExprID, AssertStmtID,
BreakStmtID, CaseStmtID, ContinueStmtID, DeclStmtID,
DefaultStmtID, DeleteStmtID, DoStmtID, ExprStmtID,
ForeachActiveStmtID, ForeachStmtID, ForeachUniqueStmtID, ForStmtID,
GotoStmtID, IfStmtID, LabeledStmtID, PrintStmtID,
ReturnStmtID, StmtListID, SwitchStmtID, UnmaskedStmtID
}
Public Attributes inherited from MemberExpr
Expr * expr
std::string identifier
const SourcePos identifierPos
bool dereferenceExpr
Public Attributes inherited from ASTNode
SourcePos pos
Protected Attributes inherited from MemberExpr
const Type * type
const Type * lvalueType
Detailed Description
Definition at line 4367 of file expr.cpp.
Constructor & Destructor Documentation
StructMemberExpr()
StructMemberExpr::StructMemberExpr (Expr * e, const char * id, SourcePos p, SourcePos idpos, bool derefLValue)
Definition at line 4383 of file expr.cpp.
Member Function Documentation
classof() [1/2]
static bool StructMemberExpr::classof (StructMemberExpr const *) inline static
Definition at line 4371 of file expr.cpp.
classof() [2/2]
static bool StructMemberExpr::classof (ASTNode const * N) inline static
Definition at line 4372 of file expr.cpp.
References IndexExpr::GetLValueType(), IndexExpr::GetType(), ASTNode::getValueID(), and ASTNode::StructMemberExprID.
getElementNumber()
int StructMemberExpr::getElementNumber () const virtual
Implements MemberExpr.
Definition at line 4463 of file expr.cpp.
References Error(), MemberExpr::getCandidateNearMatches(), StructType::GetElementNumber(), StructType::GetString(), getStructType(), MemberExpr::identifier, and MemberExpr::identifierPos.
Referenced by VectorMemberExpr::classof().
getElementType()
const Type * StructMemberExpr::getElementType () const virtual
Implements MemberExpr.
Definition at line 4476 of file expr.cpp.
References StructType::GetElementType(), getStructType(), and MemberExpr::identifier.
Referenced by VectorMemberExpr::classof(), and GetLValueType().
GetLValueType()
const Type * StructMemberExpr::GetLValueType () const virtual
Returns the type of the value returned by GetLValueType(); this should be a pointer type of some sort (uniform or varying).
Reimplemented from Expr.
Definition at line 4431 of file expr.cpp.
References AssertPos, MemberExpr::dereferenceExpr, Module::errorCount, MemberExpr::expr, PointerType::GetAsFrozenSlice(), getElementType(), Expr::GetLValueType(), Expr::GetType(), PointerType::GetUniform(), PointerType::GetVarying(), Type::IsUniformType(), MemberExpr::lvalueType, and m.
Referenced by VectorMemberExpr::classof(), and GetType().
getStructType()
const StructType * StructMemberExpr::getStructType () const private
Returns the type of the underlying struct that we're returning a member of.
Definition at line 4486 of file expr.cpp.
References AssertPos, MemberExpr::dereferenceExpr, MemberExpr::expr, PointerType::GetBaseType(), Expr::GetLValueType(), ReferenceType::GetReferenceTarget(), Expr::GetType(), and MemberExpr::type.
Referenced by getElementNumber(), getElementType(), and GetType().
GetType()
const Type * StructMemberExpr::GetType () const virtual
Returns the Type of the expression.
Reimplemented from MemberExpr.
Definition at line 4386 of file expr.cpp.
References AssertPos, Type::Equal(), Error(), Module::errorCount, MemberExpr::expr, Type::GetAsUniformType(), Type::GetAsVaryingType(), Type::GetBaseType(), MemberExpr::getCandidateNearMatches(), StructType::GetElementType(), GetLValueType(), StructType::GetString(), getStructType(), Expr::GetType(), MemberExpr::identifier, MemberExpr::identifierPos, Type::IsSOAType(), Type::IsUniformType(), Type::IsVaryingType(), MemberExpr::lvalueType, m, and MemberExpr::type.
Referenced by VectorMemberExpr::classof().
The documentation for this class was generated from the following file:
expr.cpp