Intel® Implicit SPMD Program Compiler (Intel® ISPC): DefaultStmt Class Reference
DefaultStmt Class Reference
#include <stmt.h>
Public Member Functions
DefaultStmt (Stmt *stmt, SourcePos pos)
void EmitCode (FunctionEmitContext *ctx) const
void Print (int indent) const
Stmt * TypeCheck ()
int EstimateCost () const
Public Member Functions inherited from Stmt
Stmt (SourcePos p, unsigned scid)
virtual Stmt * Optimize ()
Public Member Functions inherited from ASTNode
ASTNode (SourcePos p, unsigned scid)
virtual ~ASTNode ()
unsigned getValueID () const
Static Public Member Functions
static bool classof (DefaultStmt const *)
static bool classof (ASTNode const *N)
Static Public Member Functions inherited from Stmt
static bool classof (Stmt const *)
static bool classof (ASTNode const *N)
Static Public Member Functions inherited from ASTNode
static bool classof (ASTNode const *)
Public Attributes
Stmt * stmts
Public Attributes inherited from ASTNode
SourcePos pos
Additional Inherited Members
Public Types inherited from ASTNode
enum ASTNodeTy {
AddressOfExprID, AssignExprID, BinaryExprID, ConstExprID,
DerefExprID, PtrDerefExprID, RefDerefExprID, ExprListID,
FunctionCallExprID, FunctionSymbolExprID, IndexExprID, StructMemberExprID,
VectorMemberExprID, NewExprID, NullPointerExprID, ReferenceExprID,
SelectExprID, SizeOfExprID, SymbolExprID, SyncExprID,
TypeCastExprID, UnaryExprID, MaxExprID, AssertStmtID,
BreakStmtID, CaseStmtID, ContinueStmtID, DeclStmtID,
DefaultStmtID, DeleteStmtID, DoStmtID, ExprStmtID,
ForeachActiveStmtID, ForeachStmtID, ForeachUniqueStmtID, ForStmtID,
GotoStmtID, IfStmtID, LabeledStmtID, PrintStmtID,
ReturnStmtID, StmtListID, SwitchStmtID, UnmaskedStmtID
}
Detailed Description
Statement for a "default" label (as would be found inside a "switch" statement).
Definition at line 360 of file stmt.h.
Constructor & Destructor Documentation
DefaultStmt()
DefaultStmt::DefaultStmt (Stmt * stmt, SourcePos pos)
Definition at line 2170 of file stmt.cpp.
References stmts.
Member Function Documentation
classof() [1/2]
static bool DefaultStmt::classof (DefaultStmt const *) inline static
Definition at line 364 of file stmt.h.
classof() [2/2]
static bool DefaultStmt::classof (ASTNode const * N) inline static
Definition at line 365 of file stmt.h.
References ASTNode::DefaultStmtID, Stmt::EmitCode(), ASTNode::EstimateCost(), ASTNode::getValueID(), Stmt::Print(), and Stmt::TypeCheck().
EmitCode()
void DefaultStmt::EmitCode (FunctionEmitContext * ctx) const virtual
Emit LLVM IR for the statement, using the FunctionEmitContext to create the necessary instructions.
Implements Stmt.
Definition at line 2172 of file stmt.cpp.
References Stmt::EmitCode(), FunctionEmitContext::EmitDefaultLabel(), lCheckMask(), ASTNode::pos, and stmts.
EstimateCost()
int DefaultStmt::EstimateCost () const virtual
Estimate the execution cost of the node (not including the cost of the children. The value returned should be based on the COST_* enumerant values defined in ispc.h.
Implements ASTNode.
Definition at line 2187 of file stmt.cpp.
Print()
void DefaultStmt::Print (int indent) const virtual
Print a representation of the statement (and any children AST nodes) to standard output. This method is used for debuggins.
Implements Stmt.
Definition at line 2178 of file stmt.cpp.
References ASTNode::pos, Stmt::Print(), SourcePos::Print(), and stmts.
TypeCheck()
Stmt * DefaultStmt::TypeCheck () virtual
Type checking should be performed by the node when this method is called. In the event of an error, a NULL value may be returned. As with ASTNode::Optimize(), the caller should store the returned pointer in place of the original ASTNode *.
Implements Stmt.
Definition at line 2185 of file stmt.cpp.
Member Data Documentation
stmts
Stmt* DefaultStmt::stmts
Definition at line 373 of file stmt.h.
Referenced by DefaultStmt(), EmitCode(), Print(), and WalkAST().
The documentation for this class was generated from the following files:
stmt.h
stmt.cpp