Intel® Implicit SPMD Program Compiler (Intel® ISPC): ImproveMemoryOpsPass Class Reference
ImproveMemoryOpsPass Class Reference
Public Member Functions
ImproveMemoryOpsPass ()
llvm::StringRef getPassName () const
bool runOnBasicBlock (llvm::BasicBlock &BB)
bool runOnFunction (llvm::Function &F)
Static Public Attributes
static char ID = 0
Detailed Description
When the front-end emits gathers and scatters, it generates an array of vector-width pointers to represent the set of addresses to read from or write to. This optimization detects cases when the base pointer is a uniform pointer or when the indexing is into an array that can be converted into scatters/gathers from a single base pointer and an array of offsets.
See for example the comments discussing the __pseudo_gather functions in builtins.cpp for more information about this.
Definition at line 1128 of file opt.cpp.
Constructor & Destructor Documentation
ImproveMemoryOpsPass()
ImproveMemoryOpsPass::ImproveMemoryOpsPass () inline
Definition at line 1131 of file opt.cpp.
Member Function Documentation
getPassName()
llvm::StringRef ImproveMemoryOpsPass::getPassName () const inline
Definition at line 1133 of file opt.cpp.
References ID.
runOnBasicBlock()
bool ImproveMemoryOpsPass::runOnBasicBlock (llvm::BasicBlock & BB)
Definition at line 2756 of file opt.cpp.
References DEBUG_END_PASS, DEBUG_START_PASS, lGSBaseOffsetsGetMoreConst(), lGSToGSBaseOffsets(), lGSToLoadStore(), lImproveMaskedLoad(), and lImproveMaskedStore().
runOnFunction()
bool ImproveMemoryOpsPass::runOnFunction (llvm::Function & F)
Definition at line 2797 of file opt.cpp.
Member Data Documentation
ID
char ImproveMemoryOpsPass::ID = 0 static
Definition at line 1130 of file opt.cpp.
Referenced by getPassName().
The documentation for this class was generated from the following file:
opt.cpp