Intel SPMD Program Compiler: DeleteStmt Class Reference
DeleteStmt Class Reference
#include <stmt.h>
Public Member Functions
DeleteStmt (Expr *e, SourcePos p)
void EmitCode (FunctionEmitContext *ctx) const
void Print (int indent) const
Stmt * TypeCheck ()
int EstimateCost () const
Public Member Functions inherited from Stmt
Stmt (SourcePos p)
virtual Stmt * Optimize ()
Public Member Functions inherited from ASTNode
ASTNode (SourcePos p)
virtual ~ASTNode ()
Public Attributes
Expr * expr
Detailed Description
Representation of a delete statement in the program.
Definition at line 482 of file stmt.h.
Constructor & Destructor Documentation
DeleteStmt::DeleteStmt (Expr * e, SourcePos p)
Definition at line 3209 of file stmt.cpp.
References expr.
Member Function Documentation
void DeleteStmt::EmitCode (FunctionEmitContext * ctx) const virtual
Emit LLVM IR for the statement, using the FunctionEmitContext to create the necessary instructions.
Implements Stmt.
Definition at line 3216 of file stmt.cpp.
References AssertPos, FunctionEmitContext::BitCastInst(), FunctionEmitContext::CallInst(), Module::errorCount, expr, g, FunctionEmitContext::GetCurrentBasicBlock(), Expr::GetType(), Expr::GetValue(), LLVMTypes::Int64VectorType, Target::is32Bit(), Type::IsUniformType(), m, Module::module, ASTNode::pos, Globals::target, LLVMTypes::VoidPointerType, and FunctionEmitContext::ZExtInst().
int DeleteStmt::EstimateCost () const virtual
Estimate the execution cost of the node (not including the cost of the children. The value returned should be based on the COST_* enumerant values defined in ispc.h.
Implements ASTNode.
Definition at line 3294 of file stmt.cpp.
References COST_DELETE.
void DeleteStmt::Print (int indent) const virtual
Print a representation of the statement (and any children AST nodes) to standard output. This method is used for debuggins.
Implements Stmt.
Definition at line 3272 of file stmt.cpp.
Stmt * DeleteStmt::TypeCheck () virtual
Type checking should be performed by the node when this method is called. In the event of an error, a NULL value may be returned. As with ASTNode::Optimize(), the caller should store the returned pointer in place of the original ASTNode *.
Implements Stmt.
Definition at line 3278 of file stmt.cpp.
References Error(), expr, Type::GetString(), Expr::GetType(), and ASTNode::pos.
Member Data Documentation
Expr* DeleteStmt::expr
Expression that gives the pointer value to be deleted.
Definition at line 493 of file stmt.h.
Referenced by DeleteStmt(), EmitCode(), TypeCheck(), and WalkAST().
The documentation for this class was generated from the following files:
stmt.h
stmt.cpp