Intel SPMD Program Compiler: PointerType Class Reference
PointerType Class Reference
Type implementation for pointers to other types.
#include <type.h>
Public Member Functions
PointerType (const Type *t, Variability v, bool isConst, bool isSlice=false, bool frozen=false)
Variability GetVariability () const
bool IsBoolType () const
bool IsFloatType () const
bool IsIntType () const
bool IsUnsignedType () const
bool IsConstType () const
bool IsSlice () const
bool IsFrozenSlice () const
const PointerType * GetAsSlice () const
const PointerType * GetAsNonSlice () const
const PointerType * GetAsFrozenSlice () const
const Type * GetBaseType () const
const PointerType * GetAsVaryingType () const
const PointerType * GetAsUniformType () const
const PointerType * GetAsUnboundVariabilityType () const
const PointerType * GetAsSOAType (int width) const
const PointerType * ResolveUnboundVariability (Variability v) const
const PointerType * GetAsConstType () const
const PointerType * GetAsNonConstType () const
std::string GetString () const
std::string Mangle () const
std::string GetCDeclaration (const std::string &name) const
llvm::Type * LLVMType (llvm::LLVMContext *ctx) const
llvm::DIType GetDIType (llvm::DIDescriptor scope) const
Public Member Functions inherited from Type
bool IsPointerType () const
bool IsArrayType () const
bool IsReferenceType () const
bool IsVoidType () const
bool IsNumericType () const
bool IsUniformType () const
bool IsVaryingType () const
bool IsSOAType () const
int GetSOAWidth () const
bool HasUnboundVariability () const
virtual const Type * GetAsUnsignedType () const
virtual const Type * GetReferenceTarget () const
Static Public Member Functions
static PointerType * GetUniform (const Type *t, bool isSlice=false)
static PointerType * GetVarying (const Type *t)
static bool IsVoidPointer (const Type *t)
Static Public Member Functions inherited from Type
static bool Equal (const Type *a, const Type *b)
static bool EqualIgnoringConst (const Type *a, const Type *b)
static const Type * MoreGeneralType (const Type *type0, const Type *type1, SourcePos pos, const char *reason, bool forceVarying=false, int vecSize=0)
static bool IsBasicType (const Type *type)
Static Public Attributes
static PointerType * Void = new PointerType(AtomicType::Void, Variability(Variability::Uniform), false)
Private Attributes
const Variability variability
const bool isConst
const bool isSlice
const bool isFrozen
const Type * baseType
Additional Inherited Members
Public Attributes inherited from Type
const TypeId typeId
Protected Member Functions inherited from Type
Type (TypeId id)
Detailed Description
Type implementation for pointers to other types.
Pointers can have two additional properties beyond their variability and the type of object that they are pointing to. Both of these properties are used for internal bookkeeping and aren't directly accessible from the language.
Slice: pointers that point to data with SOA layout have this property–it indicates that the pointer has two components, where the first (major) component is a regular pointer that points to an instance of the soa<> type being indexed, and where the second (minor) component is an integer that indicates which of the soa slices in that instance the pointer points to.
Frozen: only slice pointers may have this property–it indicates that any further indexing calculations should only be applied to the major pointer, and the value of the minor offset should be left unchanged. Pointers to lvalues from structure member access have the frozen property; see discussion in comments in the StructMemberExpr class.
Definition at line 430 of file type.h.
Constructor & Destructor Documentation
PointerType()
PointerType::PointerType (const Type * t, Variability v, bool isConst, bool isSlice = false, bool frozen = false)
Definition at line 894 of file type.cpp.
References baseType.
Referenced by GetAsConstType(), GetAsFrozenSlice(), GetAsNonConstType(), GetAsNonSlice(), GetAsSlice(), GetAsSOAType(), GetAsUnboundVariabilityType(), GetAsUniformType(), GetAsVaryingType(), GetUniform(), GetVarying(), and ResolveUnboundVariability().
Member Function Documentation
GetAsConstType()
const PointerType * PointerType::GetAsConstType () const virtual
Get a const version of this type. If it's already const, then the old Type pointer is returned.
Implements Type.
Definition at line 983 of file type.cpp.
References baseType, isConst, isSlice, PointerType(), and variability.
GetAsFrozenSlice()
const PointerType * PointerType::GetAsFrozenSlice () const
Definition at line 965 of file type.cpp.
References baseType, isConst, isFrozen, PointerType(), and variability.
Referenced by StructMemberExpr::GetLValueType(), and VectorMemberExpr::GetLValueType().
GetAsNonConstType()
const PointerType * PointerType::GetAsNonConstType () const virtual
Get a non-const version of this type. If it's already not const, then the old Type pointer is returned.
Implements Type.
Definition at line 990 of file type.cpp.
References baseType, isConst, isSlice, PointerType(), and variability.
GetAsNonSlice()
const PointerType * PointerType::GetAsNonSlice () const
Definition at line 959 of file type.cpp.
References baseType, isConst, isSlice, PointerType(), and variability.
Referenced by FunctionEmitContext::GetElementPtrInst(), lEmitBinaryPointerArith(), LLVMType(), and FunctionEmitContext::maskedStore().
GetAsSlice()
const PointerType * PointerType::GetAsSlice () const
Definition at line 953 of file type.cpp.
References baseType, isConst, isSlice, PointerType(), and variability.
Referenced by IndexExpr::GetLValueType(), lConvertPtrToSliceIfNeeded(), and FunctionEmitContext::scatter().
GetAsSOAType()
const PointerType * PointerType::GetAsSOAType (int width) const virtual
Implements Type.
Definition at line 946 of file type.cpp.
References baseType, Type::GetSOAWidth(), isConst, isFrozen, isSlice, PointerType(), and Variability::SOA.
GetAsUnboundVariabilityType()
const PointerType * PointerType::GetAsUnboundVariabilityType () const virtual
Get an instance of the type with unbound variability.
Implements Type.
Definition at line 939 of file type.cpp.
References baseType, isConst, isFrozen, isSlice, PointerType(), Variability::Unbound, and variability.
GetAsUniformType()
const PointerType * PointerType::GetAsUniformType () const virtual
Return a "uniform" instance of this type. If the type is already uniform, its "this" pointer will be returned.
Implements Type.
Definition at line 932 of file type.cpp.
References baseType, isConst, isFrozen, isSlice, PointerType(), Variability::Uniform, and variability.
Referenced by GetDIType(), and LLVMType().
GetAsVaryingType()
const PointerType * PointerType::GetAsVaryingType () const virtual
Return a "varying" instance of this type. If the type is already varying, its "this" pointer will be returned.
Implements Type.
Definition at line 925 of file type.cpp.
References baseType, isConst, isFrozen, isSlice, PointerType(), variability, and Variability::Varying.
GetBaseType()
const Type * PointerType::GetBaseType () const virtual
Returns the basic root type of the given type. For example, for an array or short-vector, this returns the element type. For a struct or atomic type, it returns itself.
Implements Type.
Definition at line 923 of file type.cpp.
References baseType.
Referenced by FunctionEmitContext::AddElementOffset(), MemberExpr::create(), FunctionEmitContext::gather(), FunctionType::GetCDeclaration(), FunctionType::GetCDeclarationForDispatch(), AddressOfExpr::GetConstant(), FunctionEmitContext::GetElementPtrInst(), IndexExpr::GetLValueType(), StructMemberExpr::getStructType(), IndexExpr::GetType(), lAddVaryingOffsetsIfNeeded(), lCheckAllOffSafety(), lCheckTypeEquality(), lConvertPtrToSliceIfNeeded(), lDeconstifyType(), lEmitBinaryPointerArith(), FunctionEmitContext::LoadInst(), FunctionEmitContext::loadUniformFromSOA(), lVaryingStructHasUniformMember(), FunctionEmitContext::scatter(), FunctionEmitContext::StoreInst(), FunctionEmitContext::storeUniformToSOA(), UnaryExpr::TypeCheck(), BinaryExpr::TypeCheck(), FunctionCallExpr::TypeCheck(), and VectorMemberExpr::VectorMemberExpr().
GetCDeclaration()
std::string PointerType::GetCDeclaration (const std::string & name) const virtual
Returns a string that is the declaration of the same type in C syntax.
Implements Type.
Definition at line 1036 of file type.cpp.
References Assert, baseType, Module::errorCount, g, Type::GetCDeclaration(), Target::getVectorWidth(), Type::IsBasicType(), isConst, isSlice, Type::IsVaryingType(), m, Variability::SOA, Variability::soaWidth, Globals::target, Variability::Unbound, and variability.
Referenced by FunctionType::GetCDeclarationForDispatch().
GetDIType()
llvm::DIType PointerType::GetDIType (llvm::DIDescriptor scope) const virtual
Returns the DIType (LLVM's debugging information structure), corresponding to this type.
Implements Type.
Definition at line 1141 of file type.cpp.
References Assert, baseType, Module::diBuilder, Module::errorCount, FATAL, g, GetAsUniformType(), Type::GetDIType(), ArrayType::GetDIType(), Target::getVectorWidth(), Target::is32Bit(), lCreateDIArray(), m, Variability::SOA, Variability::soaWidth, Globals::target, Variability::type, Variability::Uniform, variability, and Variability::Varying.
GetString()
std::string PointerType::GetString () const virtual
Returns a text representation of the type (for example, for use in warning and error messages).
Implements Type.
Definition at line 997 of file type.cpp.
References Assert, baseType, Module::errorCount, Variability::GetString(), Type::GetString(), isConst, isFrozen, isSlice, m, and variability.
Referenced by FunctionType::GetCDeclarationForDispatch(), and BinaryExpr::TypeCheck().
GetUniform()
PointerType * PointerType::GetUniform (const Type * t, bool isSlice = false) static
Helper method to return a uniform pointer to the given type.
Definition at line 899 of file type.cpp.
References PointerType(), and Variability::Uniform.
Referenced by FunctionEmitContext::AddElementOffset(), FunctionEmitContext::CallInst(), FunctionEmitContext::CurrentLanesReturned(), ForeachUniqueStmt::EmitCode(), FunctionEmitContext::GetElementPtrInst(), IndexExpr::GetLValue(), IndexExpr::GetLValueType(), ReferenceExpr::GetLValueType(), AddressOfExpr::GetLValueType(), SymbolExpr::GetLValueType(), StructMemberExpr::GetLValueType(), VectorMemberExpr::GetLValueType(), AddressOfExpr::GetType(), NewExpr::GetType(), IndexExpr::GetValue(), MemberExpr::GetValue(), VectorMemberExpr::GetValue(), Declarator::InitFromType(), InitSymbol(), lDoTypeConv(), lEmitVaryingSelect(), lFinalSliceOffset(), lLLVMTypeToISPCType(), FunctionEmitContext::LoadInst(), FunctionEmitContext::maskedStore(), Type::MoreGeneralType(), FunctionEmitContext::StoreInst(), and SelectExpr::TypeCheck().
GetVariability()
Variability PointerType::GetVariability () const virtual
Returns the variability of the type.
Implements Type.
Definition at line 911 of file type.cpp.
References variability.
Referenced by FunctionEmitContext::AddElementOffset(), and lDeconstifyType().
GetVarying()
PointerType * PointerType::GetVarying (const Type * t) static
Helper method to return a varying pointer to the given type.
Definition at line 903 of file type.cpp.
References PointerType(), and Variability::Varying.
Referenced by FunctionEmitContext::GetElementPtrInst(), IndexExpr::GetLValueType(), StructMemberExpr::GetLValueType(), VectorMemberExpr::GetLValueType(), NewExpr::GetType(), VectorMemberExpr::GetValue(), lAddVaryingOffsetsIfNeeded(), lFinalSliceOffset(), and FunctionEmitContext::scatter().
IsBoolType()
bool PointerType::IsBoolType () const virtual
Returns true if the underlying type is boolean. In other words, this is true for individual bools and for short-vectors with underlying bool type, but not for arrays of bools.
Implements Type.
Definition at line 913 of file type.cpp.
IsConstType()
bool PointerType::IsConstType () const virtual
Returns true if this type is 'const'-qualified.
Implements Type.
Definition at line 921 of file type.cpp.
References isConst.
Referenced by FunctionEmitContext::AddElementOffset().
IsFloatType()
bool PointerType::IsFloatType () const virtual
Returns true if the underlying type is float or double. In other words, this is true for individual floats/doubles and for short-vectors of them, but not for arrays of them.
Implements Type.
Definition at line 915 of file type.cpp.
IsFrozenSlice()
bool PointerType::IsFrozenSlice () const inline
Definition at line 451 of file type.h.
References Variability::GetString().
Referenced by FunctionEmitContext::GetElementPtrInst(), and lCheckTypeEquality().
IsIntType()
bool PointerType::IsIntType () const virtual
Returns true if the underlying type is an integer type. In other words, this is true for individual integers and for short-vectors of integer types, but not for arrays of integer types.
Implements Type.
Definition at line 917 of file type.cpp.
Referenced by TypeCastExpr::TypeCheck().
IsSlice()
bool PointerType::IsSlice () const inline
Definition at line 450 of file type.h.
Referenced by FunctionEmitContext::AddElementOffset(), FunctionEmitContext::gather(), FunctionEmitContext::GetElementPtrInst(), TypeCastExpr::GetValue(), lAddVaryingOffsetsIfNeeded(), lCheckTypeEquality(), lConvertPtrToSliceIfNeeded(), lEmitBinaryPointerArith(), FunctionEmitContext::LoadInst(), FunctionEmitContext::maskedStore(), FunctionEmitContext::scatter(), and FunctionEmitContext::StoreInst().
IsUnsignedType()
bool PointerType::IsUnsignedType () const virtual
Returns true if the underlying type is unsigned. In other words, this is true for unsigned integers and short vectors of unsigned integer types.
Implements Type.
Definition at line 919 of file type.cpp.
IsVoidPointer()
bool PointerType::IsVoidPointer (const Type * t) static
Returns true if the given type is a void * type.
Definition at line 907 of file type.cpp.
References Type::EqualIgnoringConst(), Type::GetAsUniformType(), and Void.
Referenced by TypeCastExpr::GetValue(), lDoTypeConv(), Type::MoreGeneralType(), UnaryExpr::TypeCheck(), BinaryExpr::TypeCheck(), and AssignExpr::TypeCheck().
LLVMType()
llvm::Type * PointerType::LLVMType (llvm::LLVMContext * ctx) const virtual
Returns the LLVM type corresponding to this ispc type
Implements Type.
Definition at line 1083 of file type.cpp.
References Assert, baseType, Globals::ctx, Module::errorCount, FATAL, g, GetAsNonSlice(), GetAsUniformType(), LLVMTypes::Int32Type, LLVMTypes::Int32VectorType, isSlice, Type::IsVoidType(), FunctionType::LLVMFunctionType(), Type::LLVMType(), LLVMType(), ArrayType::LLVMType(), m, Variability::SOA, Variability::soaWidth, Variability::type, Variability::Uniform, variability, Variability::Varying, LLVMTypes::VoidPointerType, and LLVMTypes::VoidPointerVectorType.
Referenced by lConvertToSlicePointer(), lEmitVaryingSelect(), and LLVMType().
Mangle()
std::string PointerType::Mangle () const virtual
Returns a string that represents the mangled type (for use in mangling function symbol names for function overloading). The various Types implementations of this method should collectively ensure that all of them use mangling schemes that are guaranteed not to clash.
Implements Type.
Definition at line 1017 of file type.cpp.
References Assert, baseType, Module::errorCount, isFrozen, isSlice, m, Type::Mangle(), Variability::MangleString(), Variability::Unbound, and variability.
ResolveUnboundVariability()
const PointerType * PointerType::ResolveUnboundVariability (Variability v) const virtual
Implements Type.
Definition at line 971 of file type.cpp.
References Assert, baseType, Module::errorCount, isConst, isFrozen, isSlice, m, PointerType(), Type::ResolveUnboundVariability(), Variability::Unbound, Variability::Uniform, and variability.
Member Data Documentation
baseType
const Type* PointerType::baseType private
Definition at line 483 of file type.h.
Referenced by GetAsConstType(), GetAsFrozenSlice(), GetAsNonConstType(), GetAsNonSlice(), GetAsSlice(), GetAsSOAType(), GetAsUnboundVariabilityType(), GetAsUniformType(), GetAsVaryingType(), GetBaseType(), GetCDeclaration(), GetDIType(), GetString(), LLVMType(), Mangle(), PointerType(), and ResolveUnboundVariability().
isConst
const bool PointerType::isConst private
Definition at line 481 of file type.h.
Referenced by GetAsConstType(), GetAsFrozenSlice(), GetAsNonConstType(), GetAsNonSlice(), GetAsSlice(), GetAsSOAType(), GetAsUnboundVariabilityType(), GetAsUniformType(), GetAsVaryingType(), GetCDeclaration(), GetString(), IsConstType(), and ResolveUnboundVariability().
isFrozen
const bool PointerType::isFrozen private
Definition at line 482 of file type.h.
Referenced by GetAsFrozenSlice(), GetAsSOAType(), GetAsUnboundVariabilityType(), GetAsUniformType(), GetAsVaryingType(), GetString(), Mangle(), and ResolveUnboundVariability().
isSlice
const bool PointerType::isSlice private
Definition at line 482 of file type.h.
Referenced by GetAsConstType(), GetAsNonConstType(), GetAsNonSlice(), GetAsSlice(), GetAsSOAType(), GetAsUnboundVariabilityType(), GetAsUniformType(), GetAsVaryingType(), GetCDeclaration(), GetString(), LLVMType(), Mangle(), and ResolveUnboundVariability().
variability
const Variability PointerType::variability private
Definition at line 480 of file type.h.
Referenced by GetAsConstType(), GetAsFrozenSlice(), GetAsNonConstType(), GetAsNonSlice(), GetAsSlice(), GetAsUnboundVariabilityType(), GetAsUniformType(), GetAsVaryingType(), GetCDeclaration(), GetDIType(), GetString(), GetVariability(), LLVMType(), Mangle(), and ResolveUnboundVariability().
Void
PointerType * PointerType::Void = new PointerType(AtomicType::Void, Variability(Variability::Uniform), false) static
Definition at line 477 of file type.h.
Referenced by FunctionType::GetCDeclarationForDispatch(), EnumType::GetEnumerator(), NullPointerExpr::GetType(), IsVoidPointer(), and lDoTypeConv().
The documentation for this class was generated from the following files:
type.h
type.cpp