Intel® Implicit SPMD Program Compiler (Intel® ISPC): ReplaceStdlibShiftPass Class Reference
ReplaceStdlibShiftPass Class Reference
Public Member Functions
ReplaceStdlibShiftPass ()
llvm::StringRef getPassName () const
bool runOnBasicBlock (llvm::BasicBlock &BB)
bool runOnFunction (llvm::Function &F)
Static Public Attributes
static char ID = 0
Detailed Description
Definition at line 4780 of file opt.cpp.
Constructor & Destructor Documentation
ReplaceStdlibShiftPass()
ReplaceStdlibShiftPass::ReplaceStdlibShiftPass () inline
Definition at line 4783 of file opt.cpp.
Member Function Documentation
getPassName()
llvm::StringRef ReplaceStdlibShiftPass::getPassName () const inline
Definition at line 4785 of file opt.cpp.
References ID, PeepholePass::runOnBasicBlock(), and PeepholePass::runOnFunction().
runOnBasicBlock()
bool ReplaceStdlibShiftPass::runOnBasicBlock (llvm::BasicBlock & BB)
Definition at line 4800 of file opt.cpp.
References DEBUG_END_PASS, DEBUG_START_PASS, g, Target::getVectorWidth(), Opt::level, lGetIntValue(), LLVMInt32Vector(), m, Module::module, Globals::opt, PerformanceWarning(), and Globals::target.
runOnFunction()
bool ReplaceStdlibShiftPass::runOnFunction (llvm::Function & F)
Definition at line 4852 of file opt.cpp.
References PeepholePass::runOnBasicBlock().
Member Data Documentation
ID
char ReplaceStdlibShiftPass::ID = 0 static
Definition at line 4782 of file opt.cpp.
Referenced by getPassName().
The documentation for this class was generated from the following file:
opt.cpp