Intel SPMD Program Compiler: DetectGSBaseOffsetsPass Class Reference
DetectGSBaseOffsetsPass Class Reference
Public Member Functions
DetectGSBaseOffsetsPass ()
const char * getPassName () const
bool runOnBasicBlock (llvm::BasicBlock &BB)
Static Public Attributes
static char ID = 0
Detailed Description
When the front-end emits gathers and scatters, it generates an array of vector-width pointers to represent the set of addresses to read from or write to. This optimization detects cases when the base pointer is a uniform pointer or when the indexing is into an array that can be converted into scatters/gathers from a single base pointer and an array of offsets.
See for example the comments discussing the __pseudo_gather functions in builtins.cpp for more information about this.
Definition at line 1019 of file opt.cpp.
Constructor & Destructor Documentation
DetectGSBaseOffsetsPass::DetectGSBaseOffsetsPass () [inline]
Definition at line 1022 of file opt.cpp.
Member Function Documentation
const char* DetectGSBaseOffsetsPass::getPassName () const [inline]
Definition at line 1024 of file opt.cpp.
bool DetectGSBaseOffsetsPass::runOnBasicBlock (llvm::BasicBlock & BB)
Definition at line 1733 of file opt.cpp.
References Assert, GSInfo::baseOffsets32Func, GSInfo::baseOffsetsFunc, DEBUG_END_PASS, DEBUG_START_PASS, Opt::force32BitAddressing, GSInfo::func, g, GSInfo::isGather, lCallInst(), lCopyMetadata(), lExtractConstantOffset(), lExtractOffsetVector248Scale(), lGetBasePtrAndOffsets(), LLVMGetName(), LLVMIntAsType(), lOffsets32BitSafe(), NULL, Globals::opt, and LLVMTypes::VoidPointerType.
Member Data Documentation
char DetectGSBaseOffsetsPass::ID = 0 [static]
Definition at line 1021 of file opt.cpp.
The documentation for this class was generated from the following file:
opt.cpp