Intel SPMD Program Compiler: Declarator Class Reference
Declarator Class Reference
Representation of the declaration of a single variable.
#include <decl.h>
Public Member Functions
Declarator (DeclaratorKind dk, SourcePos p)
void InitFromDeclSpecs (DeclSpecs *ds)
const Type * GetType (DeclSpecs *ds) const
const Type * GetType (const Type *base, DeclSpecs *ds) const
Symbol * GetFunctionInfo (DeclSpecs *ds, std::vector< Symbol * > *args)
Symbol * GetSymbolForFunctionParameter (int paramNum) const
Symbol * GetSymbol () const
void Print (int indent) const
Public Attributes
const SourcePos pos
const DeclaratorKind kind
Declarator * child
int typeQualifiers
int arraySize
Symbol * sym
Expr * initExpr
std::vector< Declaration * > functionParams
Detailed Description
Representation of the declaration of a single variable.
In conjunction with an instance of the DeclSpecs, this gives us everything we need for a full variable declaration.
Definition at line 136 of file decl.h.
Constructor & Destructor Documentation
Declarator::Declarator (DeclaratorKind dk, SourcePos p)
Definition at line 216 of file decl.cpp.
References arraySize, child, initExpr, NULL, sym, and typeQualifiers.
Member Function Documentation
Symbol * Declarator::GetFunctionInfo (DeclSpecs * ds, std::vector< Symbol * > * args)
Returns the symbol corresponding to the function declared by this declarator and symbols for its arguments in *args.
Definition at line 298 of file decl.cpp.
References Assert, child, DK_FUNCTION, Module::errorCount, functionParams, GetSymbol(), GetSymbolForFunctionParameter(), GetType(), kind, SymbolTable::LookupFunction(), m, Symbol::name, NULL, Symbol::pos, pos, Type::ResolveUnboundVariability(), sym, Module::symbolTable, Symbol::type, and Variability::Varying.
Symbol * Declarator::GetSymbol () const
Returns the symbol associated with the declarator.
Definition at line 243 of file decl.cpp.
References child, NULL, and sym.
Referenced by Declaration::DeclareFunctions(), GetFunctionInfo(), GetStructTypesNamesPositions(), Declaration::GetVariableDeclarations(), InitFromDeclSpecs(), and Print().
Symbol * Declarator::GetSymbolForFunctionParameter (int paramNum) const
Definition at line 563 of file decl.cpp.
References Assert, functionParams, Type::GetBaseType(), NULL, pos, sym, and Symbol::type.
Referenced by GetFunctionInfo(), and GetType().
const Type * Declarator::GetType (DeclSpecs * ds) const
Get the actual type of the combination of Declarator and the given DeclSpecs. If an explicit base type is provided, the declarator is applied to that type; otherwise the base type from the DeclSpecs is used.
Definition at line 555 of file decl.cpp.
References DeclSpecs::GetBaseType(), and pos.
Referenced by GetFunctionInfo(), GetType(), and InitFromDeclSpecs().
const Type * Declarator::GetType (const Type * base, DeclSpecs * ds) const
Definition at line 345 of file decl.cpp.
References arraySize, Assert, child, Declaration::declarators, Declaration::declSpecs, DK_ARRAY, DK_BASE, DK_FUNCTION, DK_POINTER, DK_REFERENCE, Type::Equal(), Error(), Module::errorCount, FATAL, functionParams, ArrayType::GetElementCount(), ArrayType::GetElementType(), Type::GetString(), GetSymbolForFunctionParameter(), GetType(), PointerType::GetUniform(), initExpr, Type::IsSOAType(), kind, lGetStorageClassName(), m, Symbol::name, NULL, Optimize(), Symbol::pos, pos, Type::ResolveUnboundVariability(), SC_EXPORT, SC_EXTERN_C, SC_NONE, DeclSpecs::storageClass, sym, Symbol::type, TYPEQUAL_CONST, TYPEQUAL_TASK, TYPEQUAL_UNIFORM, TYPEQUAL_VARYING, DeclSpecs::typeQualifiers, typeQualifiers, Variability::Unbound, Variability::Uniform, Variability::Varying, and AtomicType::Void.
void Declarator::InitFromDeclSpecs (DeclSpecs * ds)
Once a DeclSpecs instance is available, this method completes the initialization of the Symbol, setting its Type accordingly.
Definition at line 227 of file decl.cpp.
References Assert, Module::errorCount, GetSymbol(), GetType(), m, NULL, DeclSpecs::storageClass, Symbol::storageClass, sym, and Symbol::type.
Referenced by Declaration::Declaration(), and GetStructTypesNamesPositions().
void Declarator::Print (int indent) const
Definition at line 254 of file decl.cpp.
References arraySize, child, DK_ARRAY, DK_BASE, DK_FUNCTION, DK_POINTER, DK_REFERENCE, FATAL, functionParams, GetSymbol(), initExpr, kind, lPrintTypeQualifiers(), Symbol::name, NULL, pos, Expr::Print(), SourcePos::Print(), Print(), sym, and typeQualifiers.
Referenced by Print().
Member Data Documentation
int Declarator::arraySize
For array declarators, this gives the declared size of the array. Unsized arrays have arraySize == 0.
Definition at line 182 of file decl.h.
Referenced by Declarator(), GetType(), and Print().
Declarator* Declarator::child
Child pointer if needed; this can only be non-NULL if the declarator's kind isn't DK_BASE.
Definition at line 175 of file decl.h.
Referenced by Declarator(), GetFunctionInfo(), GetSymbol(), GetType(), and Print().
std::vector<Declaration *> Declarator::functionParams
For function declarations, this holds the Declaration *s for the funciton's parameters.
Definition at line 192 of file decl.h.
Referenced by GetFunctionInfo(), GetSymbolForFunctionParameter(), GetType(), and Print().
Expr* Declarator::initExpr
Initialization expression for the variable. May be NULL.
Definition at line 188 of file decl.h.
Referenced by Declarator(), GetType(), Declaration::GetVariableDeclarations(), and Print().
const DeclaratorKind Declarator::kind
The kind of this declarator; complex declarations are assembled as a hierarchy of Declarators. (For example, a pointer to an int would have a root declarator with kind DK_POINTER and with the Declarator::child member pointing to a DK_BASE declarator for the int).
Definition at line 171 of file decl.h.
Referenced by GetFunctionInfo(), GetType(), and Print().
const SourcePos Declarator::pos
Position of the declarator in the source program.
Definition at line 164 of file decl.h.
Referenced by GetFunctionInfo(), GetStructTypesNamesPositions(), GetSymbolForFunctionParameter(), GetType(), and Print().
Symbol* Declarator::sym
Symbol associated with the declarator.
Definition at line 185 of file decl.h.
Referenced by Declarator(), GetFunctionInfo(), GetSymbol(), GetSymbolForFunctionParameter(), GetType(), InitFromDeclSpecs(), and Print().
int Declarator::typeQualifiers
Type qualifiers provided with the declarator.
Definition at line 178 of file decl.h.
Referenced by Declarator(), GetType(), and Print().
The documentation for this class was generated from the following files:
decl.h
decl.cpp