Intel SPMD Program Compiler: Target Class Reference
Target Class Reference
Structure that defines a compilation target.
#include <ispc.h>
Public Types
enum ISA {
SSE2 = 0, SSE4 = 1, AVX = 2, AVX11 = 3,
AVX2 = 4, KNL_AVX512 = 5, SKX_AVX512 = 6, GENERIC = 7,
NUM_ISAS
}
Public Member Functions
Target (const char *arch, const char *cpu, const char *isa, bool pic, bool printTarget, std::string genenricAsSmth="")
std::string GetTripleString () const
llvm::TargetMachine * GetTargetMachine () const
const char * GetISAString () const
const char * GetISATargetString () const
llvm::Value * SizeOf (llvm::Type *type, llvm::BasicBlock *insertAtEnd)
llvm::Value * StructOffset (llvm::Type *type, int element, llvm::BasicBlock *insertAtEnd)
void markFuncWithTargetAttr (llvm::Function *func)
const llvm::Target * getTarget () const
const llvm::DataLayout * getDataLayout () const
bool isValid () const
ISA getISA () const
std::string getTreatGenericAsSmth () const
std::string getArch () const
bool is32Bit () const
std::string getCPU () const
int getNativeVectorWidth () const
int getNativeVectorAlignment () const
int getDataTypeWidth () const
int getVectorWidth () const
bool getGeneratePIC () const
bool getMaskingIsFree () const
int getMaskBitCount () const
bool hasHalf () const
bool hasRand () const
bool hasGather () const
bool hasScatter () const
bool hasTranscendentals () const
bool hasTrigonometry () const
bool hasRsqrtd () const
bool hasRcpd () const
bool hasVecPrefetch () const
Static Public Member Functions
static const char * SupportedTargets ()
static std::string SupportedCPUs ()
static const char * SupportedArchs ()
static const char * ISAToString (Target::ISA isa)
static const char * ISAToTargetString (Target::ISA isa)
Private Attributes
const llvm::Target * m_target
llvm::TargetMachine * m_targetMachine
llvm::DataLayout * m_dataLayout
bool m_valid
ISA m_isa
std::string m_treatGenericAsSmth
std::string m_arch
bool m_is32Bit
std::string m_cpu
std::string m_attributes
std::vector< std::pair< std::string, std::string > > m_funcAttributes
int m_nativeVectorWidth
int m_nativeVectorAlignment
int m_dataTypeWidth
int m_vectorWidth
bool m_generatePIC
bool m_maskingIsFree
int m_maskBitCount
bool m_hasHalf
bool m_hasRand
bool m_hasGather
bool m_hasScatter
bool m_hasTranscendentals
bool m_hasTrigonometry
bool m_hasRsqrtd
bool m_hasRcpd
bool m_hasVecPrefetch
Detailed Description
Structure that defines a compilation target.
This structure defines a compilation target for the ispc compiler.
Definition at line 169 of file ispc.h.
Member Enumeration Documentation
ISA
enum Target::ISA
Enumerator giving the instruction sets that the compiler can target. These should be ordered from "worse" to "better" in that if a processor supports multiple target ISAs, then the most flexible/performant of them will apear last in the enumerant. Note also that __best_available_isa() needs to be updated if ISAs are added or the enumerant values are reordered.
Enumerator
SSE2
SSE4
AVX
AVX11
AVX2
KNL_AVX512
SKX_AVX512
GENERIC
NUM_ISAS
Definition at line 177 of file ispc.h.
Constructor & Destructor Documentation
Target()
Target::Target (const char * arch, const char * cpu, const char * isa, bool pic, bool printTarget, std::string genenricAsSmth = "")
Initializes the given Target pointer for a target of the given name, if the name is a known target. Returns true if the target was initialized and false if the name is unknown.
Definition at line 458 of file ispc.cpp.
References Assert, AVX, AVX11, AVX2, AllCPUs::BackwardCompatible(), Globals::codegenOptLevel, CPU_Broadwell, CPU_Core2, CPU_Generic, CPU_Haswell, CPU_IvyBridge, CPU_Nehalem, CPU_None, CPU_Penryn, CPU_SandyBridge, CPU_Silvermont, CPU_x86_64, Globals::ctx, Opt::disableFMA, Error(), g, GENERIC, getDataLayout(), AllCPUs::GetDefaultNameFromType(), GetTripleString(), AllCPUs::GetTypeFromName(), AllCPUs::HumanReadableListOfNames(), ISPC_MAX_NVEC, KNL_AVX512, lGetSystemISA(), m_arch, m_attributes, m_cpu, m_dataLayout, m_dataTypeWidth, m_funcAttributes, m_generatePIC, m_hasGather, m_hasHalf, m_hasRand, m_hasRcpd, m_hasRsqrtd, m_hasScatter, m_hasTranscendentals, m_hasTrigonometry, m_hasVecPrefetch, m_is32Bit, m_isa, m_maskBitCount, m_maskingIsFree, m_nativeVectorAlignment, m_nativeVectorWidth, m_target, m_targetMachine, m_treatGenericAsSmth, m_valid, m_vectorWidth, Globals::NoOmitFramePointer, Globals::opt, SKX_AVX512, SSE2, SSE4, SupportedTargets(), and Warning().
Member Function Documentation
getArch()
std::string Target::getArch () const inline
Definition at line 260 of file ispc.h.
References m_arch.
getCPU()
std::string Target::getCPU () const inline
Definition at line 264 of file ispc.h.
References m_cpu.
getDataLayout()
const llvm::DataLayout* Target::getDataLayout () const inline
Definition at line 251 of file ispc.h.
References m_dataLayout.
Referenced by VectorType::GetDIType(), lEmitStructDecl(), lEmitVectorTypedefs(), lInitDispatchModule(), Module::Module(), Optimize(), SizeOf(), StructOffset(), Target(), and Module::writeObjectFileOrAssembly().
getDataTypeWidth()
int Target::getDataTypeWidth () const inline
Definition at line 270 of file ispc.h.
References m_dataTypeWidth.
Referenced by DefineStdlib(), and VectorType::getVectorMemoryCount().
getGeneratePIC()
bool Target::getGeneratePIC () const inline
Definition at line 274 of file ispc.h.
References m_generatePIC.
getISA()
ISA Target::getISA () const inline
Definition at line 256 of file ispc.h.
References m_isa.
Referenced by AddBitcodeToModule(), Module::AddFunctionDeclaration(), Module::AddGlobalVariable(), Module::CompileAndOutput(), DefineStdlib(), Function::emitCode(), DeclStmt::EmitCode(), IfStmt::EmitCode(), ForeachStmt::EmitCode(), ForeachActiveStmt::EmitCode(), ForeachUniqueStmt::EmitCode(), PrintStmt::EmitCode(), Module::execPreprocessor(), Function::Function(), Function::GenerateIR(), DeclSpecs::GetBaseType(), FunctionEmitContext::LaneMask(), FunctionEmitContext::LaunchInst(), lGetExportedFunctions(), FunctionType::LLVMFunctionType(), lTypeConvAtomic(), lUpdateVaryingCounter(), FunctionEmitContext::MasksAllEqual(), Optimize(), FixBooleanSelectPass::runOnFunction(), FunctionEmitContext::SyncInst(), SizeOfExpr::TypeCheck(), NewExpr::TypeCheck(), Module::writeBitcode(), and Module::writeOutput().
GetISAString()
const char * Target::GetISAString () const
Returns a string like "avx" encoding the target. Good for mangling.
Definition at line 1253 of file ispc.cpp.
References ISAToString(), and m_isa.
Referenced by Module::AddFunctionDeclaration(), Module::CompileAndOutput(), Module::execPreprocessor(), FunctionEmitContext::FunctionEmitContext(), and Function::GenerateIR().
GetISATargetString()
const char * Target::GetISATargetString () const
Returns a string like "avx1.1-i32x8" encoding the target. This may be used for Target initialization.
Definition at line 1298 of file ispc.cpp.
References ISAToString(), and m_isa.
getMaskBitCount()
int Target::getMaskBitCount () const inline
Definition at line 278 of file ispc.h.
References m_maskBitCount.
Referenced by FunctionEmitContext::All(), FunctionEmitContext::Any(), DefineStdlib(), FunctionEmitContext::I1VecToBoolVec(), InitLLVMUtil(), FunctionEmitContext::LaneMask(), lCreateISPCSymbol(), FunctionEmitContext::LoadInst(), and FunctionEmitContext::None().
getMaskingIsFree()
bool Target::getMaskingIsFree () const inline
Definition at line 276 of file ispc.h.
References m_maskingIsFree.
Referenced by Function::emitCode().
getNativeVectorAlignment()
int Target::getNativeVectorAlignment () const inline
Definition at line 268 of file ispc.h.
References m_nativeVectorAlignment.
Referenced by FunctionEmitContext::AllocaInst(), FunctionEmitContext::FunctionEmitContext(), lEmitLoads(), lImproveMaskedLoad(), lImproveMaskedStore(), FunctionEmitContext::LoadInst(), IntrinsicsOpt::runOnBasicBlock(), and FunctionEmitContext::StoreInst().
getNativeVectorWidth()
int Target::getNativeVectorWidth () const inline
Definition at line 266 of file ispc.h.
References m_nativeVectorWidth.
Referenced by FunctionEmitContext::LaunchInst().
getTarget()
const llvm::Target* Target::getTarget () const inline
Definition at line 247 of file ispc.h.
References m_target.
GetTargetMachine()
llvm::TargetMachine* Target::GetTargetMachine () const inline
Returns the LLVM TargetMachine object corresponding to this target.
Definition at line 221 of file ispc.h.
References m_targetMachine.
Referenced by Module::CompileAndOutput(), lGetMask(), Optimize(), and Module::writeObjectFileOrAssembly().
getTreatGenericAsSmth()
std::string Target::getTreatGenericAsSmth () const inline
Definition at line 258 of file ispc.h.
References m_treatGenericAsSmth.
Referenced by Module::AddFunctionDeclaration(), Module::CompileAndOutput(), Function::GenerateIR(), and lCreateDispatchFunction().
GetTripleString()
std::string Target::GetTripleString () const
Returns a triple string specifying the target architecture, vendor, and environment.
Definition at line 1179 of file ispc.cpp.
References m_arch.
Referenced by lInitDispatchModule(), Module::Module(), and Target().
getVectorWidth()
int Target::getVectorWidth () const inline
Definition at line 272 of file ispc.h.
References m_vectorWidth.
Referenced by ConstExpr::Count(), DefineStdlib(), ForeachStmt::EmitCode(), PrintStmt::EmitCode(), DeclSpecs::GetBaseType(), EnumType::GetCDeclaration(), PointerType::GetCDeclaration(), ArrayType::GetCDeclaration(), AtomicType::GetDIType(), EnumType::GetDIType(), PointerType::GetDIType(), NewExpr::GetValue(), InitLLVMUtil(), lArrayVectorWidth(), lAssembleResultVectors(), lConvert(), lConvertPointerConstant(), lDefineProgramIndex(), lEmitStructDecl(), lExtractConstOffsets(), lGetBasePointer(), lGetMaskStatus(), lGetMatchingBoolVectorType(), lGetOffsetScaleVec(), lGSToLoadStore(), lIsExactMultiple(), lIsSafeToBlend(), LLVMBoolVector(), LLVMDoubleVector(), LLVMFloatVector(), LLVMInt16Vector(), LLVMInt32Vector(), LLVMInt64Vector(), LLVMInt8Vector(), LLVMUInt16Vector(), LLVMUInt32Vector(), LLVMUInt64Vector(), LLVMUInt8Vector(), lMangleStructName(), lReplacePseudoGS(), lUpdateVaryingCounter(), Optimize(), FunctionEmitContext::ProgramIndexVector(), ReplaceStdlibShiftPass::runOnBasicBlock(), FunctionEmitContext::SmearUniform(), Module::writeDispatchHeader(), and Module::writeOutput().
hasGather()
bool Target::hasGather () const inline
Definition at line 284 of file ispc.h.
References m_hasGather.
Referenced by lGSBaseOffsetsGetMoreConst(), lGSToGSBaseOffsets(), and lGSToLoadStore().
hasHalf()
bool Target::hasHalf () const inline
Definition at line 280 of file ispc.h.
References m_hasHalf.
Referenced by DefineStdlib(), and Module::execPreprocessor().
hasRand()
bool Target::hasRand () const inline
Definition at line 282 of file ispc.h.
References m_hasRand.
Referenced by DefineStdlib(), and Module::execPreprocessor().
hasRcpd()
bool Target::hasRcpd () const inline
Definition at line 294 of file ispc.h.
References m_hasRcpd.
Referenced by DefineStdlib().
hasRsqrtd()
bool Target::hasRsqrtd () const inline
Definition at line 292 of file ispc.h.
References m_hasRsqrtd.
Referenced by DefineStdlib().
hasScatter()
bool Target::hasScatter () const inline
Definition at line 286 of file ispc.h.
References m_hasScatter.
Referenced by lGSBaseOffsetsGetMoreConst(), lGSToGSBaseOffsets(), and lGSToLoadStore().
hasTranscendentals()
bool Target::hasTranscendentals () const inline
Definition at line 288 of file ispc.h.
References m_hasTranscendentals.
Referenced by DefineStdlib(), and Module::execPreprocessor().
hasTrigonometry()
bool Target::hasTrigonometry () const inline
Definition at line 290 of file ispc.h.
References m_hasTrigonometry.
Referenced by DefineStdlib().
hasVecPrefetch()
bool Target::hasVecPrefetch () const inline
Definition at line 296 of file ispc.h.
References m_hasVecPrefetch.
Referenced by lGSBaseOffsetsGetMoreConst(), and lGSToGSBaseOffsets().
is32Bit()
bool Target::is32Bit () const inline
Definition at line 262 of file ispc.h.
References m_is32Bit.
Referenced by FunctionEmitContext::AddElementOffset(), FunctionEmitContext::addVaryingOffsetsIfNeeded(), FunctionEmitContext::applyVaryingGEP(), DefineStdlib(), DeleteStmt::EmitCode(), Module::execPreprocessor(), FunctionEmitContext::gather(), PointerType::GetDIType(), BinaryExpr::GetType(), SizeOfExpr::GetType(), NewExpr::GetValue(), InitLLVMUtil(), lDeclareSizeAndPtrIntTypes(), lEmitBinaryPointerArith(), lGetBasePtrAndOffsets(), FunctionEmitContext::maskedStore(), FunctionEmitContext::scatter(), BinaryExpr::TypeCheck(), AssignExpr::TypeCheck(), IndexExpr::TypeCheck(), TypeCastExpr::TypeCheck(), and NewExpr::TypeCheck().
ISAToString()
const char * Target::ISAToString (Target::ISA isa) static
Convert ISA enum to string
Definition at line 1213 of file ispc.cpp.
References AVX, AVX11, AVX2, FATAL, GENERIC, KNL_AVX512, SKX_AVX512, SSE2, and SSE4.
Referenced by GetISAString(), and GetISATargetString().
ISAToTargetString()
const char * Target::ISAToTargetString (Target::ISA isa) static
Convert ISA enum to string
Definition at line 1258 of file ispc.cpp.
References AVX, AVX11, AVX2, FATAL, GENERIC, KNL_AVX512, SKX_AVX512, SSE2, and SSE4.
Referenced by Module::CompileAndOutput().
isValid()
bool Target::isValid () const inline
Reports if Target object has valid state.
Definition at line 254 of file ispc.h.
References m_valid.
Referenced by Module::CompileAndOutput().
markFuncWithTargetAttr()
void Target::markFuncWithTargetAttr (llvm::Function * func)
Mark LLVM function with target specific attribute, if required.
Definition at line 1387 of file ispc.cpp.
Referenced by Module::AddFunctionDeclaration(), Module::CompileFile(), Function::emitCode(), and Function::GenerateIR().
SizeOf()
llvm::Value * Target::SizeOf (llvm::Type * type, llvm::BasicBlock * insertAtEnd)
Returns the size of the given type
Definition at line 1328 of file ispc.cpp.
References Opt::force32BitAddressing, g, GENERIC, getDataLayout(), LLVMTypes::Int32Type, LLVMTypes::Int64Type, lGenericTypeLayoutIndeterminate(), LLVMInt32(), LLVMInt64(), m_is32Bit, m_isa, Globals::opt, and PTYPE.
Referenced by FunctionEmitContext::AddElementOffset(), FunctionEmitContext::addVaryingOffsetsIfNeeded(), FunctionEmitContext::applyVaryingGEP(), SizeOfExpr::GetValue(), NewExpr::GetValue(), InitSymbol(), FunctionEmitContext::LaunchInst(), and lEmitBinaryPointerArith().
StructOffset()
llvm::Value * Target::StructOffset (llvm::Type * type, int element, llvm::BasicBlock * insertAtEnd)
Given a structure type and an element number in the structure, returns a value corresponding to the number of bytes from the start of the structure where the element is located.
Definition at line 1353 of file ispc.cpp.
References Assert, Module::errorCount, Opt::force32BitAddressing, g, GENERIC, getDataLayout(), LLVMTypes::Int32Type, LLVMTypes::Int64Type, lGenericTypeLayoutIndeterminate(), LLVMInt32(), LLVMInt64(), m, m_is32Bit, m_isa, Globals::opt, and PTYPE.
Referenced by FunctionEmitContext::AddElementOffset().
SupportedArchs()
const char * Target::SupportedArchs () static
Returns a comma-delimited string giving the names of the currently supported architectures.
Definition at line 1144 of file ispc.cpp.
Referenced by usage().
SupportedCPUs()
std::string Target::SupportedCPUs () static
Returns a comma-delimited string giving the names of the currently supported CPUs.
Definition at line 1139 of file ispc.cpp.
References AllCPUs::HumanReadableListOfNames().
Referenced by usage().
SupportedTargets()
const char * Target::SupportedTargets () static
Returns a comma-delimited string giving the names of the currently supported compilation targets.
Definition at line 1152 of file ispc.cpp.
Referenced by Target(), and usage().
Member Data Documentation
m_arch
std::string Target::m_arch private
Target system architecture. (e.g. "x86-64", "x86").
Definition at line 324 of file ispc.h.
Referenced by getArch(), GetTripleString(), and Target().
m_attributes
std::string Target::m_attributes private
Target-specific attribute string to pass along to the LLVM backend
Definition at line 333 of file ispc.h.
Referenced by Target().
m_cpu
std::string Target::m_cpu private
Target CPU. (e.g. "corei7", "corei7-avx", ..)
Definition at line 330 of file ispc.h.
Referenced by getCPU(), and Target().
m_dataLayout
llvm::DataLayout* Target::m_dataLayout private
Definition at line 311 of file ispc.h.
Referenced by getDataLayout(), and Target().
m_dataTypeWidth
int Target::m_dataTypeWidth private
Data type width in bits. Typically it's 32, but could be 8, 16 or 64. For generic it's -1, which means undefined.
Definition at line 363 of file ispc.h.
Referenced by getDataTypeWidth(), and Target().
m_funcAttributes
std::vector<std::pair<std::string, std::string> > Target::m_funcAttributes private
Target-specific function attributes
Definition at line 336 of file ispc.h.
Referenced by Target().
m_generatePIC
bool Target::m_generatePIC private
Indicates whether position independent code should be generated.
Definition at line 371 of file ispc.h.
Referenced by getGeneratePIC(), and Target().
m_hasGather
bool Target::m_hasGather private
Indicates whether the target has a native gather instruction
Definition at line 392 of file ispc.h.
Referenced by hasGather(), and Target().
m_hasHalf
bool Target::m_hasHalf private
Indicates whether the target has native support for float/half conversions.
Definition at line 386 of file ispc.h.
Referenced by hasHalf(), and Target().
m_hasRand
bool Target::m_hasRand private
Indicates whether there is an ISA random number instruction.
Definition at line 389 of file ispc.h.
Referenced by hasRand(), and Target().
m_hasRcpd
bool Target::m_hasRcpd private
Indicates whether there is an ISA double precision rcp.
Definition at line 408 of file ispc.h.
Referenced by hasRcpd(), and Target().
m_hasRsqrtd
bool Target::m_hasRsqrtd private
Indicates whether there is an ISA double precision rsqrt.
Definition at line 405 of file ispc.h.
Referenced by hasRsqrtd(), and Target().
m_hasScatter
bool Target::m_hasScatter private
Indicates whether the target has a native scatter instruction
Definition at line 395 of file ispc.h.
Referenced by hasScatter(), and Target().
m_hasTranscendentals
bool Target::m_hasTranscendentals private
Indicates whether the target has support for transcendentals (beyond sqrt, which we assume that all of them handle).
Definition at line 399 of file ispc.h.
Referenced by hasTranscendentals(), and Target().
m_hasTrigonometry
bool Target::m_hasTrigonometry private
Indicates whether the target has ISA support for trigonometry
Definition at line 402 of file ispc.h.
Referenced by hasTrigonometry(), and Target().
m_hasVecPrefetch
bool Target::m_hasVecPrefetch private
Indicates whether the target has hardware instruction for vector prefetch.
Definition at line 411 of file ispc.h.
Referenced by hasVecPrefetch(), and Target().
m_is32Bit
bool Target::m_is32Bit private
Is the target architecture 32 or 64 bit
Definition at line 327 of file ispc.h.
Referenced by is32Bit(), SizeOf(), StructOffset(), and Target().
m_isa
ISA Target::m_isa private
Instruction set being compiled to.
Definition at line 318 of file ispc.h.
Referenced by getISA(), GetISAString(), GetISATargetString(), SizeOf(), StructOffset(), and Target().
m_maskBitCount
int Target::m_maskBitCount private
How many bits are used to store each element of the mask: e.g. this is 32 on SSE/AVX, since that matches the HW better, but it's 1 for the generic target.
Definition at line 382 of file ispc.h.
Referenced by getMaskBitCount(), and Target().
m_maskingIsFree
bool Target::m_maskingIsFree private
Is there overhead associated with masking on the target architecture; e.g. there is on SSE, due to extra blends and the like, but there isn't with an ISA that supports masking natively.
Definition at line 377 of file ispc.h.
Referenced by getMaskingIsFree(), and Target().
m_nativeVectorAlignment
int Target::m_nativeVectorAlignment private
Native vector alignment in bytes. Theoretically this may be derived from the vector size, but it's better to manage directly the alignement. It allows easier experimenting and better fine tuning for particular platform. This information is primatily used when –opt=force-aligned-memory is used.
Definition at line 359 of file ispc.h.
Referenced by getNativeVectorAlignment(), and Target().
m_nativeVectorWidth
int Target::m_nativeVectorWidth private
Native vector width of the vector instruction set. Note that this value is directly derived from the ISA being used (e.g. it's 4 for SSE, 8 for AVX, etc.)
Definition at line 352 of file ispc.h.
Referenced by getNativeVectorWidth(), and Target().
m_target
const llvm::Target* Target::m_target private
llvm Target object representing this target.
Definition at line 300 of file ispc.h.
Referenced by getTarget(), and Target().
m_targetMachine
llvm::TargetMachine* Target::m_targetMachine private
llvm TargetMachine. Note that it's not destroyed during Target destruction, as Module::CompileAndOutput() uses TargetMachines after Target is destroyed. This needs to be changed. It's also worth noticing, that DataLayout of TargetMachine cannot be modified and for generic targets it's not what we really need, so it must not be used.
Definition at line 310 of file ispc.h.
Referenced by GetTargetMachine(), and Target().
m_treatGenericAsSmth
std::string Target::m_treatGenericAsSmth private
The variable shows if we use special mangling with generic target.
Definition at line 321 of file ispc.h.
Referenced by getTreatGenericAsSmth(), and Target().
m_valid
bool Target::m_valid private
flag to report invalid state after construction (due to bad parameters passed to constructor).
Definition at line 315 of file ispc.h.
Referenced by isValid(), and Target().
m_vectorWidth
int Target::m_vectorWidth private
Actual vector width currently being compiled to. This may be an integer multiple of the native vector width, for example if we're "doubling up" and compiling 8-wide on a 4-wide SSE system.
Definition at line 368 of file ispc.h.
Referenced by getVectorWidth(), and Target().
The documentation for this class was generated from the following files:
ispc.h
ispc.cpp