Intel SPMD Program Compiler: GSToLoadStorePass Class Reference
GSToLoadStorePass Class Reference
Public Member Functions
GSToLoadStorePass ()
const char * getPassName () const
bool runOnBasicBlock (llvm::BasicBlock &BB)
Static Public Attributes
static char ID = 0
Detailed Description
After earlier optimization passes have run, we are sometimes able to determine that gathers/scatters are actually accessing memory in a more regular fashion and then change the operation to something simpler and more efficient. For example, if all of the lanes in a gather are reading from the same location, we can instead do a scalar load and broadcast. This pass examines gathers and scatters and tries to simplify them if at all possible.
Todo:
Currently, this only looks for all program instances going to the same location and all going to a linear sequence of locations in memory. There are a number of other cases that might make sense to look for, including things that could be handled with a vector load + shuffle or things that could be handled with hybrids of e.g. 2 4-wide vector loads with AVX, etc.
Definition at line 2274 of file opt.cpp.
Constructor & Destructor Documentation
GSToLoadStorePass::GSToLoadStorePass () [inline]
Definition at line 2277 of file opt.cpp.
Member Function Documentation
const char* GSToLoadStorePass::getPassName () const [inline]
Definition at line 2279 of file opt.cpp.
bool GSToLoadStorePass::runOnBasicBlock (llvm::BasicBlock & BB)
Definition at line 2330 of file opt.cpp.
References GatherImpInfo::align, ScatterImpInfo::align, Assert, Debug(), DEBUG_END_PASS, DEBUG_START_PASS, g, LLVMTypes::Int16VectorPointerType, int32_t, LLVMTypes::Int32VectorPointerType, LLVMTypes::Int64VectorPointerType, LLVMTypes::Int64VectorType, LLVMTypes::Int8VectorPointerType, lCallInst(), lComputeCommonPointer(), lCopyMetadata(), lGetSourcePosFromMetadata(), LLVMGetName(), LLVMInt32(), LLVMInt64(), LLVMVectorIsLinear(), LLVMVectorValuesAllEqual(), GatherImpInfo::loadBroadcastFunc, GatherImpInfo::loadMaskedFunc, ScatterImpInfo::maskedStoreFunc, NULL, Globals::target, ScatterImpInfo::vecPtrType, Target::vectorWidth, and Warning().
Member Data Documentation
char GSToLoadStorePass::ID = 0 [static]
Definition at line 2276 of file opt.cpp.
The documentation for this class was generated from the following file:
opt.cpp