Intel速 Implicit SPMD Program Compiler (Intel速 ISPC): llvmutil.cpp File Reference
llvmutil.cpp File Reference
Implementations of various LLVM utility types and classes.
#include "llvmutil.h"
#include "ispc.h"
#include "type.h"
#include <llvm/Analysis/ValueTracking.h>
#include <llvm/IR/BasicBlock.h>
#include <llvm/IR/Instructions.h>
#include <llvm/IR/Module.h>
#include <map>
#include <set>
#include <vector>
Functions
void InitLLVMUtil (llvm::LLVMContext *ctx, Target &target)
llvm::ConstantInt * LLVMInt8 (int8_t ival)
llvm::ConstantInt * LLVMUInt8 (uint8_t ival)
llvm::ConstantInt * LLVMInt16 (int16_t ival)
llvm::ConstantInt * LLVMUInt16 (uint16_t ival)
llvm::ConstantInt * LLVMInt32 (int32_t ival)
llvm::ConstantInt * LLVMUInt32 (uint32_t ival)
llvm::ConstantInt * LLVMInt64 (int64_t ival)
llvm::ConstantInt * LLVMUInt64 (uint64_t ival)
llvm::Constant * LLVMFloat (float fval)
llvm::Constant * LLVMDouble (double dval)
llvm::Constant * LLVMInt8Vector (int8_t ival)
llvm::Constant * LLVMInt8Vector (const int8_t *ivec)
llvm::Constant * LLVMUInt8Vector (uint8_t ival)
llvm::Constant * LLVMUInt8Vector (const uint8_t *ivec)
llvm::Constant * LLVMInt16Vector (int16_t ival)
llvm::Constant * LLVMInt16Vector (const int16_t *ivec)
llvm::Constant * LLVMUInt16Vector (uint16_t ival)
llvm::Constant * LLVMUInt16Vector (const uint16_t *ivec)
llvm::Constant * LLVMInt32Vector (int32_t ival)
llvm::Constant * LLVMInt32Vector (const int32_t *ivec)
llvm::Constant * LLVMUInt32Vector (uint32_t ival)
llvm::Constant * LLVMUInt32Vector (const uint32_t *ivec)
llvm::Constant * LLVMFloatVector (float fval)
llvm::Constant * LLVMFloatVector (const float *fvec)
llvm::Constant * LLVMDoubleVector (double dval)
llvm::Constant * LLVMDoubleVector (const double *dvec)
llvm::Constant * LLVMInt64Vector (int64_t ival)
llvm::Constant * LLVMInt64Vector (const int64_t *ivec)
llvm::Constant * LLVMUInt64Vector (uint64_t ival)
llvm::Constant * LLVMUInt64Vector (const uint64_t *ivec)
llvm::Constant * LLVMBoolVector (bool b)
llvm::Constant * LLVMBoolVector (const bool *bvec)
llvm::Constant * LLVMBoolVectorInStorage (bool b)
llvm::Constant * LLVMBoolVectorInStorage (const bool *bvec)
llvm::Constant * LLVMIntAsType (int64_t val, llvm::Type *type)
llvm::Constant * LLVMUIntAsType (uint64_t val, llvm::Type *type)
static bool lValuesAreEqual (llvm::Value *v0, llvm::Value *v1, std::vector< llvm::PHINode *> &seenPhi0, std::vector< llvm::PHINode *> &seenPhi1)
static int64_t lGetIntValue (llvm::Value *offset)
static bool lIsFirstElementConstVector (llvm::Value *v)
llvm::Value * LLVMFlattenInsertChain (llvm::Value *inst, int vectorWidth, bool compare, bool undef, bool searchFirstUndef)
bool LLVMExtractVectorInts (llvm::Value *v, int64_t ret[], int *nElts)
static bool lVectorValuesAllEqual (llvm::Value *v, int vectorLength, std::vector< llvm::PHINode *> &seenPhis, llvm::Value **splatValue=NULL)
static bool lIsExactMultiple (llvm::Value *val, int baseValue, int vectorLength, std::vector< llvm::PHINode *> &seenPhis)
static int lRoundUpPow2 (int v)
static bool lAllDivBaseEqual (llvm::Value *val, int64_t baseValue, int vectorLength, std::vector< llvm::PHINode *> &seenPhis, bool &canAdd)
static bool lVectorShiftRightAllEqual (llvm::Value *val, llvm::Value *shift, int vectorLength)
bool LLVMVectorValuesAllEqual (llvm::Value *v, llvm::Value **splat)
bool IsOrEquivalentToAdd (llvm::Value *op)
static bool lVectorIsLinear (llvm::Value *v, int vectorLength, int stride, std::vector< llvm::PHINode *> &seenPhis)
static bool lVectorIsLinearConstantInts (llvm::ConstantDataVector *cv, int vectorLength, int stride)
static bool lCheckMulForLinear (llvm::Value *op0, llvm::Value *op1, int vectorLength, int stride, std::vector< llvm::PHINode *> &seenPhis)
static bool lCheckShlForLinear (llvm::Value *op0, llvm::Value *op1, int vectorLength, int stride, std::vector< llvm::PHINode *> &seenPhis)
static bool lCheckAndForLinear (llvm::Value *op0, llvm::Value *op1, int vectorLength, int stride, std::vector< llvm::PHINode *> &seenPhis)
bool LLVMVectorIsLinear (llvm::Value *v, int stride)
static void lDumpValue (llvm::Value *v, std::set< llvm::Value *> &done)
void LLVMDumpValue (llvm::Value *v)
static llvm::Value * lExtractFirstVectorElement (llvm::Value *v, std::map< llvm::PHINode *, llvm::PHINode *> &phiMap)
llvm::Value * LLVMExtractFirstVectorElement (llvm::Value *v)
llvm::Value * LLVMConcatVectors (llvm::Value *v1, llvm::Value *v2, llvm::Instruction *insertBefore)
llvm::Value * LLVMShuffleVectors (llvm::Value *v1, llvm::Value *v2, int32_t shuf[], int shufSize, llvm::Instruction *insertBefore)
const char * LLVMGetName (llvm::Value *v, const char *s)
const char * LLVMGetName (const char *op, llvm::Value *v1, llvm::Value *v2)
Variables
llvm::Constant * LLVMTrue = NULL
llvm::Constant * LLVMFalse = NULL
llvm::Constant * LLVMTrueInStorage = NULL
llvm::Constant * LLVMFalseInStorage = NULL
llvm::Constant * LLVMMaskAllOn = NULL
llvm::Constant * LLVMMaskAllOff = NULL
Detailed Description
Implementations of various LLVM utility types and classes.
Definition in file llvmutil.cpp.
Function Documentation
InitLLVMUtil()
void InitLLVMUtil (llvm::LLVMContext * ctx, Target & target)
Definition at line 97 of file llvmutil.cpp.
References LLVMTypes::BoolStorageType, LLVMTypes::BoolType, LLVMTypes::BoolVectorStorageType, LLVMTypes::BoolVectorType, LLVMTypes::DoublePointerType, LLVMTypes::DoubleType, LLVMTypes::DoubleVectorPointerType, LLVMTypes::DoubleVectorType, FATAL, LLVMTypes::FloatPointerType, LLVMTypes::FloatType, LLVMTypes::FloatVectorPointerType, LLVMTypes::FloatVectorType, g, Target::getMaskBitCount(), Target::getVectorWidth(), LLVMTypes::Int16PointerType, LLVMTypes::Int16Type, LLVMTypes::Int16VectorPointerType, LLVMTypes::Int16VectorType, LLVMTypes::Int1VectorType, LLVMTypes::Int32PointerType, LLVMTypes::Int32Type, LLVMTypes::Int32VectorPointerType, LLVMTypes::Int32VectorType, LLVMTypes::Int64PointerType, LLVMTypes::Int64Type, LLVMTypes::Int64VectorPointerType, LLVMTypes::Int64VectorType, LLVMTypes::Int8PointerType, LLVMTypes::Int8Type, LLVMTypes::Int8VectorPointerType, LLVMTypes::Int8VectorType, Target::is32Bit(), LLVMFalse, LLVMFalseInStorage, LLVMMaskAllOff, LLVMMaskAllOn, LLVMTrue, LLVMTrueInStorage, LLVMTypes::MaskType, LLVMTypes::PointerIntType, Globals::target, LLVMTypes::VoidPointerType, LLVMTypes::VoidPointerVectorType, and LLVMTypes::VoidType.
Referenced by Module::Module().
IsOrEquivalentToAdd()
bool IsOrEquivalentToAdd (llvm::Value * op)
Tests to see if a binary operator has an OR which is equivalent to an ADD.
Definition at line 1098 of file llvmutil.cpp.
References lVectorIsLinear().
Referenced by lAllDivBaseEqual(), lExtractConstantOffset(), lExtractOffsetVector248Scale(), lGetBasePtrAndOffsets(), lIs32BitSafeHelper(), lIsExactMultiple(), LLVMFlattenInsertChain(), and lVectorIsLinear().
lAllDivBaseEqual()
static bool lAllDivBaseEqual (llvm::Value * val, int64_t baseValue, int vectorLength, std::vector< llvm::PHINode *> & seenPhis, bool & canAdd) static
Try to determine if all of the elements of the given vector value have the same value when divided by the given baseValue. The function returns true if this can be determined to be the case, and false otherwise. (This function may fail to identify some cases where it does in fact have this property, but should never report a given value as being a multiple if it isn't!)
Definition at line 815 of file llvmutil.cpp.
References Assert, IsOrEquivalentToAdd(), ISPC_MAX_NVEC, lIsExactMultiple(), LLVMExtractVectorInts(), lRoundUpPow2(), and lVectorValuesAllEqual().
Referenced by lCheckAndForLinear(), and lVectorShiftRightAllEqual().
lCheckAndForLinear()
static bool lCheckAndForLinear (llvm::Value * op0, llvm::Value * op1, int vectorLength, int stride, std::vector< llvm::PHINode *> & seenPhis) static
Given (op0 AND op1), try and see if we can determine if the result is a linear sequence with a step of "stride" between values. Returns true if so and false otherwise. This pattern comes up when accessing SOA data.
Definition at line 1219 of file llvmutil.cpp.
References Assert, ISPC_MAX_NVEC, lAllDivBaseEqual(), LLVMExtractVectorInts(), and lVectorIsLinear().
Referenced by lVectorIsLinear().
lCheckMulForLinear()
static bool lCheckMulForLinear (llvm::Value * op0, llvm::Value * op1, int vectorLength, int stride, std::vector< llvm::PHINode *> & seenPhis) static
Checks to see if (op0 * op1) is a linear vector where the result is a vector with values that increase by stride.
Definition at line 1155 of file llvmutil.cpp.
References lVectorIsLinear().
Referenced by lVectorIsLinear().
lCheckShlForLinear()
static bool lCheckShlForLinear (llvm::Value * op0, llvm::Value * op1, int vectorLength, int stride, std::vector< llvm::PHINode *> & seenPhis) static
Checks to see if (op0 << op1) is a linear vector where the result is a vector with values that increase by stride.
Definition at line 1186 of file llvmutil.cpp.
References lVectorIsLinear().
Referenced by lVectorIsLinear().
lDumpValue()
static void lDumpValue (llvm::Value * v, std::set< llvm::Value *> & done) static
Definition at line 1378 of file llvmutil.cpp.
Referenced by LLVMDumpValue().
lExtractFirstVectorElement()
static llvm::Value* lExtractFirstVectorElement (llvm::Value * v, std::map< llvm::PHINode *, llvm::PHINode *> & phiMap) static
Definition at line 1404 of file llvmutil.cpp.
References Assert, LLVMFlattenInsertChain(), and LLVMInt32().
Referenced by LLVMExtractFirstVectorElement().
lGetIntValue()
static int64_t lGetIntValue (llvm::Value * offset) static
Given an llvm::Value known to be an integer, return its value as an int64_t.
Definition at line 560 of file llvmutil.cpp.
References Assert.
Referenced by LLVMFlattenInsertChain().
lIsExactMultiple()
static bool lIsExactMultiple (llvm::Value * val, int baseValue, int vectorLength, std::vector< llvm::PHINode *> & seenPhis) static
This function checks to see if the given (scalar or vector) value is an exact multiple of baseValue. It returns true if so, and false if not (or if it's not able to determine if it is). Any vector value passed in is required to have the same value in all elements (so that we can just check the first element to be a multiple of the given value.)
Definition at line 741 of file llvmutil.cpp.
References Assert, g, Target::getVectorWidth(), IsOrEquivalentToAdd(), LLVMFlattenInsertChain(), LLVMVectorValuesAllEqual(), and Globals::target.
Referenced by lAllDivBaseEqual().
lIsFirstElementConstVector()
static bool lIsFirstElementConstVector (llvm::Value * v) static
Recognizes constant vector with undef operands except the first one: <i64 4, i64 undef, i64 undef, i64 undef, i64 undef, i64 undef, i64 undef, i64 undef>
Definition at line 569 of file llvmutil.cpp.
Referenced by LLVMFlattenInsertChain().
LLVMBoolVector() [1/2]
llvm::Constant* LLVMBoolVector (bool v)
Returns an LLVM boolean vector constant of the given value smeared across all elements
Definition at line 403 of file llvmutil.cpp.
References Assert, LLVMTypes::BoolVectorType, g, Target::getVectorWidth(), LLVMTypes::Int16Type, LLVMTypes::Int16VectorType, LLVMTypes::Int1VectorType, LLVMTypes::Int32Type, LLVMTypes::Int32VectorType, LLVMTypes::Int64Type, LLVMTypes::Int64VectorType, LLVMTypes::Int8Type, LLVMTypes::Int8VectorType, LLVMFalse, LLVMTrue, and Globals::target.
Referenced by ForStmt::EmitCode(), ConstExpr::GetValue(), lGetConstExprConstant(), and lLLVMConstantValue().
LLVMBoolVector() [2/2]
llvm::Constant* LLVMBoolVector (const bool * v)
Returns an LLVM boolean vector based on the given array of values. The array should have g->target.vectorWidth elements.
Definition at line 424 of file llvmutil.cpp.
References Assert, LLVMTypes::BoolVectorType, g, Target::getVectorWidth(), LLVMTypes::Int16Type, LLVMTypes::Int16VectorType, LLVMTypes::Int1VectorType, LLVMTypes::Int32Type, LLVMTypes::Int32VectorType, LLVMTypes::Int64Type, LLVMTypes::Int64VectorType, LLVMTypes::Int8Type, LLVMTypes::Int8VectorType, LLVMFalse, LLVMTrue, and Globals::target.
LLVMBoolVectorInStorage() [1/2]
llvm::Constant* LLVMBoolVectorInStorage (bool v)
Returns an LLVM boolean vector constant of the given value smeared across all elements with bool represented as storage type(i8)
Definition at line 446 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMFalseInStorage, LLVMTrueInStorage, and Globals::target.
Referenced by lGetConstExprConstant().
LLVMBoolVectorInStorage() [2/2]
llvm::Constant* LLVMBoolVectorInStorage (const bool * v)
Returns an LLVM boolean vector based on the given array of values with bool represented as storage type(i8). The array should have g->target.vectorWidth elements.
Definition at line 454 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMTypes::Int8Type, and Globals::target.
LLVMConcatVectors()
llvm::Value* LLVMConcatVectors (llvm::Value * v1, llvm::Value * v2, llvm::Instruction * insertBefore)
Given two vectors of the same type, concatenate them into a vector that has twice as many elements, where the first half has the elements from the first vector and the second half has the elements from the second vector.
Definition at line 1514 of file llvmutil.cpp.
References Assert, ISPC_MAX_NVEC, and LLVMShuffleVectors().
Referenced by lAssembleResultVectors().
LLVMDouble()
llvm::Constant* LLVMDouble (double f)
Returns an LLVM double constant of the given value
Definition at line 251 of file llvmutil.cpp.
References Globals::ctx, and g.
Referenced by ConstExpr::GetValue(), lGetConstExprConstant(), lLLVMConstantValue(), LLVMDoubleVector(), and lTypeConvAtomic().
LLVMDoubleVector() [1/2]
llvm::Constant* LLVMDoubleVector (double f)
Returns an LLVM double vector constant of the given value smeared across all elements
Definition at line 358 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMDouble(), and Globals::target.
Referenced by ConstExpr::GetValue(), lGetConstExprConstant(), lLLVMConstantValue(), and lTypeConvAtomic().
LLVMDoubleVector() [2/2]
llvm::Constant* LLVMDoubleVector (const double * f)
Returns an LLVM double vector based on the given array of values. The array should have g->target.vectorWidth elements.
Definition at line 366 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMDouble(), and Globals::target.
LLVMDumpValue()
void LLVMDumpValue (llvm::Value * v)
This is a utility routine for debugging that dumps out the given LLVM value as well as (recursively) all of the other values that it depends on.
Definition at line 1397 of file llvmutil.cpp.
References lDumpValue().
Referenced by lGetBasePtrAndOffsets(), LLVMVectorIsLinear(), LLVMVectorValuesAllEqual(), lVectorShiftRightAllEqual(), and GatherCoalescePass::runOnBasicBlock().
LLVMExtractFirstVectorElement()
llvm::Value* LLVMExtractFirstVectorElement (llvm::Value * v)
Given a vector-typed value, this function returns the value of its first element. Rather than just doing the straightforward thing of using a single extractelement instruction to do this, this function tries to rewrite the computation for the first element in scalar form; this is generally more efficient than computing the entire vector's worth of values just to extract the first element, in cases where only the first element's value is needed.
Definition at line 1503 of file llvmutil.cpp.
References lExtractFirstVectorElement().
Referenced by lComputeBasePtr(), and lComputeCommonPointer().
LLVMExtractVectorInts()
bool LLVMExtractVectorInts (llvm::Value * v, int64_t ret[], int * nElts)
Given a vector-typed value v, if the vector is a vector with constant element values, this function extracts those element values into the ret[] array and returns the number of elements (i.e. the vector type's width) in *nElts. It returns true if successful and false if the given vector is not in fact a vector of constants.
Definition at line 709 of file llvmutil.cpp.
References Assert, and lVectorValuesAllEqual().
Referenced by lAllDivBaseEqual(), lCheckAndForLinear(), lExtractConstOffsets(), lVectorIs32BitInts(), and lVectorShiftRightAllEqual().
LLVMFlattenInsertChain()
llvm::Value* LLVMFlattenInsertChain (llvm::Value * inst, int vectorWidth, bool compare = true, bool undef = true, bool searchFirstUndef = false)
This function takes chains of InsertElement instructions along the lines of:
v0 = insertelement undef, value_0, i32 index_0 v1 = insertelement v1, value_1, i32 index_1 ... vn = insertelement vn-1, value_n-1, i32 index_n-1
and initializes the provided elements array such that the i'th llvm::Value * in the array is the element that was inserted into the i'th element of the vector.
When the chain of insertelement instruction comes to an end, the only base case that this function handles is the initial value being a constant vector. For anything more complex (e.g. some other arbitrary value, it doesn't try to extract element values into the returned array.
This also handles one of two common broadcast patterns:
broadcast_init.0 = insertelement <4 x i32> undef, i32 val, i32 0 broadcast.1 = shufflevector <4 x i32> smear.0, <4 x i32> undef, <4 x i32> zeroinitializer
gep_ptr2int_broadcast_init = insertelement <8 x i64> undef, i64 gep_ptr2int, i32 0 %0 = add <8 x i64> gep_ptr2int_broadcast_init, <i64 4, i64 undef, i64 undef, i64 undef, i64 undef, i64 undef, i64 undef, i64 undef> gep_offset = shufflevector <8 x i64> %0, <8 x i64> undef, <8 x i32> zeroinitializer Function returns: Compare all elements and return one of them if all are equal, otherwise NULL. If searchFirstUndef argument is true, look for the vector with the first not-undef element, like: <i64 4, i64 undef, i64 undef, i64 undef, i64 undef, i64 undef, i64 undef, i64 undef> If compare argument is false, don't do compare and return first element instead. If undef argument is true, ignore undef elements (but all undef yields NULL anyway).
Definition at line 587 of file llvmutil.cpp.
References Assert, IsOrEquivalentToAdd(), lGetIntValue(), lIsFirstElementConstVector(), and lValuesAreEqual().
Referenced by lExtractFirstVectorElement(), lGetBasePointer(), lIsExactMultiple(), and lVectorValuesAllEqual().
LLVMFloat()
llvm::Constant* LLVMFloat (float f)
Returns an LLVM float constant of the given value
Definition at line 249 of file llvmutil.cpp.
References Globals::ctx, and g.
Referenced by ConstExpr::GetValue(), lGetConstExprConstant(), lLLVMConstantValue(), LLVMFloatVector(), and lTypeConvAtomic().
LLVMFloatVector() [1/2]
llvm::Constant* LLVMFloatVector (float f)
Returns an LLVM float vector constant of the given value smeared across all elements
Definition at line 343 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMFloat(), and Globals::target.
Referenced by ConstExpr::GetValue(), lGetConstExprConstant(), lLLVMConstantValue(), and lTypeConvAtomic().
LLVMFloatVector() [2/2]
llvm::Constant* LLVMFloatVector (const float * f)
Returns an LLVM float vector based on the given array of values. The array should have g->target.vectorWidth elements.
Definition at line 351 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMFloat(), and Globals::target.
LLVMGetName() [1/2]
const char* LLVMGetName (llvm::Value * v, const char *)
Utility routines to concat strings with the names of existing values to create meaningful new names for instruction values.
Definition at line 1549 of file llvmutil.cpp.
Referenced by FunctionEmitContext::All(), FunctionEmitContext::Any(), FunctionEmitContext::applyVaryingGEP(), FunctionEmitContext::BitCastInst(), FunctionEmitContext::BroadcastValue(), FunctionEmitContext::CastInst(), FunctionEmitContext::ExtractInst(), FunctionEmitContext::FPCastInst(), IndexExpr::GetLValue(), UnaryExpr::GetValue(), MemberExpr::GetValue(), NewExpr::GetValue(), VectorMemberExpr::GetValue(), FunctionEmitContext::I1VecToBoolVec(), FunctionEmitContext::InsertInst(), FunctionEmitContext::IntToPtrInst(), FunctionEmitContext::LaneMask(), lConvertToSlicePointer(), lEmitBinaryArith(), lEmitBinaryCmp(), lEmitNegate(), lExtractConstantOffset(), lFinalSliceOffset(), lGetBasePointer(), lGSToGSBaseOffsets(), lGSToLoadStore(), FunctionEmitContext::LoadInst(), lOffsets32BitSafe(), lTypeConvAtomic(), FunctionEmitContext::MakeSlicePointer(), FunctionEmitContext::MasksAllEqual(), FunctionEmitContext::None(), FunctionEmitContext::PtrToIntInst(), IntrinsicsOpt::runOnBasicBlock(), FunctionEmitContext::SelectInst(), FunctionEmitContext::SExtInst(), FunctionEmitContext::ShuffleInst(), FunctionEmitContext::SwitchBoolSize(), FunctionEmitContext::TruncInst(), and FunctionEmitContext::ZExtInst().
LLVMGetName() [2/2]
const char* LLVMGetName (const char * op, llvm::Value * v1, llvm::Value * v2)
Definition at line 1557 of file llvmutil.cpp.
LLVMInt16()
llvm::ConstantInt* LLVMInt16 (int16_t i)
Returns an LLVM i16 constant of the given value
Definition at line 225 of file llvmutil.cpp.
References Globals::ctx, and g.
Referenced by ConstExpr::GetValue(), lGetConstExprConstant(), lLLVMConstantValue(), LLVMInt16Vector(), and lTypeConvAtomic().
LLVMInt16Vector() [1/2]
llvm::Constant* LLVMInt16Vector (int16_t i)
Returns an LLVM i16 vector constant of the given value smeared across all elements
Definition at line 283 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMInt16(), and Globals::target.
Referenced by ConstExpr::GetValue(), lGetConstExprConstant(), lLLVMConstantValue(), and lTypeConvAtomic().
LLVMInt16Vector() [2/2]
llvm::Constant* LLVMInt16Vector (const int16_t * i)
Returns an LLVM i16 vector based on the given array of values. The array should have g->target.vectorWidth elements.
Definition at line 291 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMInt16(), and Globals::target.
LLVMInt32()
llvm::ConstantInt* LLVMInt32 (int32_t i)
Returns an LLVM i32 constant of the given value
Definition at line 233 of file llvmutil.cpp.
References Globals::ctx, and g.
Referenced by FunctionEmitContext::AddElementOffset(), FunctionEmitContext::addGSMetadata(), FunctionEmitContext::AddInstrumentationPoint(), DefineStdlib(), ForeachStmt::EmitCode(), PrintStmt::EmitCode(), FunctionEmitContext::ExtractInst(), TypeCastExpr::GetConstant(), IndexExpr::GetLValue(), IndexExpr::GetValue(), ConstExpr::GetValue(), TypeCastExpr::GetValue(), NewExpr::GetValue(), InitSymbol(), FunctionEmitContext::InsertInst(), lApplyLoad1(), lApplyLoad2(), FunctionEmitContext::LaunchInst(), lCreateDispatchFunction(), lDefineConstantInt(), lDefineConstantIntFunc(), lExtract248Scale(), lExtractFirstVectorElement(), lExtractOffsetVector248Scale(), lGetBasePtrAndOffsets(), lGetConstExprConstant(), lGetOffsetScaleVec(), lGetStringAsValue(), lGSToLoadStore(), lLLVMConstantValue(), LLVMInt32Vector(), LLVMShuffleVectors(), lTypeConvAtomic(), FunctionEmitContext::MemcpyInst(), FunctionEmitContext::ProgramIndexVector(), IntrinsicsOpt::runOnBasicBlock(), Target::SizeOf(), Target::StructOffset(), and FunctionEmitContext::SwitchInst().
LLVMInt32Vector() [1/2]
llvm::Constant* LLVMInt32Vector (int32_t i)
Returns an LLVM i32 vector constant of the given value smeared across all elements
Definition at line 313 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMInt32(), and Globals::target.
Referenced by FunctionEmitContext::EmitCaseLabel(), FunctionEmitContext::EmitDefaultLabel(), ConstExpr::GetValue(), TypeCastExpr::GetValue(), NewExpr::GetValue(), lDefineProgramIndex(), lExtract248Scale(), lGetBasePtrAndOffsets(), lGetConstExprConstant(), lGSBaseOffsetsGetMoreConst(), lLLVMConstantValue(), lTypeConvAtomic(), lUpdateVaryingCounter(), and ReplaceStdlibShiftPass::runOnBasicBlock().
LLVMInt32Vector() [2/2]
llvm::Constant* LLVMInt32Vector (const int32_t * i)
Returns an LLVM i32 vector based on the given array of values. The array should have g->target.vectorWidth elements.
Definition at line 321 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMInt32(), and Globals::target.
LLVMInt64()
llvm::ConstantInt* LLVMInt64 (int64_t i)
Returns an LLVM i64 constant of the given value
Definition at line 241 of file llvmutil.cpp.
References Globals::ctx, and g.
Referenced by FunctionEmitContext::AddElementOffset(), ForeachActiveStmt::EmitCode(), ForeachUniqueStmt::EmitCode(), AddressOfExpr::GetConstant(), ConstExpr::GetValue(), NewExpr::GetValue(), lEmitLoads(), lGEPAndLoad(), lGetBasePtrAndOffsets(), lGetConstExprConstant(), lGetOffsetScaleVec(), lLLVMConstantValue(), LLVMInt64Vector(), lTypeConvAtomic(), FunctionEmitContext::ProgramIndexVector(), IntrinsicsOpt::runOnBasicBlock(), InstructionSimplifyPass::simplifyCall(), Target::SizeOf(), Target::StructOffset(), and FunctionEmitContext::SwitchInst().
LLVMInt64Vector() [1/2]
llvm::Constant* LLVMInt64Vector (int64_t i)
Returns an LLVM i64 vector constant of the given value smeared across all elements
Definition at line 373 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMInt64(), and Globals::target.
Referenced by FunctionEmitContext::EmitCaseLabel(), FunctionEmitContext::EmitDefaultLabel(), ConstExpr::GetValue(), NewExpr::GetValue(), lExtract248Scale(), lGetBasePtrAndOffsets(), lGetConstExprConstant(), lGSBaseOffsetsGetMoreConst(), lLLVMConstantValue(), and lTypeConvAtomic().
LLVMInt64Vector() [2/2]
llvm::Constant* LLVMInt64Vector (const int64_t * i)
Returns an LLVM i64 vector based on the given array of values. The array should have g->target.vectorWidth elements.
Definition at line 381 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMInt64(), and Globals::target.
LLVMInt8()
llvm::ConstantInt* LLVMInt8 (int8_t i)
Returns an LLVM i8 constant of the given value
Definition at line 217 of file llvmutil.cpp.
References Globals::ctx, and g.
Referenced by ConstExpr::GetValue(), lGetConstExprConstant(), lLLVMConstantValue(), LLVMInt8Vector(), and lTypeConvAtomic().
LLVMInt8Vector() [1/2]
llvm::Constant* LLVMInt8Vector (int8_t i)
Returns an LLVM i8 vector constant of the given value smeared across all elements
Definition at line 253 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMInt8(), and Globals::target.
Referenced by ConstExpr::GetValue(), lGetConstExprConstant(), lLLVMConstantValue(), and lTypeConvAtomic().
LLVMInt8Vector() [2/2]
llvm::Constant* LLVMInt8Vector (const int8_t * i)
Returns an LLVM i8 vector based on the given array of values. The array should have g->target.vectorWidth elements.
Definition at line 261 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMInt8(), and Globals::target.
LLVMIntAsType()
llvm::Constant* LLVMIntAsType (int64_t , llvm::Type * t)
Returns a constant integer or vector (according to the given type) of the given signed integer value.
Definition at line 463 of file llvmutil.cpp.
Referenced by lComputeSliceIndex(), lEmitBinaryPointerArith(), lGSBaseOffsetsGetMoreConst(), and lGSToGSBaseOffsets().
LLVMShuffleVectors()
llvm::Value* LLVMShuffleVectors (llvm::Value * v1, llvm::Value * v2, int32_t shuf[], int shufSize, llvm::Instruction * insertBefore)
Shuffle two vectors together with a ShuffleVectorInst, returning a vector with shufSize elements, where the shuf[] array offsets are used to determine which element from the two given vectors is used for each result element.
Definition at line 1533 of file llvmutil.cpp.
References LLVMTypes::Int32Type, and LLVMInt32().
Referenced by lApplyLoad4(), lAssemble4Vector(), LLVMConcatVectors(), and lSplit8WideLoads().
LLVMUInt16()
llvm::ConstantInt* LLVMUInt16 (uint16_t i)
Returns an LLVM i16 constant of the given value
Definition at line 229 of file llvmutil.cpp.
References Globals::ctx, and g.
Referenced by ConstExpr::GetValue(), lGetConstExprConstant(), lLLVMConstantValue(), and LLVMUInt16Vector().
LLVMUInt16Vector() [1/2]
llvm::Constant* LLVMUInt16Vector (uint16_t i)
Returns an LLVM i16 vector constant of the given value smeared across all elements
Definition at line 298 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMUInt16(), and Globals::target.
Referenced by ConstExpr::GetValue(), lGetConstExprConstant(), and lLLVMConstantValue().
LLVMUInt16Vector() [2/2]
llvm::Constant* LLVMUInt16Vector (const uint16_t * i)
Returns an LLVM i16 vector based on the given array of values. The array should have g->target.vectorWidth elements.
Definition at line 306 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMUInt16(), and Globals::target.
LLVMUInt32()
llvm::ConstantInt* LLVMUInt32 (uint32_t i)
Returns an LLVM i32 constant of the given value
Definition at line 237 of file llvmutil.cpp.
References Globals::ctx, and g.
Referenced by ConstExpr::GetValue(), lGetConstExprConstant(), lLLVMConstantValue(), and LLVMUInt32Vector().
LLVMUInt32Vector() [1/2]
llvm::Constant* LLVMUInt32Vector (uint32_t i)
Returns an LLVM i32 vector constant of the given value smeared across all elements
Definition at line 328 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMUInt32(), and Globals::target.
Referenced by ConstExpr::GetValue(), lGetConstExprConstant(), and lLLVMConstantValue().
LLVMUInt32Vector() [2/2]
llvm::Constant* LLVMUInt32Vector (const uint32_t * i)
Returns an LLVM i32 vector based on the given array of values. The array should have g->target.vectorWidth elements.
Definition at line 336 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMUInt32(), and Globals::target.
LLVMUInt64()
llvm::ConstantInt* LLVMUInt64 (uint64_t i)
Returns an LLVM i64 constant of the given value
Definition at line 245 of file llvmutil.cpp.
References Globals::ctx, and g.
Referenced by ConstExpr::GetValue(), lGetConstExprConstant(), lLLVMConstantValue(), and LLVMUInt64Vector().
LLVMUInt64Vector() [1/2]
llvm::Constant* LLVMUInt64Vector (uint64_t i)
Returns an LLVM i64 vector constant of the given value smeared across all elements
Definition at line 388 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMUInt64(), and Globals::target.
Referenced by ConstExpr::GetValue(), lGetConstExprConstant(), and lLLVMConstantValue().
LLVMUInt64Vector() [2/2]
llvm::Constant* LLVMUInt64Vector (const uint64_t * i)
Returns an LLVM i64 vector based on the given array of values. The array should have g->target.vectorWidth elements.
Definition at line 396 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMUInt64(), and Globals::target.
LLVMUInt8()
llvm::ConstantInt* LLVMUInt8 (uint8_t i)
Returns an LLVM i8 constant of the given value
Definition at line 221 of file llvmutil.cpp.
References Globals::ctx, and g.
Referenced by ConstExpr::GetValue(), lGetConstExprConstant(), lLLVMConstantValue(), and LLVMUInt8Vector().
LLVMUInt8Vector() [1/2]
llvm::Constant* LLVMUInt8Vector (uint8_t i)
Returns an LLVM i8 vector constant of the given value smeared across all elements
Definition at line 268 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMUInt8(), and Globals::target.
Referenced by ConstExpr::GetValue(), lGetConstExprConstant(), and lLLVMConstantValue().
LLVMUInt8Vector() [2/2]
llvm::Constant* LLVMUInt8Vector (const uint8_t * i)
Returns an LLVM i8 vector based on the given array of values. The array should have g->target.vectorWidth elements.
Definition at line 276 of file llvmutil.cpp.
References g, Target::getVectorWidth(), LLVMUInt8(), and Globals::target.
LLVMUIntAsType()
llvm::Constant* LLVMUIntAsType (uint64_t , llvm::Type * t)
Returns a constant integer or vector (according to the given type) of the given unsigned integer value.
Definition at line 476 of file llvmutil.cpp.
LLVMVectorIsLinear()
bool LLVMVectorIsLinear (llvm::Value * v, int stride)
Given vector of integer-typed values, see if the elements of the array have a step of 'stride' between their values. This function tries to handle as many possibilities as possible, including things like all elements equal to some non-constant value plus an integer offset, etc.
Definition at line 1361 of file llvmutil.cpp.
References Assert, Debug(), Globals::debugPrint, g, LLVMDumpValue(), and lVectorIsLinear().
Referenced by lGSToLoadStore().
LLVMVectorValuesAllEqual()
bool LLVMVectorValuesAllEqual (llvm::Value * v, llvm::Value ** splat)
Tests to see if all of the elements of the vector in the 'v' parameter are equal. This is a conservative test and may return false for arrays where the values are actually all equal.
Definition at line 1080 of file llvmutil.cpp.
References Assert, Debug(), Globals::debugPrint, g, LLVMDumpValue(), and lVectorValuesAllEqual().
Referenced by isFPIntBitCast(), lExtractOffsetVector248Scale(), lGSToLoadStore(), lIsExactMultiple(), and GatherCoalescePass::runOnBasicBlock().
lRoundUpPow2()
static int lRoundUpPow2 (int v) static
Returns the next power of two greater than or equal to the given value.
Definition at line 798 of file llvmutil.cpp.
Referenced by lAllDivBaseEqual().
lValuesAreEqual()
static bool lValuesAreEqual (llvm::Value * v0, llvm::Value * v1, std::vector< llvm::PHINode *> & seenPhi0, std::vector< llvm::PHINode *> & seenPhi1) static
Conservative test to see if two llvm::Values are equal. There are (potentially many) cases where the two values actually are equal but this will return false. However, if it does return true, the two vectors definitely are equal.
Definition at line 494 of file llvmutil.cpp.
References Assert.
Referenced by LLVMFlattenInsertChain().
lVectorIsLinear()
static bool lVectorIsLinear (llvm::Value * v, int vectorLength, int stride, std::vector< llvm::PHINode *> & seenPhis) static
Definition at line 1250 of file llvmutil.cpp.
References IsOrEquivalentToAdd(), lCheckAndForLinear(), lCheckMulForLinear(), lCheckShlForLinear(), lVectorIsLinearConstantInts(), and lVectorValuesAllEqual().
Referenced by IsOrEquivalentToAdd(), lCheckAndForLinear(), lCheckMulForLinear(), lCheckShlForLinear(), and LLVMVectorIsLinear().
lVectorIsLinearConstantInts()
static bool lVectorIsLinearConstantInts (llvm::ConstantDataVector * cv, int vectorLength, int stride) static
Given a vector of compile-time constant integer values, test to see if they are a linear sequence of constant integers starting from an arbirary value but then having a step of value "stride" between elements.
Definition at line 1121 of file llvmutil.cpp.
References Assert.
Referenced by lVectorIsLinear().
lVectorShiftRightAllEqual()
static bool lVectorShiftRightAllEqual (llvm::Value * val, llvm::Value * shift, int vectorLength) static
Given a vector shift right of some value by some amount, try to determine if all of the elements of the final result have the same value (i.e. whether the high bits are all equal, disregarding the low bits that are shifted out.) Returns true if so, and false otherwise.
Definition at line 934 of file llvmutil.cpp.
References Assert, ISPC_MAX_NVEC, lAllDivBaseEqual(), LLVMDumpValue(), and LLVMExtractVectorInts().
Referenced by lVectorValuesAllEqual().
lVectorValuesAllEqual()
static bool lVectorValuesAllEqual (llvm::Value * v, int vectorLength, std::vector< llvm::PHINode *> & seenPhis, llvm::Value ** splatValue = NULL) static
Definition at line 963 of file llvmutil.cpp.
References Assert, LLVMFlattenInsertChain(), and lVectorShiftRightAllEqual().
Referenced by lAllDivBaseEqual(), LLVMExtractVectorInts(), LLVMVectorValuesAllEqual(), and lVectorIsLinear().
Variable Documentation
LLVMFalse
llvm::Constant* LLVMFalse = NULL
Definition at line 91 of file llvmutil.cpp.
Referenced by ForeachStmt::EmitCode(), ConstExpr::GetValue(), InitLLVMUtil(), lEmitLogicalOp(), lGetConstExprConstant(), lLLVMConstantValue(), LLVMBoolVector(), FunctionEmitContext::MemcpyInst(), and IsCompileTimeConstantPass::runOnBasicBlock().
LLVMFalseInStorage
llvm::Constant* LLVMFalseInStorage = NULL
Definition at line 93 of file llvmutil.cpp.
Referenced by InitLLVMUtil(), lGetConstExprConstant(), and LLVMBoolVectorInStorage().
LLVMMaskAllOff
llvm::Constant* LLVMMaskAllOff = NULL
LLVM constant value representing an 'all off' SIMD lane mask
Definition at line 95 of file llvmutil.cpp.
Referenced by FunctionEmitContext::Break(), FunctionEmitContext::ClearBreakLanes(), FunctionEmitContext::Continue(), FunctionEmitContext::CurrentLanesReturned(), ForeachStmt::EmitCode(), FunctionEmitContext::EndIf(), FunctionEmitContext::FunctionEmitContext(), InitLLVMUtil(), lEmitLogicalOp(), FunctionEmitContext::RestoreContinuedLanes(), FunctionEmitContext::StartForeach(), FunctionEmitContext::StartLoop(), FunctionEmitContext::StartSwitch(), and FunctionEmitContext::SwitchInst().
LLVMMaskAllOn
llvm::Constant* LLVMMaskAllOn = NULL
LLVM constant value representing an 'all on' SIMD lane mask
Definition at line 94 of file llvmutil.cpp.
Referenced by FunctionEmitContext::CallInst(), Function::emitCode(), DoStmt::EmitCode(), ForStmt::EmitCode(), ForeachStmt::EmitCode(), UnmaskedStmt::EmitCode(), IfStmt::emitMaskAllOn(), FunctionEmitContext::EndIf(), FunctionEmitContext::FunctionEmitContext(), IndexExpr::GetValue(), MemberExpr::GetValue(), InitLLVMUtil(), lEmitLogicalOp(), lStoreAssignResult(), FunctionEmitContext::maskedStore(), FunctionEmitContext::restoreMaskGivenReturns(), FunctionEmitContext::SetInternalMaskAndNot(), and FunctionEmitContext::StoreInst().
LLVMTrue
llvm::Constant* LLVMTrue = NULL
These variables hold the corresponding LLVM constant values as a convenience to code elsewhere in the system.
Definition at line 90 of file llvmutil.cpp.
Referenced by ForStmt::EmitCode(), ForeachStmt::EmitCode(), ConstExpr::GetValue(), InitLLVMUtil(), lEmitLogicalOp(), lGetConstExprConstant(), lLLVMConstantValue(), LLVMBoolVector(), and IsCompileTimeConstantPass::runOnBasicBlock().
LLVMTrueInStorage
llvm::Constant* LLVMTrueInStorage = NULL
Definition at line 92 of file llvmutil.cpp.
Referenced by InitLLVMUtil(), lGetConstExprConstant(), and LLVMBoolVectorInStorage().