Intel SPMD Program Compiler: constant_scanner Namespace Reference
constant_scanner Namespace Reference
Classes
class constant_iterator
Functions
constant_iterator constant_begin (const llvm::Function *F)
constant_iterator constant_end (const llvm::Function *F)
Function Documentation
constant_iterator constant_scanner::constant_begin (const llvm::Function * F) inline
Definition at line 195 of file cbackend.cpp.
References constant_scanner::constant_iterator::constant_iterator().
Referenced by PrintEscapedString().
constant_iterator constant_scanner::constant_end (const llvm::Function * F) inline
Definition at line 199 of file cbackend.cpp.
References constant_scanner::constant_iterator::constant_iterator().
Referenced by PrintEscapedString().