Intel SPMD Program Compiler: opt.h File Reference
opt.h File Reference
Declarations related to optimization passes.
#include "ispc.h"
Functions
void Optimize (llvm::Module *module, int optLevel)
Detailed Description
Declarations related to optimization passes.
Definition in file opt.h.
Function Documentation
Optimize()
void Optimize (llvm::Module * module, int optLevel)
Optimize the functions in the given module, applying the specified level of optimization. optLevel zero corresponds to essentially no optimization–just enough to generate correct code, while level one corresponds to full optimization.
Definition at line 504 of file opt.cpp.
References DebugPassManager::add(), CreateFixBooleanSelectPass(), CreateGatherCoalescePass(), CreateImproveMemoryOpsPass(), CreateInstructionSimplifyPass(), CreateIntrinsicsOptPass(), CreateIsCompileTimeConstantPass(), CreateMakeInternalFuncsStaticPass(), CreatePeepholePass(), CreateReplacePseudoMemoryOpsPass(), CreateReplaceStdlibShiftPass(), Globals::debugPrint, Opt::disableCoalescing, Opt::disableGatherScatterOptimizations, Opt::disableHandlePseudoMemoryOps, Opt::disableMaskAllOnOptimizations, g, Target::GENERIC, Target::getDataLayout(), Target::getISA(), DebugPassManager::getPM(), Target::GetTargetMachine(), Target::getVectorWidth(), LAST_OPT_NUMBER, Globals::opt, DebugPassManager::run(), Globals::target, and Opt::unrollLoops.