Intel SPMD Program Compiler: parse.yy File Reference
parse.yy File Reference
#include "ispc.h"
#include "type.h"
#include "module.h"
#include "decl.h"
#include "expr.h"
#include "sym.h"
#include "stmt.h"
#include "util.h"
#include <stdio.h>
#include <llvm/IR/Constants.h>
Macros
#define yytnamerr lYYTNameErr
#define YYLTYPE SourcePos
#define YYLLOC_DEFAULT(Current, Rhs, N)
#define UNIMPLEMENTED
Functions
if (s)$$
TOKEN_LAUNCH postfix_expression (' ')'
Variables
primary_expression __pad0__
Symbol * s = m->symbolTable->LookupVariable(name)
launch_expression __pad1__
launch_expression int32_t
launch_expression Expr * launchCount [3] = {oneExpr, oneExpr, oneExpr}
Macro Definition Documentation
#define UNIMPLEMENTED
Value:
Error(yylloc, "Unimplemented parser functionality %s:%d", \
        __FILE__, __LINE__);
#define YYLLOC_DEFAULT (Current, Rhs, N)
Value:
do                                                                 \
      if (N)                                                           \
        {                                                              \
          (Current).first_line   = YYRHSLOC (Rhs, 1).first_line;       \
          (Current).first_column = YYRHSLOC (Rhs, 1).first_column;     \
          (Current).last_line    = YYRHSLOC (Rhs, N).last_line;        \
          (Current).last_column  = YYRHSLOC (Rhs, N).last_column;      \
          (Current).name         = YYRHSLOC (Rhs, 1).name    ;         \
        }                                                              \
      else                                                             \
        { /* empty RHS */                                              \
          (Current).first_line   = (Current).last_line   =             \
            YYRHSLOC (Rhs, 0).last_line;                               \
          (Current).first_column = (Current).last_column =             \
            YYRHSLOC (Rhs, 0).last_column;                             \
          (Current).name = NULL;                        /* new */ \
        }                                                              \
    while (0)
#define YYLTYPE SourcePos
#define yytnamerr lYYTNameErr
Function Documentation
if (s)
Referenced by GetStructTypesNamesPositions(), lCostCallbackPre(), and lVaryingBCPreFunc().
TOKEN_LAUNCH postfix_expression (' ')
Definition at line 39027 of file parse.yy.
Variable Documentation
primary_expression __pad0__
Definition at line 38943 of file parse.yy.
launch_expression __pad1__
Definition at line 39018 of file parse.yy.
launch_expression int32_t
Definition at line 39018 of file parse.yy.
Referenced by ConstExpr::ConstExpr(), ConstExpr::GetConstant(), lApplyLoad4(), lCheckAllOffSafety(), lCheckIndicesVersusBounds(), lGetOffsetScaleVec(), lGSBaseOffsetsGetMoreConst(), LLVMConcatVectors(), lSplit8WideLoads(), lUpdateVaryingCounter(), lVectorIs32BitInts(), TypeCastExpr::Optimize(), Target::SizeOf(), and Target::StructOffset().
launch_expression Expr* launchCount[3] = {oneExpr, oneExpr, oneExpr}
Definition at line 39024 of file parse.yy.
Referenced by FunctionCallExpr::GetValue().
Symbol* s = m->symbolTable->LookupVariable(name)
Definition at line 38948 of file parse.yy.
Referenced by CaseStmt::CaseStmt(), CoalescedLoadOp::CoalescedLoadOp(), DefaultStmt::DefaultStmt(), ForeachActiveStmt::ForeachActiveStmt(), ForeachUniqueStmt::ForeachUniqueStmt(), Function::Function(), ArrayType::GetCDeclaration(), VectorType::GetCDeclaration(), ArrayType::GetString(), VectorType::GetString(), LabeledStmt::LabeledStmt(), lGetStringAsValue(), LLVMGetName(), lParseInclude(), ArrayType::Mangle(), VectorType::Mangle(), ReplaceStdlibShiftPass::runOnBasicBlock(), FunctionEmitContext::SwitchInst(), SwitchStmt::SwitchStmt(), SymbolExpr::SymbolExpr(), UnmaskedStmt::UnmaskedStmt(), and VariableDeclaration::VariableDeclaration().