Intel SPMD Program Compiler: stmt.cpp File Reference
stmt.cpp File Reference
File with definitions classes related to statements in the language.
#include "stmt.h"
#include "ctx.h"
#include "util.h"
#include "expr.h"
#include "type.h"
#include "sym.h"
#include "module.h"
#include "llvmutil.h"
#include <stdio.h>
#include <map>
#include <llvm/Module.h>
#include <llvm/Function.h>
#include <llvm/Type.h>
#include <llvm/DerivedTypes.h>
#include <llvm/LLVMContext.h>
#include <llvm/Metadata.h>
#include <llvm/Instructions.h>
#include <llvm/CallingConv.h>
#include <llvm/Support/IRBuilder.h>
#include <llvm/Support/raw_ostream.h>
Classes
struct VaryingBCCheckInfo
struct SwitchVisitInfo
Functions
static bool lPossiblyResolveFunctionOverloads (Expr *expr, const Type *type)
static void lInitSymbol (llvm::Value *lvalue, const char *symName, const Type *symType, Expr *initExpr, FunctionEmitContext *ctx, SourcePos pos)
static bool lHasUnsizedArrays (const Type *type)
static void lEmitIfStatements (FunctionEmitContext *ctx, Stmt *stmts, const char *trueOrFalse)
static bool lCheckAllOffSafety (ASTNode *node, void *data)
static bool lIsVaryingFor (ASTNode *node)
static bool lVaryingBCPreFunc (ASTNode *node, void *d)
static ASTNode * lVaryingBCPostFunc (ASTNode *node, void *d)
static bool lHasVaryingBreakOrContinue (Stmt *stmt)
static llvm::Value * lUpdateVaryingCounter (int dim, int nDims, FunctionEmitContext *ctx, llvm::Value *uniformCounterPtr, llvm::Value *varyingCounterPtr, const std::vector< int > &spans)
static int lLog2 (int i)
static void lGetSpans (int dimsLeft, int nDims, int itemsLeft, bool isTiled, int *a)
static bool lCheckMask (Stmt *stmts)
static bool lSwitchASTPreVisit (ASTNode *node, void *d)
static char lEncodeType (const Type *t)
static llvm::Value * lProcessPrintArg (Expr *expr, FunctionEmitContext *ctx, std::string &argTypes)
Detailed Description
File with definitions classes related to statements in the language.
Definition in file stmt.cpp.
Function Documentation
static bool lCheckAllOffSafety (ASTNode * node, void * data) [static]
Given an AST node, check to see if it's safe if we happen to run the code for that node with the execution mask all off.
Definition at line 628 of file stmt.cpp.
References Target::allOffMaskIsSafe, ConstExpr::AsInt32(), Assert, IndexExpr::baseExpr, MemberExpr::dereferenceExpr, DereferenceExpr::expr, g, CollectionType::GetElementCount(), Type::GetReferenceTarget(), Expr::GetType(), IndexExpr::index, int32_t, ISPC_MAX_NVEC, NULL, and Globals::target.
Referenced by IfStmt::emitVaryingIf(), and lCheckMask().
static bool lCheckMask (Stmt * stmts) [static]
Given the statements following a 'case' or 'default' label, this function determines whether the mask should be checked to see if it is "all off" immediately after the label, before executing the code for the statements.
Definition at line 2121 of file stmt.cpp.
References lCheckAllOffSafety(), NULL, and PREDICATE_SAFE_IF_STATEMENT_COST.
Referenced by CaseStmt::EmitCode(), and DefaultStmt::EmitCode().
static void lEmitIfStatements (FunctionEmitContext * ctx, Stmt * stmts, const char * trueOrFalse) [static]
Definition at line 485 of file stmt.cpp.
References FunctionEmitContext::AddInstrumentationPoint(), Stmt::EmitCode(), FunctionEmitContext::EndScope(), NULL, and FunctionEmitContext::StartScope().
Referenced by IfStmt::EmitCode(), IfStmt::emitMaskAllOn(), IfStmt::emitMaskedTrueAndFalse(), and IfStmt::emitMaskMixed().
static char lEncodeType (const Type * t) [static]
Definition at line 2631 of file stmt.cpp.
References Type::IsUniformType(), NULL, AtomicType::UniformBool, AtomicType::UniformDouble, AtomicType::UniformFloat, AtomicType::UniformInt32, AtomicType::UniformInt64, AtomicType::UniformUInt32, AtomicType::UniformUInt64, AtomicType::VaryingBool, AtomicType::VaryingDouble, AtomicType::VaryingFloat, AtomicType::VaryingInt32, AtomicType::VaryingInt64, AtomicType::VaryingUInt32, and AtomicType::VaryingUInt64.
Referenced by lProcessPrintArg().
static void lGetSpans (int dimsLeft, int nDims, int itemsLeft, bool isTiled, int * a) [static]
Definition at line 1541 of file stmt.cpp.
References lLog2().
Referenced by ForeachStmt::EmitCode().
static bool lHasUnsizedArrays (const Type * type) [static]
Definition at line 270 of file stmt.cpp.
References ArrayType::GetElementCount(), ArrayType::GetElementType(), and NULL.
Referenced by DeclStmt::EmitCode().
static bool lHasVaryingBreakOrContinue (Stmt * stmt) [static]
Given a statment, walk through it to see if there is a 'break' or 'continue' statement inside if its children, under varying control flow. We need to detect this case for loops since what might otherwise look like a 'uniform' loop needs to have code emitted to do all of the lane management stuff if this is the case.
Definition at line 1002 of file stmt.cpp.
References VaryingBCCheckInfo::foundVaryingBreakOrContinue, lVaryingBCPostFunc(), and lVaryingBCPreFunc().
Referenced by ForStmt::EmitCode(), SwitchStmt::EmitCode(), DoStmt::EstimateCost(), ForStmt::EstimateCost(), DoStmt::TypeCheck(), and ForStmt::TypeCheck().
static void lInitSymbol (llvm::Value * lvalue, const char * symName, const Type * symType, Expr * initExpr, FunctionEmitContext * ctx, SourcePos pos) [static]
Utility routine that emits code to initialize a symbol given an initializer expression.
Parameters:
lvalue Memory location of storage for the symbol's data
symName Name of symbol (used in error messages)
symType Type of variable being initialized
initExpr Expression for the initializer
ctx FunctionEmitContext to use for generating instructions
pos Source file position of the variable being initialized
Definition at line 155 of file stmt.cpp.
References FunctionEmitContext::AddElementOffset(), Type::Equal(), Error(), ExprList::exprs, FATAL, CollectionType::GetElementCount(), FunctionEmitContext::GetElementPtrInst(), CollectionType::GetElementType(), Type::GetString(), ReferenceType::GetString(), Expr::GetType(), PointerType::GetUniform(), Expr::GetValue(), LLVMInt32(), lPossiblyResolveFunctionOverloads(), NULL, FunctionEmitContext::StoreInst(), and TypeConvertExpr().
Referenced by DeclStmt::EmitCode().
static bool lIsVaryingFor (ASTNode * node) [static]
Returns true if the given node is an 'if' statement where the test condition has varying type.
Definition at line 940 of file stmt.cpp.
References Expr::GetType(), Type::IsVaryingType(), NULL, and IfStmt::test.
Referenced by lVaryingBCPostFunc(), and lVaryingBCPreFunc().
static int lLog2 (int i) [static]
Returns the integer log2 of the given integer.
Definition at line 1521 of file stmt.cpp.
Referenced by lGetSpans().
static bool lPossiblyResolveFunctionOverloads (Expr * expr, const Type * type) [static]
Definition at line 123 of file stmt.cpp.
References Type::GetBaseType(), FunctionType::GetNumParameters(), FunctionType::GetParameterType(), NULL, and FunctionSymbolExpr::ResolveOverloads().
Referenced by DeclStmt::EmitCode(), and lInitSymbol().
static llvm::Value* lProcessPrintArg (Expr * expr, FunctionEmitContext * ctx, std::string & argTypes) [static]
Given an Expr for a value to be printed, emit the code to evaluate the expression and store the result to alloca'd memory. Update the argTypes string with the type encoding for this expression.
Definition at line 2661 of file stmt.cpp.
References FunctionEmitContext::AllocaInst(), FunctionEmitContext::BitCastInst(), Globals::ctx, Error(), g, Type::GetAsNonConstType(), Type::GetAsUniformType(), Type::GetString(), Expr::GetType(), Expr::GetValue(), Type::IsUniformType(), lEncodeType(), LLVM_TYPE_CONST, Type::LLVMType(), NULL, FunctionEmitContext::StoreInst(), AtomicType::UniformInt16, AtomicType::UniformInt32, AtomicType::UniformInt8, AtomicType::UniformUInt16, AtomicType::UniformUInt8, AtomicType::VaryingInt32, and LLVMTypes::VoidPointerType.
Referenced by PrintStmt::EmitCode().
static bool lSwitchASTPreVisit (ASTNode * node, void * d) [static]
Definition at line 2254 of file stmt.cpp.
References SwitchVisitInfo::caseBlocks, FunctionEmitContext::CreateBasicBlock(), SwitchVisitInfo::ctx, SwitchVisitInfo::defaultBlock, Error(), SwitchVisitInfo::lastBlock, SwitchVisitInfo::nextBlock, NULL, and CaseStmt::value.
Referenced by SwitchStmt::EmitCode().
static llvm::Value* lUpdateVaryingCounter (int dim, int nDims, FunctionEmitContext * ctx, llvm::Value * uniformCounterPtr, llvm::Value * varyingCounterPtr, const std::vector< int > & spans) [static]
Definition at line 1477 of file stmt.cpp.
References FunctionEmitContext::BinaryOperator(), g, FunctionEmitContext::InsertInst(), int32_t, LLVMTypes::Int32VectorType, ISPC_MAX_NVEC, LLVMInt32Vector(), FunctionEmitContext::LoadInst(), FunctionEmitContext::StoreInst(), Globals::target, and Target::vectorWidth.
Referenced by ForeachStmt::EmitCode().
static ASTNode* lVaryingBCPostFunc (ASTNode * node, void * d) [static]
Postorder callback function for checking for varying breaks or continues; decrement the varying control flow depth after the node's children have been processed, if this is a varying if statement.
Definition at line 987 of file stmt.cpp.
References lIsVaryingFor(), and VaryingBCCheckInfo::varyingControlFlowDepth.
Referenced by lHasVaryingBreakOrContinue().
static bool lVaryingBCPreFunc (ASTNode * node, void * d) [static]
Preorder callback function for checking for varying breaks or continues.
Definition at line 955 of file stmt.cpp.
References VaryingBCCheckInfo::foundVaryingBreakOrContinue, if(), lIsVaryingFor(), NULL, and VaryingBCCheckInfo::varyingControlFlowDepth.
Referenced by lHasVaryingBreakOrContinue().