Intel SPMD Program Compiler: SourcePos Struct Reference
SourcePos Struct Reference
Representation of a range of positions in a source file.
#include <ispc.h>
Public Member Functions
SourcePos (const char *n=NULL, int fl=0, int fc=0, int ll=0, int lc=0)
void Print () const
llvm::DIFile GetDIFile () const
bool operator== (const SourcePos &p2) const
Public Attributes
const char * name
int first_line
int first_column
int last_line
int last_column
Detailed Description
Representation of a range of positions in a source file.
This class represents a range of characters in a source file (e.g. those that span a token's definition), from starting line and column to ending line and column. (These values are tracked by the lexing code). Both lines and columns are counted starting from one.
Definition at line 128 of file ispc.h.
Constructor & Destructor Documentation
SourcePos::SourcePos (const char * n = NULL, int fl = 0, int fc = 0, int ll = 0, int lc = 0)
Definition at line 1083 of file ispc.cpp.
References first_column, first_line, last_column, last_line, Module::module, and name.
Member Function Documentation
llvm::DIFile SourcePos::GetDIFile () const
Returns a LLVM DIFile object that represents the SourcePos's file
Definition at line 1099 of file ispc.cpp.
References Assert, Globals::currentDirectory, Module::diBuilder, filename, GetDirectoryAndFileName(), and name.
Referenced by Module::AddGlobalVariable(), FunctionEmitContext::EmitFunctionParameterDebugInfo(), FunctionEmitContext::EmitVariableDebugInfo(), FunctionEmitContext::FunctionEmitContext(), EnumType::GetDIType(), StructType::GetDIType(), and UndefinedStructType::GetDIType().
bool SourcePos::operator== (const SourcePos & p2) const
Definition at line 1116 of file ispc.cpp.
References first_column, first_line, last_column, last_line, and name.
void SourcePos::Print () const
Prints the filename and line/column range to standard output.
Definition at line 1109 of file ispc.cpp.
References first_column, first_line, last_column, last_line, and name.
Referenced by ExprStmt::Print(), DeclStmt::Print(), UnaryExpr::Print(), IfStmt::Print(), Declarator::Print(), BinaryExpr::Print(), DoStmt::Print(), ForStmt::Print(), AssignExpr::Print(), BreakStmt::Print(), SelectExpr::Print(), ContinueStmt::Print(), ExprList::Print(), ForeachStmt::Print(), ForeachActiveStmt::Print(), FunctionCallExpr::Print(), ForeachUniqueStmt::Print(), IndexExpr::Print(), UnmaskedStmt::Print(), ReturnStmt::Print(), MemberExpr::Print(), CaseStmt::Print(), DefaultStmt::Print(), SwitchStmt::Print(), ConstExpr::Print(), StmtList::Print(), TypeCastExpr::Print(), ReferenceExpr::Print(), PtrDerefExpr::Print(), RefDerefExpr::Print(), AddressOfExpr::Print(), SizeOfExpr::Print(), SymbolExpr::Print(), FunctionSymbolExpr::Print(), SyncExpr::Print(), and NullPointerExpr::Print().
Member Data Documentation
int SourcePos::first_column
Definition at line 134 of file ispc.h.
Referenced by FunctionEmitContext::AddDebugPos(), FunctionEmitContext::addGSMetadata(), AssertStmt::EmitCode(), lPrint(), lPrintFileLineContext(), operator==(), Print(), SourcePos(), FunctionEmitContext::StartScope(), and Union().
int SourcePos::first_line
Definition at line 133 of file ispc.h.
Referenced by FunctionEmitContext::AddDebugPos(), Module::AddFunctionDeclaration(), Module::AddGlobalVariable(), FunctionEmitContext::addGSMetadata(), FunctionEmitContext::AddInstrumentationPoint(), DeclStmt::EmitCode(), AssertStmt::EmitCode(), FunctionEmitContext::EmitFunctionParameterDebugInfo(), FunctionEmitContext::EmitVariableDebugInfo(), FunctionEmitContext::FunctionEmitContext(), EnumType::GetDIType(), StructType::GetDIType(), UndefinedStructType::GetDIType(), lCoalescePerfInfo(), lPrint(), lPrintFileLineContext(), operator==(), Print(), SourcePos(), FunctionEmitContext::StartScope(), and Union().
int SourcePos::last_column
Definition at line 136 of file ispc.h.
Referenced by FunctionEmitContext::addGSMetadata(), lPrintFileLineContext(), operator==(), Print(), SourcePos(), and Union().
int SourcePos::last_line
Definition at line 135 of file ispc.h.
Referenced by FunctionEmitContext::addGSMetadata(), lPrintFileLineContext(), operator==(), Print(), SourcePos(), and Union().
const char* SourcePos::name
Definition at line 132 of file ispc.h.
Referenced by Module::AddFunctionDeclaration(), Module::AddGlobalVariable(), FunctionEmitContext::addGSMetadata(), FunctionEmitContext::AddInstrumentationPoint(), AssertStmt::EmitCode(), GetDIFile(), lCreateISPCSymbol(), lCreateSymbol(), lPrint(), lPrintFileLineContext(), operator==(), PerformanceWarning(), Print(), SourcePos(), and Union().
The documentation for this struct was generated from the following files:
ispc.h
ispc.cpp