Intel® Implicit SPMD Program Compiler (Intel® ISPC): target_enums.cpp File Reference
target_enums.cpp File Reference
Define enums describing target platform.
#include "target_enums.h"
#include "ispc.h"
#include "util.h"
#include <cstring>
Functions
Arch ParseArch (std::string arch)
std::string ArchToString (Arch arch)
ISPCTarget ParseISPCTarget (std::string target)
std::pair< std::vector< ISPCTarget >, std::string > ParseISPCTargets (const char *target)
std::string ISPCTargetToString (ISPCTarget target)
bool ISPCTargetIsX86 (ISPCTarget target)
bool ISPCTargetIsGeneric (ISPCTarget target)
bool ISPCTargetIsNeon (ISPCTarget target)
bool ISPCTargetIsWasm (ISPCTarget target)
TargetOS ParseOS (std::string os)
std::string OSToString (TargetOS os)
std::string OSToLowerString (TargetOS os)
TargetOS GetHostOS ()
Detailed Description
Define enums describing target platform.
Definition in file target_enums.cpp.
Function Documentation
ArchToString()
std::string ArchToString (Arch arch)
Definition at line 60 of file target_enums.cpp.
References aarch64, arm, error, Error(), none, wasm32, x86, and x86_64.
Referenced by TargetLibRegistry::getSupportedArchs(), main(), BitcodeLib::print(), TargetLibRegistry::printSupportMatrix(), and Target::Target().
GetHostOS()
TargetOS GetHostOS ()
Definition at line 390 of file target_enums.cpp.
References error, freebsd, linux, macos, and windows.
Referenced by Globals::Globals().
ISPCTargetIsGeneric()
bool ISPCTargetIsGeneric (ISPCTarget target)
Definition at line 276 of file target_enums.cpp.
References generic_1, generic_16, generic_32, generic_4, generic_64, and generic_8.
Referenced by Module::CompileAndOutput().
ISPCTargetIsNeon()
bool ISPCTargetIsNeon (ISPCTarget target)
Definition at line 290 of file target_enums.cpp.
References neon_i16x8, neon_i32x4, neon_i32x8, and neon_i8x16.
Referenced by Target::Target().
ISPCTargetIsWasm()
bool ISPCTargetIsWasm (ISPCTarget target)
Definition at line 302 of file target_enums.cpp.
References wasm_i32x4.
ISPCTargetIsX86()
bool ISPCTargetIsX86 (ISPCTarget target)
Definition at line 251 of file target_enums.cpp.
References avx1_i32x16, avx1_i32x4, avx1_i32x8, avx1_i64x4, avx2_i32x16, avx2_i32x4, avx2_i32x8, avx2_i64x4, avx512knl_i32x16, avx512skx_i32x16, avx512skx_i32x8, sse2_i32x4, sse2_i32x8, sse4_i16x8, sse4_i32x4, sse4_i32x8, and sse4_i8x16.
Referenced by lIsTargetValidforArch().
ISPCTargetToString()
std::string ISPCTargetToString (ISPCTarget target)
Definition at line 182 of file target_enums.cpp.
References avx1_i32x16, avx1_i32x4, avx1_i32x8, avx1_i64x4, avx2_i32x16, avx2_i32x4, avx2_i32x8, avx2_i64x4, avx512knl_i32x16, avx512skx_i32x16, avx512skx_i32x8, error, Error(), generic_1, generic_16, generic_32, generic_4, generic_64, generic_8, host, neon_i16x8, neon_i32x4, neon_i32x8, neon_i8x16, none, sse2_i32x4, sse2_i32x8, sse4_i16x8, sse4_i32x4, sse4_i32x8, sse4_i8x16, and wasm_i32x4.
Referenced by TargetLibRegistry::getSupportedTargets(), main(), BitcodeLib::print(), TargetLibRegistry::printSupportMatrix(), and Target::Target().
OSToLowerString()
std::string OSToLowerString (TargetOS os)
Definition at line 364 of file target_enums.cpp.
References android, custom_linux, error, freebsd, ios, linux, macos, ps4, UNREACHABLE, web, and windows.
Referenced by TargetLibRegistry::getSupportedOSes().
OSToString()
std::string OSToString (TargetOS os)
Definition at line 338 of file target_enums.cpp.
References android, custom_linux, error, freebsd, ios, linux, macos, ps4, UNREACHABLE, web, and windows.
Referenced by BitcodeLib::print(), and TargetLibRegistry::printSupportMatrix().
ParseArch()
Arch ParseArch (std::string arch)
Definition at line 45 of file target_enums.cpp.
References aarch64, arm, error, wasm32, x86, and x86_64.
Referenced by main().
ParseISPCTarget()
ISPCTarget ParseISPCTarget (std::string target)
Definition at line 84 of file target_enums.cpp.
References avx1_i32x16, avx1_i32x4, avx1_i32x8, avx1_i64x4, avx2_i32x16, avx2_i32x4, avx2_i32x8, avx2_i64x4, avx512knl_i32x16, avx512skx_i32x16, avx512skx_i32x8, error, generic_1, generic_16, generic_32, generic_4, generic_64, generic_8, host, neon_i32x4, neon_i32x8, neon_i8x16, sse2_i32x4, sse2_i32x8, sse4_i16x8, sse4_i32x4, sse4_i32x8, sse4_i8x16, and wasm_i32x4.
Referenced by Module::CompileAndOutput(), and ParseISPCTargets().
ParseISPCTargets()
std::pair<std::vector<ISPCTarget>, std::string> ParseISPCTargets (const char * target)
Definition at line 156 of file target_enums.cpp.
References error, and ParseISPCTarget().
Referenced by main().
ParseOS()
TargetOS ParseOS (std::string os)
Definition at line 311 of file target_enums.cpp.
References android, custom_linux, error, freebsd, g, TargetLibRegistry::getSupportedOSes(), ios, linux, macos, ps4, Globals::target_registry, web, and windows.
Referenced by main().