Intel SPMD Program Compiler: util.h File Reference
util.h File Reference
#include "ispc.h"
Macros
#define PRINTF_FUNC
#define FATAL(message) FatalError(__FILE__, __LINE__, message)
#define PRINTF_FUNC
#define FATAL(message) FatalError(__FILE__, __LINE__, message)
#define PRINTF_FUNC
#define FATAL(message) FatalError(__FILE__, __LINE__, message)
#define PRINTF_FUNC
#define FATAL(message) FatalError(__FILE__, __LINE__, message)
#define PRINTF_FUNC
#define FATAL(message) FatalError(__FILE__, __LINE__, message)
#define PRINTF_FUNC
#define FATAL(message) FatalError(__FILE__, __LINE__, message)
Functions
uint32_t RoundUpPow2 (uint32_t v)
void Debug (SourcePos p, const char *format,...) PRINTF_FUNC
void Warning (SourcePos p, const char *format,...) PRINTF_FUNC
void Error (SourcePos p, const char *format,...) PRINTF_FUNC
void PerformanceWarning (SourcePos p, const char *format,...) PRINTF_FUNC
void FatalError (const char *file, int line, const char *message)
int StringEditDistance (const std::string &str1, const std::string &str2, int maxDist)
std::vector< std::string > MatchStrings (const std::string &str, const std::vector< std::string > &options)
void GetDirectoryAndFileName (const std::string &currentDir, const std::string &relativeName, std::string *directory, std::string *filename)
bool VerifyDataLayoutCompatibility (const std::string &module_dl, const std::string &lib_dl)
void PrintWithWordBreaks (const char *buf, int indent, int columnWidth, FILE *out)
int TerminalWidth ()
Detailed Description
Definition in file util.h.
Macro Definition Documentation
#define FATAL (message) FatalError(__FILE__, __LINE__, message)
Reports a fatal error that causes the program to terminate. This should only be used for cases where there is an internal error in the compiler.
Definition at line 113 of file util.h.
Referenced by ConstExpr::ConstExpr(), DefineStdlib(), UndefinedStructType::GetAsSOAType(), FunctionType::GetAsSOAType(), FunctionType::GetAsUnboundVariabilityType(), FunctionType::GetAsUniformType(), AtomicType::GetAsUnsignedType(), FunctionType::GetAsVaryingType(), FunctionType::GetBaseType(), AtomicType::GetCDeclaration(), ExprList::GetConstant(), AtomicType::GetDIType(), EnumType::GetDIType(), PointerType::GetDIType(), VectorType::GetDIType(), CFInfo::GetForeach(), Variability::GetString(), AtomicType::GetString(), UnaryExpr::GetType(), BinaryExpr::GetType(), ExprList::GetType(), UnaryExpr::GetValue(), BinaryExpr::GetValue(), AssignExpr::GetValue(), ExprList::GetValue(), ConstExpr::GetValue(), TypeCastExpr::GetValue(), ConstExpr::GetValues(), VectorType::getVectorMemoryCount(), Globals::Globals(), InitLLVMUtil(), InitSymbol(), Target::ISAToString(), Target::ISAToTargetString(), lAssemble4Vector(), lAssembleResultVectors(), lCoalesceGathers(), lEmitBinaryArith(), lEmitBinaryBitOp(), lEmitBinaryCmp(), lEmitBinaryPointerArith(), lEmitLoads(), lEmitOpAssign(), lGetStorageClassName(), lIsMatchWithTypeWidening(), lLLVMConstantValue(), AtomicType::LLVMType(), EnumType::LLVMType(), PointerType::LLVMType(), VectorType::LLVMType(), FunctionType::LLVMType(), lMangleStructName(), lOpString(), lSignal(), lTypeConvAtomic(), AtomicType::Mangle(), Variability::MangleString(), UnaryExpr::Optimize(), TypeCastExpr::Optimize(), Declarator::Print(), ConstExpr::Print(), FunctionEmitContext::SyncInst(), BinaryExpr::TypeCheck(), WalkAST(), Module::writeDispatchHeader(), Module::writeHeader(), and Module::writeOutput().
#define FATAL (message) FatalError(__FILE__, __LINE__, message)
#define FATAL (message) FatalError(__FILE__, __LINE__, message)
#define FATAL (message) FatalError(__FILE__, __LINE__, message)
#define FATAL (message) FatalError(__FILE__, __LINE__, message)
#define FATAL (message) FatalError(__FILE__, __LINE__, message)
#define PRINTF_FUNC
#define PRINTF_FUNC
#define PRINTF_FUNC
#define PRINTF_FUNC
#define PRINTF_FUNC
Definition at line 65 of file util.h.
#define PRINTF_FUNC
Function Documentation
void Debug (SourcePos p, const char * format, ...)
Prints a debugging message. These messages are only printed if g->debugPrint is true. In addition to a program source code position to associate with the message, a printf()-style format string is passed along with any values needed for items in the format string.
Definition at line 398 of file util.cpp.
References Globals::debugPrint, g, lPrint(), and Globals::quiet.
Referenced by AddBitcodeToModule(), Function::emitCode(), IfStmt::emitVaryingIf(), ConstExpr::GetConstant(), SelectExpr::GetValue(), lApplyLoad1(), lApplyLoad2(), lApplyLoad4(), lAssemble4Vector(), lCreateISPCSymbol(), lCreateSymbol(), lEmitLoads(), lGSToLoadStore(), LLVMVectorIsLinear(), LLVMVectorValuesAllEqual(), lSelectLoads(), lStripUnusedDebugInfo(), BinaryExpr::Optimize(), GatherCoalescePass::runOnBasicBlock(), and TypeConvertExpr().
void Error (SourcePos p, const char * format, ...)
Prints an error message. It is assumd that compilation can not be successfully completed after an error has been issued, though the system tries to continue compiling as much as possible, in order to be able to issue any subsequent error messages. In addition to a program source code position to associate with the message, a printf()-style format string is passed along with any values needed for items in the format string.
Definition at line 385 of file util.cpp.
References Module::errorCount, g, lPrint(), m, and Globals::quiet.
Referenced by AddBitcodeToModule(), Module::AddExportedTypes(), Module::AddFunctionDeclaration(), Module::AddGlobalVariable(), SymbolTable::AddType(), SymbolTable::AddVariable(), FunctionEmitContext::Break(), StructType::checkIfCanBeSOA(), Module::CompileAndOutput(), FunctionEmitContext::Continue(), MemberExpr::create(), FunctionEmitContext::CurrentLanesReturned(), DoAssertPos(), FunctionEmitContext::EmitCaseLabel(), DeclStmt::EmitCode(), ReturnStmt::EmitCode(), GotoStmt::EmitCode(), AssertStmt::EmitCode(), FunctionEmitContext::EmitDefaultLabel(), emitOffloadParamStruct(), Function::GenerateIR(), DeclSpecs::GetBaseType(), ExprList::GetConstant(), FunctionSymbolExpr::GetConstant(), StructMemberExpr::getElementNumber(), VectorMemberExpr::getElementNumber(), GetStructTypesNamesPositions(), FunctionSymbolExpr::GetType(), StructMemberExpr::GetType(), AssignExpr::GetValue(), FunctionCallExpr::GetValue(), VectorMemberExpr::GetValue(), Declaration::GetVariableDeclarations(), Declarator::InitFromDeclSpecs(), Declarator::InitFromType(), FunctionEmitContext::initLabelBBlocks(), InitSymbol(), lApplyTypeQualifiers(), lCheckExportedParameterTypes(), lCheckForConstStructMember(), lCheckForStructParameters(), lConstFoldBinaryArithOp(), lCreateBinaryOperatorCall(), lCreateDispatchFunction(), lDoTypeConv(), lEmitOpAssign(), lEmitPrePostIncDec(), lGetSystemISA(), FunctionEmitContext::LoadInst(), lProcessPrintArg(), lSwitchASTPreVisit(), lVaryingStructHasUniformMember(), lVectorConvert(), Type::MoreGeneralType(), NewExpr::NewExpr(), FunctionSymbolExpr::ResolveOverloads(), ArrayType::SizeUnsizedArrays(), FunctionEmitContext::StartForeach(), FunctionEmitContext::StoreInst(), StructType::StructType(), Target::Target(), UnaryExpr::TypeCheck(), BinaryExpr::TypeCheck(), AssignExpr::TypeCheck(), ForeachStmt::TypeCheck(), FunctionCallExpr::TypeCheck(), ForeachUniqueStmt::TypeCheck(), IndexExpr::TypeCheck(), LabeledStmt::TypeCheck(), TypeCastExpr::TypeCheck(), DeleteStmt::TypeCheck(), PtrDerefExpr::TypeCheck(), AddressOfExpr::TypeCheck(), SizeOfExpr::TypeCheck(), NewExpr::TypeCheck(), Module::writeDevStub(), and Module::writeOutput().
void FatalError (const char * file, int line, const char * message)
This function generally shouldn't be called directly, but should be used via the FATAL macro, which includes the file and line number where the error was issued.
Definition at line 455 of file util.cpp.
References lPrintBugText().
void GetDirectoryAndFileName (const std::string & currentDir, const std::string & relativeName, std::string * directory, std::string * filename)
Given the current working directory and a filename relative to that directory, this function returns the final directory that the resulting file is in and the base name of the file itself.
Definition at line 547 of file util.cpp.
References Assert, Globals::currentDirectory, and g.
Referenced by SourcePos::GetDIFile(), and Module::Module().
std::vector<std::string> MatchStrings (const std::string & str, const std::vector< std::string > & options)
Given a string and a set of candidate strings, returns the set of candidates that are "close" to the given string, where distance is measured by the number of single-character changes needed to transform between the two. An empty vector may be returned if none of the options is close to str.
Definition at line 519 of file util.cpp.
References StringEditDistance().
Referenced by GotoStmt::EmitCode(), and MemberExpr::getCandidateNearMatches().
void PerformanceWarning (SourcePos p, const char * format, ...)
Prints a message about a potential performance issue in the user's code. These messages are purely informative and don't affect the completion of compilation. In addition to a program source code position to associate with the message, a printf()-style format string is passed along with any values needed for items in the format string.
Definition at line 426 of file util.cpp.
References Globals::emitPerfWarnings, g, lPrint(), SourcePos::name, and Globals::quiet.
Referenced by DeclStmt::EmitCode(), DeclSpecs::GetBaseType(), BinaryExpr::GetValue(), lCoalescePerfInfo(), lEmitBinaryArith(), lReplacePseudoGS(), lTypeConvAtomic(), and ReplaceStdlibShiftPass::runOnBasicBlock().
void PrintWithWordBreaks (const char * buf, int indent, int columnWidth, FILE * out)
Print the given string to the given FILE, assuming the given output column width. Break words as needed to avoid words spilling past the last column.
Definition at line 230 of file util.cpp.
References lFindWordEnd().
Referenced by lPrint(), and usage().
uint32_t RoundUpPow2 (uint32_t v) inline
Rounds up the given value to the next power of two, if it isn't a power of two already.
Definition at line 51 of file util.h.
Referenced by Module::AddFunctionDeclaration(), and FunctionEmitContext::LaunchInst().
int StringEditDistance (const std::string & str1, const std::string & str2, int maxDist)
Returns the number of single-character edits needed to transform between the two strings.
Parameters
str1 First string
str2 Second string
maxDist Maximum number of single-character edits allowed
Returns
Number of single-character edits to transform from str1 to str2, or maxDist+1 if it's not psosible to do so in fewer than maxDist steps
Definition at line 482 of file util.cpp.
Referenced by SymbolTable::closestTypeMatch(), SymbolTable::ClosestVariableOrFunctionMatch(), and MatchStrings().
int TerminalWidth ()
Returns the width of the terminal where the compiler is running. Finding this out may fail in a variety of reasonable situations (piping compiler output to 'less', redirecting output to a file, running the compiler under a debuffer; in this case, just return a reasonable default.
Definition at line 81 of file util.cpp.
References Globals::disableLineWrap, g, and STDOUT_FILENO.
Referenced by lPrint(), and usage().
bool VerifyDataLayoutCompatibility (const std::string & module_dl, const std::string & lib_dl)
Verification routine, which ensures that DataLayout of the module being compiled is compatible with DataLayout of the library. At the moment we allow the library DataLayout to a subset of the module DataLayout (and extra floating point and vector types to be defined for module) or empty library DataLayout.
Definition at line 603 of file util.cpp.
References lGetStringArray().
Referenced by AddBitcodeToModule().
void Warning (SourcePos p, const char * format, ...)
Prints a warning about an issue found during compilation. Compilation can still continue after warnings; they are purely informative for the user. In addition to a program source code position to associate with the message, a printf()-style format string is passed along with any values needed for items in the format string.
Definition at line 410 of file util.cpp.
References Globals::disableWarnings, Module::errorCount, g, lPrint(), m, Globals::quiet, and Globals::warningsAsErrors.
Referenced by AddBitcodeToModule(), Module::AddFunctionDeclaration(), SymbolTable::AddVariable(), Function::emitCode(), IfStmt::EmitCode(), DoStmt::EmitCode(), ForStmt::EmitCode(), DeclSpecs::GetBaseType(), TypeCastExpr::GetValue(), Declarator::InitFromType(), lCheckIndicesVersusBounds(), lExtractOrCheckGlobals(), lGSToLoadStore(), main(), BinaryExpr::Optimize(), FunctionSymbolExpr::ResolveOverloads(), Target::Target(), TypeCastExpr::TypeCheck(), Module::writeDevStub(), Module::writeHostStub(), and Module::writeOutput().